### ISSUE TITLE
[firebase_auth] add support to set custom user claims

### ISSUE THREAD

**Issue by SwissCheese5** [FirebaseExtended/flutterfire#106]
**Is your feature request related to a problem? Please describe.**
You currently can't set custom information to a FirebaseUser object.

**Describe the solution you'd like**
Support is just not enabled in the plugin, but is available in other firebase auth SDKs https://firebase.google.com/docs/auth/admin/custom-claims

**Comment by Levi-Lesches** [comment]
The key difference here is that this plugin is meant to be run by the client, whereas the Admin SDK is meant to be run exclusively by the server. Otherwise, anyone can set their own custom claims. The whole point of custom claims is that they come from a single source of truth -- the server/cloud functions.

**Comment by SwissCheese5** [comment]
Thank you for the clarification. Closing

**Comment by bicho19** [comment]
in my case, i need the claims to access a remote server and save other user data (Full Name, Address ...) before redirecting the user to home screen. is there any method (i thought about using Future.delayed for few seconds).

**Comment by Levi-Lesches** [comment]
Have you considered [Cloud Firestore](https://firebase.google.com/docs/firestore)? You can have a document for each user and store their data there.

**Comment by Levi-Lesches** [comment]
Custom claims are exclusively meant for authentication (and they have very tight limits, as well as bloat login times) -- they're really not meant to be used to simply pass data around.

**Comment by bicho19** [comment]
I was using Cloud Firestore before, but decided to move die to some limitations. Cloud function takes a bit of time to set claims on each signup. But for the moment i guess i can live with that.

**Comment by Levi-Lesches** [comment]
I see. Just so you know, custom claims has even more restrictions, the biggest one being that the user needs to logout for any changes to take effect. 

Since this issue is closed anyway, can I help you with using Firestore? I found it to be the most convenient service that Firebase has to offer and I'm curious as to what your limitations are.
