### ISSUE TITLE
[Firebase Messaging] Receive data notifications while the app is terminated

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#1066]
Since we have background execution of dart code now, would it be possible to receive data notifications while the app is terminated?

**Comment by optimygmbh** [comment]
Why is this issue closed? Is it possible to receive data notifications while app is terminated or am I the only one who has this requirement??

**Comment by MrVanosh** [comment]
Not only you :(

**Comment by edisonpagtakhan** [comment]
Any updates on this?

**Comment by msarkrish** [comment]
How to do that with Dart code, any example is there?

**Comment by aakhga** [comment]
@msarkrish Take a look here: https://medium.com/flutter/executing-dart-in-the-background-with-flutter-plugins-and-geofencing-2b3e40a1a124

**Comment by imtoori** [comment]
Why is this issue closed? :/

**Comment by anilraok** [comment]
I'm looking forward for this fix as well

**Comment by bartekpacia** [comment]
*Comment for stats*

I also need this feature.

**Comment by imtoori** [comment]
As I far as I get this issue is closed because the feature is implemented.

[The table](https://pub.dev/packages/firebase_messaging#receiving-messages) in the README is wrong, you can receive data notifications while the app is terminated; just follow [this part](https://pub.dev/packages/firebase_messaging#android-integration) and the section `Optionally handle background messages`

**Comment by infinityCounter** [comment]
@optimygmbh I was able to confirm that I can receive a data notification using the `onBackgroundMessage` callback even if the application is terminated on Android (API 8.1). I then triggered a local notification using the flutter_local_notifications plugin.

@imtoori It seems you're correct but the documentation is very misleading, especially since debug mode is usually closed when apps are terminated in the emulator. Any chance we could get the documentation updated?

I've however yet to confirm if this works after some time(after app is removed from the services whitelist).
