### ISSUE TITLE
[firebase_crashlytics] document opt-in

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#1143]
The [Android Crashlytics documentation](https://firebase.google.com/docs/crashlytics/customize-crash-reports?authuser=0&platform=android) says to enable collection via "Fabric.with(this, new Crashlytics());", but the Flutter plugin's FirebaseCrashlyticsPlugin.registerWith method does this. Does this mean opting out is currently not possible?

**Comment by kroikie** [comment]
@pbaker5

The issue at https://github.com/flutter/flutter/issues/33095 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by tigloo** [comment]
I see that this ticket is labeled as "documentation", but looking at the source I don't see any way how to enable Crashlytics only for opt-in users since initialization already happens at plugin initialization.

Is an opt-in scenario possible and what would it look like? I assume that any GDPR-compliant Flutter dev would need this feature, so wondering why there's not a lot of traffic in this ticket.

**Comment by Ehesp** [comment]
This is a bit of both - the internals need some work but it also needs documented. Will leave open to track.

**Comment by Salakar** [comment]
A new Crashlytics plugin has now landed on master which should solve this issue - with documentation on opt-in.

Checkout the migration guide to get started on upgrading to the new Crashlytics plugin: https://firebase.flutter.dev/docs/migration/
