### ISSUE TITLE
 Unable to generate stack trace element from Dart side error.

### ISSUE THREAD

**Issue by Ankit77** [FirebaseExtended/flutterfire#1288]

**Comment by iapicca** [comment]
Hi @Ankit77 
could you please provide your `flutter doctor -v`
and your `flutter run --verbose`.
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you"

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Comment by feinstein** [comment]
I am getting this error as well, I found it under the investigation of a weird behavior on my app. I am generating a `Stream.erro()` to simulate an error coming from Firestore, the error works fine on the fisrt time I open this new window, but on the second time I get an error saying the `Stream` has already being listed to, but this seems impossible to me as the whole screen has been disposed and recreated, including the `Stream`. So in order to investigate this, I added `Stream.error().doOnEach()` and now the error handling works fine on the first time the screen is shown, but on the second time I don't get any errors on Flutter, I get on Crashlytics, on the console, saying: 

>I/flutter (27086): Error caught by Crashlytics plugin <recordError>:
E/CrashlyticsPlugin(27086): Unable to generate stack trace element from Dart side error.
I/chatty  (27086): uid=10091(com.myapp.myapp) identical 2 lines
E/CrashlyticsPlugin(27086): Unable to generate stack trace element from Dart side error.
I/flutter (27086): firebase_crashlytics: Error reported to Crashlytics.
I/flutter (27086): Error caught by Crashlytics plugin <recordError>:
E/CrashlyticsPlugin(27086): Unable to generate stack trace element from Dart side error.
I/chatty  (27086): uid=10091(com.myapp.myapp) identical 2 lines
E/CrashlyticsPlugin(27086): Unable to generate stack trace element from Dart side error.
I/flutter (27086): Error caught by Crashlytics plugin <recordError>:
E/CrashlyticsPlugin(27086): Unable to generate stack trace element from Dart side error.
I/chatty  (27086): uid=10091(com.myapp.myapp) identical 1 line
E/CrashlyticsPlugin(27086): Unable to generate stack trace element from Dart side error.
I/flutter (27086): firebase_crashlytics: Error reported to Crashlytics.
I/flutter (27086): firebase_crashlytics: Error reported to Crashlytics.
I/eraty.myapp(27086): Background concurrent copying GC freed 88526(3MB) AllocSpace objects, 16(312KB) LOS objects, 50% free, 3MB/7MB, paused 5.336ms total 133.685ms


Flutter 1.12.13+hotfix.8 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 0b8abb4724 (3 weeks ago) • 2020-02-11 11:44:36 -0800
Engine • revision e1e6ced81d
Tools • Dart 2.7.0

**Comment by Mikkelet** [comment]
Having the same problem when trying to add some data to firestore

[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18363.657], locale en-DK)
    • Flutter version 1.12.13+hotfix.8 at C:\src\flutter
    • Framework revision 0b8abb4724 (4 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Mikkel\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[!] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code, 64-bit edition (version 1.42.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

! Doctor found issues in 1 category.

**Comment by helenaford** [comment]
Open p/r that might be able to resolve this (as mentioned above by Blaxou). (https://github.com/FirebaseExtended/flutterfire/pull/1821).

**Comment by Salakar** [comment]
Hey all, given the age of this and that Crashlytics got a rework I don't believe this is a relevant issue anymore, as far as I can tell https://github.com/FirebaseExtended/flutterfire/pull/1821 originally aimed to solve this but was closed due to the Crashlytics rework already covering it and the original PR author confirmed they're no longer having issues.
