### ISSUE TITLE
[firebase_messaging] More control over shouldEstablishDirectChannel property

### ISSUE THREAD

**Issue by shorben07** [FirebaseExtended/flutterfire#1347]
**Is your feature request related to a problem? Please describe.**
shouldEstablishDirectChannel  is always set to true in method configure
```
 } else if ([@"configure" isEqualToString:method]) {
    [FIRMessaging messaging].shouldEstablishDirectChannel = true;
```
So, on iOS Simulators in flutter code onMessage: callback is triggered from the direct channel. The problem is that in onMessage callback we navigate the user to a specific part of the app. 
Our iOS app is configured in such a way that if app is in foreground then notification alert is always presented and onMessage:  is called ONLY if the user tapped on the system notification banner.
```
extension AppDelegate: UNUserNotificationCenterDelegate {
    
    func userNotificationCenter(_ center: UNUserNotificationCenter,
                                willPresent notification: UNNotification,
                                withCompletionHandler completionHandler: @escaping (UNNotificationPresentationOptions) -> Void)
    {
        completionHandler([.alert, .badge, .sound])
    }
}
```
Direct channel works as a silent push means message arrives without any banner etc.
These all lead that in our use case the user suddenly navigated without any interaction from his side.
The issue I have is related to iOS Simulators ONLY

**Describe the solution you'd like**
shouldEstablishDirectChannel should be configurable from dart API

**Additional context**

**Comment by Salakar** [comment]
Hey 👋 

As part of our roadmap (#2582) we've just shipped a complete rework of the `firebase_messaging` plugin that aims to solve this and many other issues. Given that direct channels have now been removed on the Firebase iOS SDKs this issue is now resolved as the rework version has removed all usages of direct channel. 

If you can, please try out the dev release (see the [migration guide](https://firebase.flutter.dev/docs/migration/) for upgrading and for changes) and if you have any feedback then join in the discussion [here](https://github.com/FirebaseExtended/flutterfire/discussions/4023).

Thanks
