### ISSUE TITLE
[cloud_firestore] Kindly add option for inequality value

### ISSUE THREAD

**Issue by shrutikateiosys** [FirebaseExtended/flutterfire#148]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

**Comment by noelmansour** [comment]
Inequality queries are not supported by firestore. This isn't a limitation of the library, but of using firestore itself. See https://firebase.google.com/docs/firestore/query-data/queries#query_limitations

**Comment by shrutikateiosys** [comment]
Why you are not providing this option. we need this. kindly help.

**Comment by cbenhagen** [comment]
@shrutikateiosys Inequality operations don't scale like other operations that use an index. Firestore indexes are good for range queries. With this type of index, for an inequality query, the backend would still have to scan every document in the collection in order to come up with results, and that's extremely bad for performance when the number of documents grows large.

More info: https://stackoverflow.com/a/47252340/3695912

**Comment by iapicca** [comment]
Hi @shrutikateiosys  
is the proposed resolution working for you?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
