### ISSUE TITLE
[CLOUD_FIRESTORE] Add web support

### ISSUE THREAD

**Issue by Arno-Z** [FirebaseExtended/flutterfire#1658]
firebase_core and firebase auth have gotten Flutter for Web support. Please also provide web support for Cloud Firestore.

**Comment by noelmansour** [comment]
It seems like this is being tracked in the flutter project here: https://github.com/flutter/flutter/issues/45293

**Comment by ditman** [comment]
Closing as dup; this is already being worked on here:

https://github.com/FirebaseExtended/flutterfire/pull/1670

**Comment by ialhashim** [comment]
Can we test it out now? whats the time frame for this feature to be merged?

**Comment by ditman** [comment]
@ialhashim I see that you're already trying to clone/reference the branch in the PR, that's the way I'm testing this with multiple (codelab) apps.

> what's the time frame for this feature to be merged?

We're in the PR process. 3 (big) PRs need to be merged for this to be published. I can't give you an exact time frame for this, because of the holidays, but we're getting close!
