### ISSUE TITLE
[firebase_auth_web] Credentials Persistence

### ISSUE THREAD

**Issue by rdev-software** [FirebaseExtended/flutterfire#1771]
On page reload I am loosing currentUser, there is no persistence present ?

**Comment by rich-j** [comment]
The issue as we see it is that the web and iOS/Android versions behave differently. During iOS restart, restoring the user from a previous session with `await firebaseAuth.currentUser()` just works - and you get a `null` if there wasn't a previous user session to restore. During a web restart, the same code always returns `null` even when there was a previous user session. It would be nice for the Dart Firebase API to behave consistently across platforms.

Since we have other state that tells us that we do have a user, we wait for the state to change:

```dart
final maybeUser = await firebaseAuth.onAuthStateChanged
  .timeout(Duration(seconds:5))       // Throws TimeoutException on expiration
  .firstWhere( (user) => user != null )
  .then( (user) => Some( user ) )
  .catchError( (_) => None() );
```

Note that this code is waiting on Firebase authentication internal initialization to occur. Since `currentUser` returns a `Future` it should return a value that includes the knowledge that initialization has completed. The `FirebaseApp.configure` also returns a `Future` that could take in to account internal initialization being completed.

**Comment by Yacine-Benali** [comment]
any updates on this issue ?

**Comment by matthewp672261** [comment]
Curious on this too. Seems inconsistent in it's implementation.

**Comment by Salakar** [comment]
Hey 👋 

Our rework of the `firebase_auth` plugin as part of the [FlutterFire roadmap](https://github.com/FirebaseExtended/flutterfire/issues/2582) was published over a week ago with a ton of fixes and new features. Please could you try the new version and see if this is still an issue for you? If it is then please submit a new up to date GitHub issue.

Support for changing persistence settings was added, see: https://firebase.flutter.dev/docs/auth/usage#persisting-authentication-state

For help migrating to the new plugins please see the new migration guide: https://firebase.flutter.dev/docs/migration
