### ISSUE TITLE
[firebase_dynamic_links] Programmatically generated dynamic link not caught by getInitialLink

### ISSUE THREAD

**Issue by degloff** [FirebaseExtended/flutterfire#1847]
Programmatically generated dynamic links are not properly catched by

`FirebaseDynamicLinks.instance.getInitialLink().`

if the app is closed. However, if the app is open it is properly detected by the listener for new incoming dynamic links. It is not clear to me if it is a setup problem, how I generate the dynamic link. 

**To Reproduce**

First set up Firebase for Flutter project as documented. Then to set up a dynamic link:

```
/// See also
/// https://firebase.google.com/docs/dynamic-links/use-cases/rewarded-referral
/// how to implement referral schemes using Firebase.
Future<ShortDynamicLink> buildDynamicLink(String userId) async {
  final PackageInfo packageInfo = await PackageInfo.fromPlatform();
  final String packageName = packageInfo.packageName;

  var androidParams = AndroidParameters(
    packageName: packageInfo.packageName,
    minimumVersion: Constants.androidVersion, // app version and not the Android OS version
  );

  var iosParams = IosParameters(
    bundleId: packageInfo.packageName,
    minimumVersion: Constants.iosVersion, // app version and not the iOS version
    appStoreId: Constants.iosAppStoreId,
  );

  var socialMetaTagParams = SocialMetaTagParameters(
    title: 'Referral Link',
    description: 'Referred app signup',
  );

  var dynamicLinkParams = DynamicLinkParameters(
    uriPrefix: 'https://xxxxxx.page.link',
    link: Uri.parse('https://www.xxxxxxxxx${Constants.referralLinkPath}?${Constants.referralLinkParam}=$userId'),
    androidParameters: androidParams,
    iosParameters: iosParams,
    socialMetaTagParameters: socialMetaTagParams,
  );

  return dynamicLinkParams.buildShortLink();
}
``` 

This dynamic link then can be shared with other new users.

I listen for initial links at app startup and then for new incoming links.

1) The link properly opens the app if the app is not running but the getInitialLink does not get it.

2) If the app is open the link is properly caught by the listener and all works.

Here is the very simple main.dart that I used to verify 1) that the initial link is not found with FirebaseDynamicLinks.instance.getInitialLink().

```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  PendingDynamicLinkData linkData = await FirebaseDynamicLinks.instance.getInitialLink();
  String link = linkData?.link.toString();
  runApp(MyTestApp(link: link));
}

class MyTestApp extends StatelessWidget {
  final String link;

  MyTestApp({this.link});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        builder: (BuildContext context, Widget child) {
          return Scaffold(
            body: Container(
              child: Center(
                  child: Text('Initial dynamic Firebase link: $link')
              ),
            ),
          );
        }
    );
  }
}
``` 

**Expected behavior**

The link should open the app and trigger `FirebaseDynamicLinks.instance.getInitialLink().`.

**Additional context**

I (think I) properly configured Firebase project with Firebase console. I also verified that with 'signup by email link' and these dynamic links are working as expected, also when the app is not open.

**Comment by degloff** [comment]
Just for reference, this is the way I initialize Firestore dynamic link handling:

```
static Future<FirebaseDynamicLinkHandler> setup ({
    @required AuthService auth,
    @required UserDataService userDataService,
    @required EmailSecureStore userCredentialsStorage,
  }) async {

    final linkHandler = FirebaseDynamicLinkHandler(
      auth: auth,
      userDataService: userDataService,
      widgetsBinding: WidgetsBinding.instance,
      emailStore: userCredentialsStorage,
    );

    // Check dynamic link once on app startup. 
    PendingDynamicLinkData linkData = await FirebaseDynamicLinks.instance.getInitialLink();
    linkHandler._processDynamicLink(linkData?.link);

    // Listen to subsequent links
    FirebaseDynamicLinks.instance.onLink(
      onSuccess: (linkData) {
        return linkHandler._handleLink(linkData?.link);
      },
      // convert to PlatformException as OnLinkErrorCallback has private constructor and can't be tested
      onError: (error) => linkHandler._handleLinkError(PlatformException(
        code: error.code,
        message: error.message,
        details: error.details,
      )),
    );

    return linkHandler;
  }
```

**Comment by pneves001** [comment]
name: partymein
description: Party Me In is an event planning and chat program.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^3.2.2
  font_awesome_flutter: ^8.5.0
  firebase_core: ^0.4.3+2
  firebase_auth: 0.14.0+9
  flutter_facebook_login: ^2.0.1
  google_sign_in: 4.0.6
  image_picker: ^0.6.1+10
  contacts_service: ^0.3.0
  intl: ^0.16.1
  flutter_calendar_carousel: ^1.4.10
  http: ^0.12.0+2
  device_calendar: 1.0.0+2
  web_socket_channel: ^1.1.0
  firebase_messaging: ^6.0.9
  path_provider: ^1.3.0
  network_image_to_byte: ^0.0.1
  bitmap: ^0.0.5
  firebase_dynamic_links: ^0.5.0+9
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  

  
  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:

  assets:
    - assets/images/event-details.png
    - assets/images/logo.png
    - assets/images/image-login.png
    - assets/images/event1.png
    - assets/images/event2.png
    - assets/images/event3.png


    - assets/res/config.json
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

**Comment by ciceropablo** [comment]
Same here.

**Comment by degloff** [comment]
Hi Paoblo, this means you can confirm the behaviour that I see too?

**Comment by degloff** [comment]
Either we miss something in the config/setup or it is really a bug. Would be good to confirm.

**Comment by pneves001** [comment]
when you set your intent. You need to set it to the link set in the firebase console to make it work. I closed the issue because I found 1 little inconspicuous line in the documentation on the firebase page that said you had to use your Dynamic Link domain. Not the deep link domain for your platform.

It should work then.

**Comment by surveshoeb** [comment]
I'm also facing this same issue. The issue is that FirebaseDynamicLinks.instance.getInitialLink() always capture the first link which opens the application. If the application is not opened via a dynamic link it will always return a null value. 

Scenario 1:
The app is invoked via dynamic URL, getInitialLink() return the correct URL.
Scenario 2:
The app was in the background and it was resumed via dynamic URL, getInitialLink() returns null or previous record.

**Comment by surveshoeb** [comment]
I fixed this issue by using this code

```dart
@override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
    _retrieveDynamicLink();
  }
  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    if (state == AppLifecycleState.resumed) {
      _retrieveDynamicLink();
    }
  }
  Future<void> _retrieveDynamicLink() async {
    FirebaseDynamicLinks.instance.onLink(
        onSuccess: (PendingDynamicLinkData data) async {
      final Uri deepLink = data?.link;
      print(deepLink);
      if (deepLink != null) {
        print(deepLink.pathSegments);
        List list = deepLink.pathSegments;
        if (list != null && list.isNotEmpty) {
          print(list.first);
          DocumentSnapshot snapshot = await Firestore.instance
              .collection("events")
              .document(list.first)
              .get();
          if (snapshot != null && snapshot.exists) {
            Navigator.push(
              context,
              MaterialPageRoute(
                builder: (context) =>
                    EventViewPage(Event.fromJson(snapshot.data)),
              ),
            );
          }
        }
      }
    }, onError: (OnLinkErrorException e) async {
      print("onLinkError");
      print(e.message);
    });
  }
  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }
```

**Comment by surveshoeb** [comment]
I fixed the issue via this code:

```dart
@override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
    _retrieveDynamicLink();
  }
  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    if (state == AppLifecycleState.resumed) {
      _retrieveDynamicLink();
    }
  }
  Future<void> _retrieveDynamicLink() async {
    FirebaseDynamicLinks.instance.onLink(
        onSuccess: (PendingDynamicLinkData data) async {
      final Uri deepLink = data?.link;
      print(deepLink);
      if (deepLink != null) {
        print(deepLink.pathSegments);
        List list = deepLink.pathSegments;
        if (list != null && list.isNotEmpty) {
          print(list.first);
        }
      }
    }, onError: (OnLinkErrorException e) async {
      print("onLinkError");
      print(e.message);
    });
  }
  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }
```

**Comment by KingIdee** [comment]
Thanks @surveshoeb , your solution helped!

**Comment by russellwheatley** [comment]
Please see this [comment](https://github.com/FirebaseExtended/flutterfire/issues/100#issuecomment-706096896). `getInitialLink` should not be relied to work every single time. It makes an _attempt_ to retrieve the link data on app launch.
