### ISSUE TITLE
[firebase_ml_vision] textRecognizer doesn't work on iOS (no cloudTextRecognizer workaround)

### ISSUE THREAD

**Issue by Alecsplus** [FirebaseExtended/flutterfire#1912]
**Describe the bug**
Same bug of issue 1276
https://github.com/FirebaseExtended/flutterfire/issues/1276

Also in my case I have this problem only on iOS devices.
Text is recognized only with cloudTextRecognizer and not with textRecognizer method (with the same image).

This is a really great problem, because cloud recognition needs billing.

What we can do to to solve it?

Thanks in advance

**To Reproduce**
use textRecognizer() on iOS devices do not works. 
cloudTextRecognizer() works well

**Expected behavior**
textRecognmizer should give a similar result to cloudTextRecognizer

**Additional context**
only iOS. Android works well.

**Comment by iapicca** [comment]
Hi @Alecsplus 
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose` 
and your `pubspec.yaml` 
or if possible a reproducible minimal code sample.
Thank you

**Comment by chaser79** [comment]
The FirebaseVision.instance.textRecognizer() is not recognizing any text on iOS device. It works perfect on an android device. 

To Reproduce
Use FirebaseVision.instance.textRecognizer() on an image to try and recognize text.
```
void _read() {
    progressDialog.show();
    _takePicture().then((String filePath) async {
        final FirebaseVisionImage visionImage =
            FirebaseVisionImage.fromFilePath(filePath);
        final TextRecognizer textRecognizer =
            FirebaseVision.instance.textRecognizer();
        textRecognizer.processImage(visionImage).then((visionText) {
          print(visionText.text);
          _processText(visionText.blocks);
          textRecognizer.close();
        }).catchError((error) {
          progressDialog.dismiss();
          PlatformErrorAlert(context: context, text: error).show();
        });
    }).catchError((error) {
      progressDialog.dismiss();
      PlatformErrorAlert(context: context, text: error).show();
    });
  }
```
The `print(visionText.text);` is empty when using an iOS device.

I expect it to return a VisionText with the recognized text like it does on an android device.

Flutter doctor output
```
Doctor summary:
[✓] Flutter (Channel master, v1.16.4-pre.22, on Mac OS X 10.14.6 18G103, locale en-GB)
    • Flutter version 1.16.4-pre.22 at /Users/lukechase/Apps/FlutterSDK
    • Framework revision e4a61dfdea (12 hours ago), 2020-03-29 21:01:02 -0400
    • Engine revision 361d5d5320
    • Dart version 2.8.0 (build 2.8.0-dev.17.0 1402e8e1a4)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/lukechase/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.1

[!] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.43.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (1 available)
    • iPhone XR • 00008020-001D6D883C45002E • ios • iOS 13.3.1

! Doctor found issues in 1 category.

! Doctor found issues in 1 category.
```

**Comment by zelliot** [comment]
On Android textRecognizer() and cloudTextRecognizer() both work perfectly.

On iOS neither textRecognizer() or cloudTextRecognizer() work.

I've done a bit of digging on this and I think it is something to do with the image. It seems to be rotated or flipped on iOS.

Testing with a photo of my Australian Passport taken within the app  on iOS, textRecognizer doesn't work at all but with cloudTextRecognizer it seems to work but returns everything back to front i.e. "AIJAЯТ2UA"

Flutter doctor output:
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E266, locale en-AU)
    • Flutter version 1.12.13+hotfix.9 at /Users/elliot/dev/flutter
    • Framework revision f139b11009 (9 days ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/elliot/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.43.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.0

[✓] Connected device (1 available)
    • ePhone • 47e705ac2711c7e3436bbe0fda4b9ab3beeafbef • ios • iOS 13.4

• No issues found!

**Comment by lurajon** [comment]
Hi!
I experience the same problem;

`void _initializeVision() async {
    final File imageFile = File(path);

    if (imageFile != null) {
      await _getImageSize(imageFile);
    }

    await GallerySaver.saveImage(path);

    final FirebaseVisionImage visionImage =
        FirebaseVisionImage.fromFile(imageFile);

    final TextRecognizer textRecognizer =
        FirebaseVision.instance.textRecognizer();

    print(visionImage);
    final VisionText visionText =
        await textRecognizer.processImage(visionImage);

    
    String text = "";
    print(visionText.text);
    for (TextBlock block in visionText.blocks) {
      print(block.text);
      for (TextLine line in block.lines) {
          print(line.text);
          text += line.text + '\n';
          for (TextElement element in line.elements) {
            print(element.text);
            _elements.add(element);
          }
        
      }
    }

    if (this.mounted) {
      setState(() {
        recognizedText = text;
      });
    }
  }`

pubspec.yml
`name: refurb_app
description: A refurbishment application to keep track of your paint choices etc

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.1
  sqflite: ^1.3.0
  path:
  path_provider: ^1.6.7
  flutter_redux: ^0.5.3 
  redux: ^3.0.0
  flutter_secure_storage: ^3.3.1+1
  flutter_localizations:
    sdk: flutter
  camera:
  flutter_i18n: ^0.14.0
  firebase_ml_vision:
  firebase_core: ^0.4.0
  flutter_camera_ml_vision: ^2.2.4
  image_picker:
  gallery_saver: ^2.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - logo.png
    - assets/images/
    - assets/i18n/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
`

When I open a camerastream however, and use fromBytes 

`FirebaseVisionImage.fromBytes(
        _concatenatePlanes(image.planes),
        _buildMetaData(image, _rotationIntToImageRotation(imageRotation)),
      ),`
Text are recognized on the stream.

Maybe the issue is somewhere in `FirebaseVisionImage.fromFile(imageFile);`?

**Comment by junnyea** [comment]
Facing the same problem here. Value for visionText is empty

>  VisionText visionText =
>     await textRecognizer.processImage(visionImage)

**Comment by hariprasadiit** [comment]
For me with original photo it doesn't work but, If I use `flutter_image_compress` and use the resulted compressed image, on device text recognition works well. I think it has something to do with rotation and EXIF information.

**Comment by TehRaab** [comment]
> For me with original photo it doesn't work but, If I use `flutter_image_compress` and use the resulted compressed image, on device text recognition works well. I think it has something to do with rotation and EXIF information.

I am also facing the same problem.  If i am to use `flutter_image_compress`, how do you determine how much rotation is needed?  I have noticed that the iPad Mini 2 only works in landscape.  I believe this is because the camera hardware is actually physically installed at +/-90 degree angle.

**Comment by hariprasadiit** [comment]
@TehRaab I think `flutter_image_compress`  automatically rotates the images based on EXIF information

**Comment by nickykln** [comment]
Hello, any progress on that issue ? 

Thanks a lot for your help,

**Comment by robwafle-scripd** [comment]
Hi!  We are experiencing this issue too.  And, we're starting to have some issues with Android as well.  Usually, might get an exception or two when starting the android app saying something along the lines of "please wait, still downloading ocr model from cloud", but now it won't download at all.  

Also, I am getting some warnings when building my app:
[!] FirebaseMLVisionTextModel has been deprecated in favor of MLKitTextRecognition

It looks like the MLKit is going through a bit of a transformation at the moment: https://firebase.google.com/docs/ml-kit/recognize-text

This appears to be the pod file name that will replace the current podfile:
pod 'GoogleMLKit/TextRecognition'

But, replacing with this line didn't help either.

**Comment by SimonDziak** [comment]
Android works perfectly for me. iOS text detection does not work. It detects weird texts and outputs wrong information if it pick up something.

**Comment by TehRaab** [comment]
> Android works perfectly for me. iOS text detection does not work. It detects weird texts and outputs wrong information if it pick up something.

I've had this issue for several months now and still haven't found a solution.  I've you find one, please let us know.  I raised a separate issue back in June - https://github.com/FirebaseExtended/flutterfire/issues/2770

**Comment by a-arshad** [comment]
Has there been any updates or other workarounds on this problem? 

The flutter_image_compress used to be fine as a workaround for a while, but now it seems like nothing is being detected on iOS at all. Has the cloudTextRecognizer been working recently as well, or is that still broken?

**Comment by SimonDziak** [comment]
Hello everyone. If you are having problems with Image Text Recognition for iOS I found the fix. After testing around multiple times, and you can try this to the text detection works but it just detects text incorrectly. Why is that? Well if you start fliping the phone around and image you will realize the issue becomes with the orientation of the screen. The fix then lays in fixing the orientation of the screen for iOS. 

ML Vision uses pictures (hundreds of them per second) to detect whatever you want. You have to orient each image to the correct space and then send it to the text detector. 

This is the plugin I used: flutter_exif_rotation:

**Comment by SimonDziak** [comment]
So you await to take a picture. You send the path of the image into the Flutter Exif Rotation and then send it to Firebase Vision. Hope this helps. 

It took me a few days of pulling my hair out to figure this out.

**Comment by a-arshad** [comment]
> Hello everyone. If you are having problems with Image Text Recognition for iOS I found the fix. After testing around multiple times, and you can try this to the text detection works but it just detects text incorrectly. Why is that? Well if you start fliping the phone around and image you will realize the issue becomes with the orientation of the screen. The fix then lays in fixing the orientation of the screen for iOS.
> 
> ML Vision uses pictures (hundreds of them per second) to detect whatever you want. You have to orient each image to the correct space and then send it to the text detector.
> 
> This is the plugin I used: flutter_exif_rotation:

I used to have this problem and so if I were to orient the device differently, the text recognizer would return text correctly. However, even with your fix or using flutter_compress_image, this is not the case. The FlutterVisionText returns no text read for any orientation.

`  if (Platform.isIOS) {
      file = await FlutterExifRotation.rotateImage(path: path);
    }

    FirebaseVisionImage image = FirebaseVisionImage.fromFile(file);`

**Comment by a-arshad** [comment]
> > Hello everyone. If you are having problems with Image Text Recognition for iOS I found the fix. After testing around multiple times, and you can try this to the text detection works but it just detects text incorrectly. Why is that? Well if you start fliping the phone around and image you will realize the issue becomes with the orientation of the screen. The fix then lays in fixing the orientation of the screen for iOS.
> > ML Vision uses pictures (hundreds of them per second) to detect whatever you want. You have to orient each image to the correct space and then send it to the text detector.
> > This is the plugin I used: flutter_exif_rotation:
> 
> I used to have this problem and so if I were to orient the device differently, the text recognizer would return text correctly. However, even with your fix or using flutter_compress_image, this is not the case. The FlutterVisionText returns no text read for any orientation.
> 
> ```
> if (Platform.isIOS) {
>       file = await FlutterExifRotation.rotateImage(path: path);
> }
> 
> FirebaseVisionImage image = FirebaseVisionImage.fromFile(file);
> ```

Just an update, this workaround still works. The error I was because I was using the new `GoogleMLKit/TextRecognition` pod. Instead if you just use the deprecated pods, `Firebase/MLVision` and `Firebase/MLVisionTextModel`, the textRecognizer works fine. Hopefully the newer pod gets patched up to work with Flutter soon.

**Comment by rohan20** [comment]
I can confirm that the [solution](https://github.com/FirebaseExtended/flutterfire/issues/1912#issuecomment-748411617) proposed by @SimonDziak and its [example](https://github.com/FirebaseExtended/flutterfire/issues/1912#issuecomment-748420669) from @a-arshad works with on-device text recognizer (didn't try the cloud one).

```dart
if (Platform.isIOS) {
      file = await FlutterExifRotation.rotateImage(path: path);
}

FirebaseVisionImage image = FirebaseVisionImage.fromFile(file);
```

```yaml
// pubspec.yaml
flutter_exif_rotation: ^0.3.2
```

Thank you both of you! ✅

**Comment by bmvkrd** [comment]
I can also confirm that the above solution proposed by @SimonDziak works (when FlutterExifRotation is used).
Thanks a lot, guys!

**Comment by eliaweiss** [comment]
@SimonDziak fix did not work for me ;(

**Comment by martinsmoises** [comment]
it didn't work for me either.

**Comment by martinsmoises** [comment]
Add 'Firebase/MLVisionTextModel' on Podfile  was work for me. 

`target 'Runner' do
  use_frameworks!
  use_modular_headers!
  pod 'Firebase/MLVisionTextModel'

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end`

**Comment by martinsmoises** [comment]
Add 'Firebase/MLVisionTextModel' on Podfile was work for me.
`
target 'Runner' do
  use_frameworks!
  use_modular_headers!
  pod 'Firebase/MLVisionTextModel'

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end
`

**Comment by martinsmoises** [comment]
Add 'Firebase/MLVisionTextModel' on Podfile  was work for me

`pod Firebase/MLVisionTextModel`

**Comment by Salakar** [comment]
Hey, :wave:, the `firebase_ml_vision` package is now discontinued since its APIs have been deprecated and removed from the Android & iOS Firebase SDKs.

I'd recommend switching to the alternatives now;

 - **for on-device vision APIs**; switch to Google's standalone ML Kit library via [google_ml_kit](https://pub.dev/packages/google_ml_kit)
 - **for cloud vision APIs**; the recommended approach now is to use Firebase
Authentication and Functions, which gives you a managed, serverless gateway to the Google Cloud Vision APIs. For an example Functions project see the [vision-annotate-images](https://github.com/firebase/functions-samples/tree/master/vision-annotate-images) sample project. You'd deploy this project for example and then call the cloud function from your app with your image data to get the annotation result.

Apologies for any inconvenience here and best of luck switching over the the new APIs. `firebase_ml_custom` is not affected by this deprecation.

Thanks
