### ISSUE TITLE
[firebase_ml_vision] FirebaseVisionImage.fromBytes does not work when loading a network image and crashes the app 

### ISSUE THREAD

**Issue by vivekcr** [FirebaseExtended/flutterfire#2021]
Im trying to use face_detector to detect faces on the network images that get pulled on page load

Im trying to construct the image using 
FirebaseVisionImage.fromBytes

I have the following configuration, note since its a network image i do not have the plane and metadata information and constructing it on assumption as follows

final FirebaseVisionImageMetadata metadata = FirebaseVisionImageMetadata(
        rawFormat: 0,
        size: Size(480, 360),
        planeData: [
          FirebaseVisionImagePlaneMetadata(
              bytesPerRow: 64, height: 480, width: 360)
        ],
        rotation: ImageRotation.rotation90);
    final FirebaseVisionImage visionImage =
        FirebaseVisionImage.fromBytes(responseToSend.bodyBytes, metadata);
    final FaceDetector faceDetector = FirebaseVision.instance.faceDetector();

The app crashes when i use the above constructed image to list faces,
final List<Face> faces = await faceDetector.processImage(visionImage);

**Comment by vivekcr** [comment]
Anyone facing the same issue. The example page works out of cameraImage what incase we use a network image we dont have all the required metadata information and it crashes thew app completely without anything in the logs !!!

**Comment by Salakar** [comment]
Hey, :wave:, the `firebase_ml_vision` package is now discontinued since its APIs have been deprecated and removed from the Android & iOS Firebase SDKs.

I'd recommend switching to the alternatives now;

 - **for on-device vision APIs**; switch to Google's standalone ML Kit library via [google_ml_kit](https://pub.dev/packages/google_ml_kit)
 - **for cloud vision APIs**; the recommended approach now is to use Firebase
Authentication and Functions, which gives you a managed, serverless gateway to the Google Cloud Vision APIs. For an example Functions project see the [vision-annotate-images](https://github.com/firebase/functions-samples/tree/master/vision-annotate-images) sample project. You'd deploy this project for example and then call the cloud function from your app with your image data to get the annotation result.

Apologies for any inconvenience here and best of luck switching over the the new APIs. `firebase_ml_custom` is not affected by this deprecation.

Thanks
