### ISSUE TITLE
[cloud_firestore] Incompatibiltiy with webrtc

### ISSUE THREAD

**Issue by cadaniel** [FirebaseExtended/flutterfire#2052]
**Describe the bug**
When I build with the package [flutter_webrtc](https://pub.dev/packages/flutter_webrtc) I get the following error 

In file included from /Users/archer/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.2.6/ios/Classes/FlutterRTCVideoRenderer.m:9:
    In file included from /Users/archer/Work/ldrc/ios/Pods/libyuv-iOS/headers/libyuv.h:15:
    /Users/archer/Work/ldrc/ios/Pods/abseil/absl/types/compare.h:33:10: fatal error: 'cstddef' file not found
    #include <cstddef>

**To Reproduce**
Import both flutter_webrtc: ^0.2.6 and cloud_firestore: ^0.13.2
Compile for iOS debug

**Expected behavior**
Successful compile

**Additional context**
brew doctor shows no odd header files, and flutter doctor has no warnings

After some more searching it seems to be related to 
https://github.com/firebase/firebase-ios-sdk/issues/4537

**Comment by iapicca** [comment]
Hi @cadaniel 
I'm not sure that the error you are reporting depends from flutterfire plugin,
but rather from the aforementioned [flutter_webrtc](https://pub.dev/packages/flutter_webrtc) plugin
you may want to open an issue in the dedicated [github](https://github.com/cloudwebrtc/flutter-webrtc/issues);
nevertheless if you believe the issue is cause by flutterfire 
could you please provide your `flutter doctor -v` , 
your `flutter run --verbose` 
and your `pubspec.yaml` 
or if possible a reproducible minimal code sample.
Thank you

**Comment by Thomas-Ahn** [comment]
please try these:  1) Podfile
   platform :ios, '11.0'
2) pubspce.yaml
dependencies:
   flutter_webrtc: ^0.2.7
3) codesign "login" key chain password pop-up menu, enter your login password with "Always Allow"

**Comment by kirstywilliams** [comment]
Hey @cadaniel did you manage to track down if this was an issue with [flutter_webrtc](https://pub.dev/packages/flutter_webrtc) and not firestore? Or whether the solution provided by @Thomas-Ahn above https://github.com/FirebaseExtended/flutterfire/issues/2052#issuecomment-602396348 fixed your issue? - thanks!

**Comment by cadaniel** [comment]
Sorry for the slow response. 

The problem is now fixed! Thanks so much!
