### ISSUE TITLE
[cloud_firestore] Add listCollections to DocumentReference

### ISSUE THREAD

**Issue by willcalderbank** [FirebaseExtended/flutterfire#2058]
Currently it's impossible to see the collections in a document. 

The nodeJS api has this feature: https://googleapis.dev/nodejs/firestore/latest/DocumentReference.html#listCollections

Just wondering if this is on the roadmap at all. I would be really handy to walk the collections/document tree.

Thanks

**Comment by IchordeDionysos** [comment]
This is a Admin SDK only feature:
https://firebase.google.com/docs/reference/swift/firebasefirestore/api/reference/Classes/DocumentReference
https://firebase.google.com/docs/reference/android/com/google/firebase/firestore/DocumentReference
https://firebase.google.com/docs/reference/js/firebase.firestore.DocumentReference

I guess this is probably because of permission problems.
There is currently no way in the Firestore Security Rules to define whether you are allowed to list the collections.

Also, I would open an issue at the github.com/firebase/firebase-ios-sdk repos or write directly to the Firebase support with a feature request 🤔
