### ISSUE TITLE
[firebase_messaging] Bug with onResume and onLaunch

### ISSUE THREAD

**Issue by Ionys320** [FirebaseExtended/flutterfire#207]
Hello,
When I click on a notification, it launch onResume, but when the onResume void open a new page, onResume is looped. It's the same thing with onLaunch…

```
Future<void> notificationClick(Map<dynamic, dynamic> message, context) async { 
	print('notifClick');
	Navigator.pushNamed(context, 'test'); 
}
```

**Comment by Ehesp** [comment]
Hi @Ionys320 please can you try with the latest version of Flutter & the messaging plugin. If this issue still persists, please can you let me know and also add details such as plugin versions, and the `flutter doctor` output. Thanks.

Closing for now due to the age and lack of info to help investigate. Thanks.
