### ISSUE TITLE
[Firebase Performance] Misleading instructions

### ISSUE THREAD

**Issue by pulstar** [FirebaseExtended/flutterfire#2170]
At https://pub.dev/packages/firebase_performance#-readme-tab-, in the Usage section, it have a link to a Codelab that appear to have nothing to do with Firebase performance (https://codelabs.developers.google.com/codelabs/flutter-firebase/#4). Could anybody check this?

From the Firebase Console, I found some instructions at: https://firebase.google.com/docs/perf-mon/get-started-android

But it is not clear to me if do I need to make these changes in build.gradle, or just install the firebase_performance package from pub.dev in my pubspec.yaml

What is the right thing to do?

Sorry if this is not a bug. As a suggestion, it could be good to have a Report an Error link at pub.dev

**Comment by Jan-pp** [comment]
Same issue here, the provided link is wrong. Please provide specific instructions.

What exactly do I (not) need to do to get it working in Android? I added the stuff in the build.gradle files and it seems to work now. However it might not be necessary and just add extra bagage. I've already installed Analytics, Crashlytics and FCM.

For iOS I didn't have to do anything special besides installing the Flutter package.

It's hard to tell if the performance plugin works at all since it takes hours for anything to show up in the dashboard, if at all. The DebugView is super flaky as well...

**Comment by Salakar** [comment]
This codelab has since been removed, please follow the docs located on the package itself now and on http://firebase.flutter.dev/ - thanks.
