### ISSUE TITLE
[firebase_messaging] If I run provided example app it creates 2 icons of the app in Android

### ISSUE THREAD

**Issue by bahadurvaibhav** [FirebaseExtended/flutterfire#2237]
**Describe the bug**
I am trying to run the example app (for Firebase Messaging) given in below repository:
https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_messaging/example

When I build the app, I get 2 icons
![InkedScreenshot_1585230827_LI](https://user-images.githubusercontent.com/13390257/77654895-ab207f80-6f97-11ea-9da4-26d97fdfba63.jpg)

**To Reproduce**
Run main.dart from the above repository.

**Expected behavior**
Should one show 1 icon

**Comment by TahaTesser** [comment]
Definitely an issue

![Screenshot_1585302650](https://user-images.githubusercontent.com/48603081/77743826-a82c9a00-703e-11ea-96e0-e1df502aeea2.png)

**Comment by vkammerer** [comment]
This is due to the fact that two `LAUNCHER` attributes are declared in the manifest:
- https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_messaging/example/android/app/src/main/AndroidManifest.xml#L13-L16
- https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_messaging/example/android/app/src/main/AndroidManifest.xml#L28-L31

Removing one should solve the issue

**Comment by Salakar** [comment]
Closing in favour of trying the latest messaging version which has since this issue was created been heavily reworked to improve it along with detailed documentation: https://firebase.flutter.dev/docs/messaging/overview

If you still have a problem please raise a new GitHub issue with up to date information and code snippets if possible. Thanks.
