### ISSUE TITLE
[firebase_messaging] Android App not registering with firebase

### ISSUE THREAD

**Issue by Genora51** [FirebaseExtended/flutterfire#2241]
**Describe the bug**
I am not receiving push notifications sent with Firebase Cloud Messaging. When I create a message from the firebase console the `Target` step reports: `0% of potential users are eligible for this campaign:0`, indicating that the FCM token is not registered with the server. However, if I directly input the token from `getToken()` into the `Send test message` dialog the message sends successfully. So I imagine the issue involves the plugin not registering the token.

**To Reproduce**
1. Followed the installation and _Android Integration_ steps from the README (latest version)
2. I am also using `flutter_local_notifications` but I was under the impression that issues with this package were fixed, so I don't think this is the cause of the problem.

**Comment by AbScott1985** [comment]
hi did you manage to fix this I have the same problem

**Comment by Genora51** [comment]
I left it a few days, and when I came back to it it had started working properly. I have no idea what the issue was, but it might just be some weirdness with the way firebase handles new devices.

**Comment by Salakar** [comment]
Closing in favour of trying the latest messaging version which has since this issue was created been heavily reworked to improve it along with detailed documentation: https://firebase.flutter.dev/docs/messaging/overview

If you still have a problem please raise a new GitHub issue with up to date information and code snippets if possible. Thanks.
