### ISSUE TITLE
[firebase_ml_vision] PDF417 reader is not working for DL

### ISSUE THREAD

**Issue by aantelov87** [FirebaseExtended/flutterfire#2242]
Trying to read a PDF417 barcode for a US DL using the new barcode library instead of the one from Google Mobile Vision but your lib is not properly reading and camera is unusable for Samsung S8 when resolution is set to ResolutionPreset.high.

Any ideas how can we use this feature from the new API? 

I am testing with the example but I am not getting any good results.

Thank you

**Comment by TahaTesser** [comment]
Hi @aantelov87 
can you please provide your `flutter doctor -v` and `flutter run --verbose`?
Are you using official firebase_ml_vision example? 
Thank you

**Comment by aantelov87** [comment]
Hi @TahaTesser 

Yes, I am using the official firebase_ml_vision example but I just changed the following line 
https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_ml_vision/example/lib/material_barcode_scanner.dart#L156
with 
`final ResolutionPreset preset = ResolutionPreset.high;`

because with the resolution used in the official example, the detector is not able to detect PDF417 barcode for DL.  

In the attachment flutter run --verbose when the resolution is set to high for PDF417 detection.

Please, let me know if you need anything else. 

`flutter doctor -v                
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76, locale en-US)
    • Flutter version 1.12.13+hotfix.8 at /Users/aantelov/GPN/flutter
    • Framework revision 0b8abb4724 (6 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/aantelov/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/aantelov/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    • CocoaPods version 1.9.0

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (1 available)
    • SM G950F • ce06182664a6821703 • android-arm64 • Android 9 (API 28)
`

[output-modified.txt](https://github.com/FirebaseExtended/flutterfire/files/4393064/output-modified.txt)

**Comment by aantelov87** [comment]
Hello @TahaTesser 

Have I added the issue in the correct project?  because it looks like nobody is looking into this since 6 days ago.

**Comment by Salakar** [comment]
Hey, :wave:, the `firebase_ml_vision` package is now discontinued since its APIs have been deprecated and removed from the Android & iOS Firebase SDKs.

I'd recommend switching to the alternatives now;

 - **for on-device vision APIs**; switch to Google's standalone ML Kit library via [google_ml_kit](https://pub.dev/packages/google_ml_kit)
 - **for cloud vision APIs**; the recommended approach now is to use Firebase
Authentication and Functions, which gives you a managed, serverless gateway to the Google Cloud Vision APIs. For an example Functions project see the [vision-annotate-images](https://github.com/firebase/functions-samples/tree/master/vision-annotate-images) sample project. You'd deploy this project for example and then call the cloud function from your app with your image data to get the annotation result.

Apologies for any inconvenience here and best of luck switching over the the new APIs. `firebase_ml_custom` is not affected by this deprecation.

Thanks
