### ISSUE TITLE
[firebase_messaging] Assert on iOS calling requestNotificationPermissions

### ISSUE THREAD

**Issue by johannesvuorinen** [FirebaseExtended/flutterfire#2271]
Using latest Flutter engine (ios_debug_unopt) from GitHub asserts on iOS when calling requestNotificationPermissions in Dart:
FLTFirebaseMessagingPlugin.m Row 115: `[self->_channel invokeMethod:@"onIosSettingsRegistered" arguments:settingsDictionary];`
asserts on `FML_DCHECK_CREATION_THREAD_IS_CURRENT(checker_.checker);`

Workaround fix by changing the call to:
`dispatch_async(dispatch_get_main_queue(), ^{[self->_channel invokeMethod:@"onIosSettingsRegistered" arguments:settingsDictionary];});`

**Comment by Salakar** [comment]
Closing in favour of trying the latest messaging version which has since this issue was created been heavily reworked to improve it along with detailed documentation: https://firebase.flutter.dev/docs/messaging/overview

If you still have a problem please raise a new GitHub issue with up to date information and code snippets if possible. Thanks.
