### ISSUE TITLE
[firebase_auth] onIdTokenChanged stream is missing

### ISSUE THREAD

**Issue by derfurth** [FirebaseExtended/flutterfire#2319]
FirebaseAuth only provides onAuthStateChanged, a stream emitting each time the user signIn or signOut.

It should also provides onIdTokenChanged which includes sign-in, sign-out, and token refresh events as a way to get token changes.
https://firebase.google.com/docs/reference/js/firebase.auth.Auth#on-idtoken-changed

Right now sending a token to a server requires having to call getIdToken to be sure it's still valid, I'd like a stream of tokens instead because streams rocks!

**Comment by lukepighetti** [comment]
This feature is sorely missed. Is there a blocker to implementing it?

**Comment by lukepighetti** [comment]
Here's a shim if anyone wants to use it


```dart

  /// Handle when firebase user is signed in or signed out
  void _handleAuthStateChanged(FirebaseUser e) async {
    if (e == null) {
      _authentication = null;
    } else {
      /// Get token
      final firebaseToken = await e.getIdToken(refresh: true);

      /// Setup token refresh
      firebaseToken.expirationTime.asFuture(() async {
        var user = await FirebaseAuth.instance.currentUser();
        _handleAuthStateChanged(user);
      });
```


```dart
extension DateTimeFutureX on DateTime {
  Future<T> asFuture<T>([FutureOr<T> Function() computation]) async {
    final difference = this.difference(DateTime.now());
    return Future.delayed(difference, computation);
  }
}

```

**Comment by vytautas-pranskunas-** [comment]
Hello, any progress on this?

**Comment by vytautas-pranskunas-** [comment]
@lukepighetti 
Your code snippet is good however timer stops after you lock phone screen and resumes (or starts from scratch) after you unlock screen - meaning that if user turns off the screen after 30 minutes and resumes it after 1 hour token will not refreshed because timer was paused. Any ideas how to solve this?

**Comment by lukepighetti** [comment]
I do not have a good solution. It would get more complex than what I have laid out above for sure. I would suggest that further improvement on my 'shim' would be to expose this feature from the native code to the flutter code. Wish I had a better answer for you. Maybe there's a Scheduler tool or package we can use instead of a timed future?

**Comment by vytautas-pranskunas-** [comment]
i actually have: in addition to your code i have added this code to my main.dart
```
@override
Future<void> didChangeAppLifecycleState(AppLifecycleState state) async {
     super.didChangeAppLifecycleState(state);
     if (state == AppLifecycleState.resumed) {
         await _authService.refreshToken();
     }
 }
```

**Comment by shashkiranr** [comment]
Need this !!

**Comment by Ehesp** [comment]
Now implemented: https://pub.dev/documentation/firebase_auth/latest/firebase_auth/FirebaseAuth/idTokenChanges.html
