### ISSUE TITLE
[cloud_firestore]  Firebase/CoreOnly dependency instead of Firebase/Core for ios IDFA

### ISSUE THREAD

**Issue by heeyounglee** [FirebaseExtended/flutterfire#2326]
**Is your feature request related to a problem? Please describe.**
My iOS kids app is rejected for using IDFA even if I remove firebase_analytics,
I believe that it's from the pod dependency: GoogleAppMeasurement -> FirebaseAnalytics -> Firebase/Core
https://github.com/FirebaseExtended/flutterfire/blob/master/packages/cloud_firestore/cloud_firestore/ios/cloud_firestore.podspec#L23

**Describe the solution you'd like**
Change from Firebase/Core to Firebase/CoreOnly which doesn't depend on Firebase/Analytics

**Comment by heeyounglee** [comment]
related: https://github.com/firebase/firebase-ios-sdk/issues/5153

**Comment by geekydiamond** [comment]
We were also rejected. We also use the firebase_auth plugin which also seems to pull in Firebase/Core. Should I open another ticket for that?

**Comment by heeyounglee** [comment]
Is there any plan for fix this? Should I label it as a bug instead of enhancement?

**Comment by Ehesp** [comment]
Core is required on some modules (at the moment) due to the hard dependency they have on each other. Have you seen these docs?

https://firebase.google.com/docs/analytics/configure-data-collection?platform=ios#disable_idfa_collection

Need to figure out how exactly this can be done though, any help appreciated..

**Comment by divinemery** [comment]
We are facing the same issue. Our ios app is getting rejected because of advertisingIdentifier is used. Our app is in Kids Category so we can't use the advertisingIdentifier.

<img width="834" alt="Screenshot 2020-05-29 at 5 16 15 PM" src="https://user-images.githubusercontent.com/3801000/83263739-1c66f380-a1d0-11ea-8155-11104566157c.png">

**Comment by Salakar** [comment]
Hey this has been fixed as part of #2582 / #2913  - pending release.
