### ISSUE TITLE
Collection Group query isn't returning any data

### ISSUE THREAD

**Issue by SirusCodes** [FirebaseExtended/flutterfire#2332]
I have set composite index and rules in console but still I'm unable to get any data. Below is snippet of my service for query
```
_db
        .collectionGroup("entries")
        .where("instructors", arrayContains: _id.getUser.mailID)
        .where("branch", isEqualTo: _id.getBranch.name)
        .where("date", isEqualTo: date)
        .snapshots(); 
```

**Comment by TahaTesser** [comment]
Hi @SirusCodes 
This platform is not meant for assistance on personal code. Please see https://flutter.dev/community for resources and asking questions like this, you may also get some help if you post it on Stack Overflow. Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it 
Thank you

**Comment by kingdg25** [comment]
Same issue here, not streaming collection when using arrayContains. Hello @TahaTesser kindly try it yourself so that you consider this an issue.

pubspec.yaml:
  cupertino_icons: ^0.1.2
  animated_text_kit: ^1.3.0
  firebase_core: ^0.4.1+5
  firebase_auth: ^0.15.4
  cloud_firestore: ^0.13.4+1
  cached_network_image: ^2.0.0
  fluttertoast: ^3.1.3
  shared_preferences: ^0.5.6+1
  google_sign_in: ^4.1.1
  firebase_messaging: ^5.1.0
  firebase_analytics:

flutter version: 1.12.13+hotfix.7

**Comment by theniceboy** [comment]
Same issue here. It seems like `collectionGroup` queries will not receive results with `where` clauses.

**Comment by SirusCodes** [comment]
What issue I was facing that i couldn't get data using contains clause rest other clauses worked fine and I guess that contains clause searches the clause in the incoming data so that gave me a problem. I was my mistake! 

I'm using 0.13.4+2 version. 

I don't know why you all are facing this issue but I would be happy to help you.

**Comment by TahaTesser** [comment]
Hi @SirusCodes 
given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
Thank you
