### ISSUE TITLE
firebase_auth on macOS throws MissingPluginException

### ISSUE THREAD

**Issue by threos** [FirebaseExtended/flutterfire#2393]
When trying to verify a phone number using firebase_auth package iOS and Android works perfect but on macOS, firebase_auth throws the following: `Unhandled Exception: MissingPluginException(No implementation found for method verifyPhoneNumber on channel plugins.flutter.io/firebase_auth)`.

**Steps to reproduce**
1. Create a Flutter project with desktop (macOS) support.
2. Call FirebaseAuth.instance.verifyPhoneNumber on somewhere in the app
3. Run the app on macOS and check the console.

**Expected behavior**
The app should send the OTP to the number provided as it does on mobile.

**Comment by joaovirgili** [comment]
Same here.

**Comment by shinriyo** [comment]
E/flutter (15262): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: MissingPluginException(No implementation found for method RemoteConfig#instance on channel plugins.flutter.io/firebase_remote_config)
E/flutter (15262): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)

**Comment by Salakar** [comment]
This is fixed in the latest auth release. @shinriyo for Remote config lets track macOS support on #1653 instead.

Please could you try the new version and see if this is still an issue for you? If it is then please submit a new up to date GitHub issue.

For help migrating to the new plugins please see the new migration guide: https://firebase.flutter.dev/docs/migration
