### ISSUE TITLE
Firebase ML Kit TextRecognizer change the size scan area

### ISSUE THREAD

**Issue by endritgojani** [FirebaseExtended/flutterfire#2421]
I want the camera to detect text only within this rectangle 
![as shown in the picture)](https://user-images.githubusercontent.com/33748159/80090333-a089e380-855f-11ea-90b1-d2d7834be92e.jpg)

**Comment by TahaTesser** [comment]
Hi @endritgojani 
This platform is not meant for assistance on personal code.
Please see https://flutter.dev/community for resources and asking questions like this, you may also get some help if you post it on Stack Overflow. 
if you disagree please write in the comments and I will reopen it 
Thank you

**Comment by endritgojani** [comment]
No I disagree because this question has to do with Firebase ML Kit, not with something in flutter

**Comment by Salakar** [comment]
Hey, :wave:, the `firebase_ml_vision` package is now discontinued since its APIs have been deprecated and removed from the Android & iOS Firebase SDKs.

I'd recommend switching to the alternatives now;

 - **for on-device vision APIs**; switch to Google's standalone ML Kit library via [google_ml_kit](https://pub.dev/packages/google_ml_kit)
 - **for cloud vision APIs**; the recommended approach now is to use Firebase
Authentication and Functions, which gives you a managed, serverless gateway to the Google Cloud Vision APIs. For an example Functions project see the [vision-annotate-images](https://github.com/firebase/functions-samples/tree/master/vision-annotate-images) sample project. You'd deploy this project for example and then call the cloud function from your app with your image data to get the annotation result.

Apologies for any inconvenience here and best of luck switching over the the new APIs. `firebase_ml_custom` is not affected by this deprecation.

Thanks
