### ISSUE TITLE
[firebase_auth] example should not use setState in async calls

### ISSUE THREAD

**Issue by fourman-alex** [FirebaseExtended/flutterfire#256]
The example might mislead developers that are new to flutter because it uses `setState` and `Scaffold.of` in async calls where this can throw an exception.  
While the current code does demonstrate the API usage, it having bad practice examples can cause new developers to adopt those incorrect practices.

### Examples of such cases:
`signin_page.dart`
```
onPressed: () async {
                final FirebaseUser user = await _auth.currentUser();
                if (user == null) {
                  Scaffold.of(context).showSnackBar(SnackBar(
                    content: const Text('No one has signed in.'),
                  ));
                  return;
                }
                _signOut();
                final String uid = user.uid;
                Scaffold.of(context).showSnackBar(SnackBar(
                  content: Text(uid + ' has successfully signed out.'),
                ));
              }
```
```
void _signInAnonymously() async {
    final FirebaseUser user = await _auth.signInAnonymously();
    assert(user != null);
    assert(user.isAnonymous);
    assert(!user.isEmailVerified);
    assert(await user.getIdToken() != null);
    if (Platform.isIOS) {
      // Anonymous auth doesn't show up as a provider on iOS
      assert(user.providerData.isEmpty);
    } else if (Platform.isAndroid) {
      // Anonymous auth does show up as a provider on Android
      assert(user.providerData.length == 1);
      assert(user.providerData[0].providerId == 'firebase');
      assert(user.providerData[0].uid != null);
      assert(user.providerData[0].displayName == null);
      assert(user.providerData[0].photoUrl == null);
      assert(user.providerData[0].email == null);
    }

    final FirebaseUser currentUser = await _auth.currentUser();
    assert(user.uid == currentUser.uid);
    setState(() {
      if (user != null) {
        _success = true;
        _userID = user.uid;
      } else {
        _success = false;
      }
    });
  }
```

**Comment by Salakar** [comment]
Hey 👋 

Our rework of the `firebase_auth` plugin as part of the [FlutterFire roadmap](https://github.com/FirebaseExtended/flutterfire/issues/2582) was published over a week ago with a ton of fixes and new features. 

This also included some updates to the example app. Would you mind reviewing and seeing if this is still an issue - I noticed you sent a PR last year but it was very stale and the repo has changed drastically since then so I've closed it as it'd probably be easier to review updated example and submit a new PR suggesting any changes. Firestore & Core examples could also do with a review if you feel like it 🤓 PRs would be very welcome. 

For help migrating to the new plugins please see the new migration guide: https://firebase.flutter.dev/docs/migration

**Comment by fourman-alex** [comment]
@Salakar  I'll definetly try to get to the new examples, I remember the pains of just starting with Flutter. But if anyone beats me to it the better.
