### ISSUE TITLE
firebase_ml_vision 0.9.3+8 not able to detect barcode hi i tried the same for me its not working on my device one plus 8T

### ISSUE THREAD

**Issue by kw2019ltd** [FirebaseExtended/flutterfire#2623]
hi i tried the same for me its not working on my device one plus 8T

attached screen shot where it was not able to detect QR code
![Screenshot_20200524-152234](https://user-images.githubusercontent.com/47334522/82757070-c583a780-9de6-11ea-8c0f-9135aa84bae5.jpg)

record where it was not able to detect qrcode
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/47334522/82757118-04196200-9de7-11ea-9c10-e2e41ecdda82.gif)

also i added print to check if barcode detect it was not 

![image](https://user-images.githubusercontent.com/47334522/82757184-6c684380-9de7-11ea-9b68-9b7a18a6b4bb.png)

I/native  ( 9172): barcode_detector_client.cc:238 Not using NNAPI
**I/flutter ( 9172): 0**

pls check the issue.

_Originally posted by @kw2019ltd in https://github.com/FirebaseExtended/flutterfire/issues/2506#issuecomment-633242872_

**Comment by Salakar** [comment]
Hey, :wave:, the `firebase_ml_vision` package is now discontinued since its APIs have been deprecated and removed from the Android & iOS Firebase SDKs.

I'd recommend switching to the alternatives now;

 - **for on-device vision APIs**; switch to Google's standalone ML Kit library via [google_ml_kit](https://pub.dev/packages/google_ml_kit)
 - **for cloud vision APIs**; the recommended approach now is to use Firebase
Authentication and Functions, which gives you a managed, serverless gateway to the Google Cloud Vision APIs. For an example Functions project see the [vision-annotate-images](https://github.com/firebase/functions-samples/tree/master/vision-annotate-images) sample project. You'd deploy this project for example and then call the cloud function from your app with your image data to get the annotation result.

Apologies for any inconvenience here and best of luck switching over the the new APIs. `firebase_ml_custom` is not affected by this deprecation.

Thanks
