### ISSUE TITLE
Allow to initialize all Firebase plugins without a google.json file

### ISSUE THREAD

**Issue by escamoteur** [FirebaseExtended/flutterfire#265]
Hi,

maybe this is already solved, but when I last looked at it not all Firebase plugins could be initialized completely from code without the need of a google.json file.

The problem is as long as it only works with a google.json file you can't access Firebase from Dart test which would be extremely helpful for Integrationtests.

So my wish would be that all plugins can be optionally initialized completely from code with API key etc.
Thanks for your great work
Thomas

**Comment by Ehesp** [comment]
Hello,

Unfortunately the native SDKs on a number of plugins (e.g. messaging) are required to support the Android/iOS config files. Some plugins don't allow secondary apps and require the "default" app to be created via these files.

You can create a secondary app for some modules: https://pub.dev/documentation/firebase_core/latest/firebase_core/FirebaseApp/configure.html

Since this is a general limitation of the underlying Android & iOS SDKs, I'll close this as it's not possible.
