### ISSUE TITLE
[cloud_firestore] Use cloud_firestore in a Dart command line program

### ISSUE THREAD

**Issue by milesbenettdyson** [FirebaseExtended/flutterfire#267]
**Is your feature request related to a problem? Please describe.**
For development I need to add many entities to a Cloud Firestore instance. Currently I go to the Cloud Firestore console and add them manually. That's error-prone and tedious.

**Describe the solution you'd like**
I'd like to be able to write helper scripts in Dart that populate a Cloud Firestore instance with example entities. The Dart code should be able to import the same code that the Flutter app uses to communicate with Cloud Firestore to avoid code duplication. Currently that's not possible, since `cloud_firestore` depends on `dart:ui`:

```
$ dart add_tournaments.dart 
../../../../progs/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.12.9+4/lib/cloud_firestore.dart:10:8: Error: Not found: 'dart:ui'
import 'dart:ui' show hashValues, hashList;
...
```

**Comment by rubenvereecken** [comment]
@milesbenettdyson have you figured out a way around this?

**Comment by milesbenettdyson** [comment]
No, unfortunately not.

**Comment by rubenvereecken** [comment]
Since my comment I've had quite a bit of experience with Firebase. Firebase seems to like having client and server ("admin") libraries separately. For example, I'm using the Node.js admin library which contains a few functions that the client library doesn't have. I think it's for similar reasons that a single Dart library for both admin and client functionality won't be considered. So then it becomes about asking for an admin Dart library... and since Dart is a language heavily engineered for mobile, I think that's unlikely to happen.

**Comment by Salakar** [comment]
This isn't on the roadmap unfortunately as we rely on the original Firebase SDKs such as the Web SDK to provide functionality. Having said that there are projects like [`firebase_admin`](https://pub.dev/packages/firebase_admin) that aim to provide Admin SDK functionality in Dart which you could use in your CLI.
