### ISSUE TITLE
[FirebaseAuth] Expose startActivityForSignInWithProvider

### ISSUE THREAD

**Issue by sageata** [FirebaseExtended/flutterfire#2691]
**Is your feature request related to a problem? Please describe.**

I am trying to use Sign in With Apple in a Flutter project, however I find it very difficult to implement this on Android because the `startActivityForSignInWithProvider` is not exposed.

**Describe the solution you'd like**
Expose `startActivityForSignInWithProvider` on the FirebaseAuth.instance

**Additional context**

**Comment by Salakar** [comment]
We plan to support the custom OAuth flow (webview / browser signin) in a future release which uses this method underneath on Android for example. No ETA yet though sorry, will probably be after our rework of Functions, Storage, Crashlytics & Messaging.

**Comment by ZetiMente** [comment]
Why is this such a low priority? Is this because its Apple? Here we are in Feb 2021 and you still can't use Firebase Auth for Android using Sign in with Apple. I didn't even plan to use Sign in with Apple, but Apple rejects your App if you use other 3rd party logins. So I have no choice but to use it. But now I do all this work for iOS, and can't even enjoy all the fruits of that labor to use the Flutter cross platform power to have Android because of this issue.

**Comment by KevinKozj** [comment]
+1 on @ZetiMente

**Comment by gabrc52** [comment]
Apple sign in brings some benefits like not having to give the app your email address, but still receive emails. I'd like to try it out on my Android device, mainly for testing, since I can't easily test on Apple devices

**Comment by vbuberen** [comment]
Sign in with Apple is also very useful for seamless experience for users with devices on both platforms. 

This issue should get a higher priority for sure.

**Comment by Spartan056** [comment]
Any news on this?

**Comment by gabrc52** [comment]
Definitely, if you use an iPad and an Android phone, you could use Apple Sign in on FlutterFire apps in both.

**Comment by loicgeek** [comment]
+1
