### ISSUE TITLE
[firebase_ml_vision] Run imageLabeler in different isolate

### ISSUE THREAD

**Issue by JSBmanD** [FirebaseExtended/flutterfire#2707]
**Describe the bug**
I was trying to run image labeler in isolate but I'm getting error:
`ServicesBinding.defaultBinaryMessenger was accessed before the 'binding was initialized.`

**To Reproduce**
1. Make an isolate
2. Run in it image labeler
3. 'ServicesBinding.defaultBinaryMessenger was accessed before the 'binding was initialized.' error will be thrown.

**Expected behavior**
Image will be labeled and I can get a list of labels.

**Flutter doctor**
Run `flutter doctor` and paste the output below:

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.17.2, on Microsoft Windows [Version 10.0.18363.752], locale ru-RU)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 4.0)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by TahaTesser** [comment]
Hi @JSBmanD 
Can you please try possible [solution](https://github.com/flutter/flutter/issues/40253#issuecomment-530397525)?
Thank you

**Comment by JSBmanD** [comment]
Hi @TahaTesser, as isolate doesn't have main.dart it's not helping. Running that line before the isolate and even before runApp() doesn't help.

**Comment by TahaTesser** [comment]
Hi @JSBmanD 
Can you please provide your `flutter run --verbose` and a minimal complete reproducible code sample.
Thank you

**Comment by Salakar** [comment]
Hey, :wave:, the `firebase_ml_vision` package is now discontinued since its APIs have been deprecated and removed from the Android & iOS Firebase SDKs.

I'd recommend switching to the alternatives now;

 - **for on-device vision APIs**; switch to Google's standalone ML Kit library via [google_ml_kit](https://pub.dev/packages/google_ml_kit)
 - **for cloud vision APIs**; the recommended approach now is to use Firebase
Authentication and Functions, which gives you a managed, serverless gateway to the Google Cloud Vision APIs. For an example Functions project see the [vision-annotate-images](https://github.com/firebase/functions-samples/tree/master/vision-annotate-images) sample project. You'd deploy this project for example and then call the cloud function from your app with your image data to get the annotation result.

Apologies for any inconvenience here and best of luck switching over the the new APIs. `firebase_ml_custom` is not affected by this deprecation.

Thanks
