### ISSUE TITLE
Firebase background handler

### ISSUE THREAD

**Issue by kratipandey57** [FirebaseExtended/flutterfire#2745]
how to open app if onbackgroundhandler is called

**Comment by iapicca** [comment]
Hi @kratipandey57 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments, possibly providing a minimal reproducible code sample that does not use flutter fire or other 3rd party plugins, and I will reopen it.
Thank you
