### ISSUE TITLE
[CloudStore] <data pulled from document is assigned to variable in delay>

### ISSUE THREAD

**Issue by shan-vm** [FirebaseExtended/flutterfire#2748]
**Describe the bug**
Line number 19 is executed first and prints null.
![image](https://user-images.githubusercontent.com/6676205/84434610-0a0da080-ac39-11ea-843e-624bb41d755d.png)

**To Reproduce**
below screenshot provides all info
![image](https://user-images.githubusercontent.com/6676205/84434610-0a0da080-ac39-11ea-843e-624bb41d755d.png)

**Expected behavior**
Line number 19 should run last.

**Comment by iapicca** [comment]
Hi @shan-vm 
this behaviour is expected because 
when the firstly printed "cars" is printed cars is still null
because of the async function
and as expected the second print at the end of the async function is called when completed

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments, possibly providing a minimal reproducible code sample that does not use flutter fire or other 3rd party plugins, and I will reopen it.
Thank you

**Comment by shan-vm** [comment]
how the code should be. Collectionrefreance followed by "then" to handle the async behaviour.
is there any proper documentation?

**Comment by iapicca** [comment]
Hi @shan-vm 
here is the [documentation](https://dart.dev/codelabs/async-await)
Please see https://flutter.dev/community for resources and asking questions like this,
you may also get some help if you post it on Stack Overflow and if you need help with your code, please see https://www.reddit.com/r/flutterhelp/
Thank you
