### ISSUE TITLE
How to get FNC1 codes in barcode scanning?

### ISSUE THREAD

**Issue by solartes** [FirebaseExtended/flutterfire#2799]
I want to decode the FNC1 codes in GS1-128 barcode in flutter using ML Vision.

We know the GS1-128 structure is the following:

![image](https://user-images.githubusercontent.com/22583659/85177993-f8348a80-b242-11ea-9f35-88e64d89f707.png) 

How can I get the FNC1 codes?

**Comment by haraldkofler** [comment]
The FNC symbol is ASCI 29. To replace all occurrences of an FNC inside the barcode, use this:
code.rawValue.replaceAll(String.fromCharCode(29), "<FNC>");

**Comment by solartes** [comment]
Thanks!!!!

**Comment by Salakar** [comment]
Hey, :wave:, the `firebase_ml_vision` package is now discontinued since its APIs have been deprecated and removed from the Android & iOS Firebase SDKs.

I'd recommend switching to the alternatives now;

 - **for on-device vision APIs**; switch to Google's standalone ML Kit library via [google_ml_kit](https://pub.dev/packages/google_ml_kit)
 - **for cloud vision APIs**; the recommended approach now is to use Firebase
Authentication and Functions, which gives you a managed, serverless gateway to the Google Cloud Vision APIs. For an example Functions project see the [vision-annotate-images](https://github.com/firebase/functions-samples/tree/master/vision-annotate-images) sample project. You'd deploy this project for example and then call the cloud function from your app with your image data to get the annotation result.

Apologies for any inconvenience here and best of luck switching over the the new APIs. `firebase_ml_custom` is not affected by this deprecation.

Thanks
