### ISSUE TITLE
FCM onMessage callback passes Map<String,dynamic> that contains subnodes of type Map<dynamic,dynamic>

### ISSUE THREAD

**Issue by safield** [FirebaseExtended/flutterfire#2804]
I have implemented the method callbacks for FCM in dart (onMessage , onResume, onLaunch).

The required signature of these functions is Function(Map<String,dyanmic>). Map<String,dynamic> is the logical representation of json structure, since all keys in json are type String.

Contrary to this, the field "notification" contains an _internalLinkedHashMap<dynamic,dynamic>. This breaks the json parsing library I use, as it expected every field to contain the following types...
-Map<String,dynamic>
-List<Map<String,dynamic>>
-basic types, or list of basic types.

The expected behaviour is that all keys are represented at String and not dynamic.

**Comment by Salakar** [comment]
Closing in favour of trying the latest messaging version which has since this issue was created been heavily reworked to improve it along with detailed documentation: https://firebase.flutter.dev/docs/messaging/overview

If you still have a problem please raise a new GitHub issue with up to date information and code snippets if possible. Thanks.
