### ISSUE TITLE
[firebase_analytics] List type paramters

### ISSUE THREAD

**Issue by najmsaqib** [FirebaseExtended/flutterfire#2835]
Firebase Analytics documents says that "ITEMS" parameter supports "Parcelable[]" for android and "NSArray" for IOS but this feature is missing in Flutter firebase_analytics 5.0.15 and we can't pass List to ITEMS parameter.

Documents for Android:
https://firebase.google.com/docs/reference/android/com/google/firebase/analytics/FirebaseAnalytics.Event#ADD_TO_CART

Documents for IOS:
https://firebase.google.com/docs/reference/swift/firebaseanalytics/api/reference/Constants#/c:FIREventNames.h@kFIREventAddToCart

**Comment by GursheeshSingh** [comment]
Even for logViewItemList

**Comment by keobrien** [comment]
+1 this would be extremely useful for working around any events that are not yet implemented like the new purchase event that replaces the ecommerce_purchase event. Also, iOS seems to allow the event with the list to be sent but Android does not. Looks like the issue is in android/src/main/java/io/flutter/plugins/firebaseanalytics/FirebaseAnalyticsPlugin.java createBundleFromMap does not support an Array List.

Error message:
`java.lang.IllegalArgumentException: Unsupported value type: java.util.ArrayList`

**Comment by CameliaTripon** [comment]
When can we expect this to be fixed? It is really an issue which postpones our release since the Enhanced Ecommerce bundle list is requested by our marketing team.

**Comment by rubenvereecken** [comment]
We too need List type parameters.

**Comment by CameliaTripon** [comment]
Hello. I saw that the PR with the fix was merged to master. Any idea when we will have a release with this?
