### ISSUE TITLE
[Firebase cloud messaging] all notifications at once

### ISSUE THREAD

**Issue by sergitovar91** [FirebaseExtended/flutterfire#2903]
Hi ! I would need your help. I have an application mobile (android and iOS) with flutter and firebase cloud messaging.

My case: I receive 4 notifications on the device (as an example) and I want to read all of them when I click in the application’s icon. Currently I have to click each notification to read it and be able to create the widgets

How can I do it ?

For both Android and iOS ! Thanks !!!

**Comment by Salakar** [comment]
Closing in favour of trying the latest messaging version which has since this issue was created been heavily reworked to improve it along with detailed documentation: https://firebase.flutter.dev/docs/messaging/overview

If you still have a problem please raise a new GitHub issue with up to date information and code snippets if possible. Thanks.
