### ISSUE TITLE
Fatal: failed to find callback

### ISSUE THREAD

**Issue by panchalAlpit** [FirebaseExtended/flutterfire#2906]
E/FlutterFcmService( 3245): Fatal: failed to find callback
W/FirebaseMessaging( 3245): Notification Channel set in AndroidManifest.xml has not been created by the app. The default value will be used.
E/FlutterFcmService( 3245): Fatal: failed to find callback

**Comment by TahaTesser** [comment]
duplicate of https://github.com/FirebaseExtended/flutterfire/issues/2906

**Comment by apiep** [comment]
Hi I think this was caused by this line https://github.com/FirebaseExtended/flutterfire/blob/4511f7c21a63a77b9ef69344402574cced5c5d07/packages/firebase_messaging/android/src/main/java/io/flutter/plugins/firebasemessaging/FlutterFirebaseMessagingService.java#L147

which in my understanding are can not find callback for handling incoming message while in background?
Maybe skip the line without logging, or change the log into `Info` / `Warn` instead of `Fatal`?
