### ISSUE TITLE
firebase_ml_vision is using Deprecated libraries

### ISSUE THREAD

**Issue by kw2019ltd** [FirebaseExtended/flutterfire#3026]
hi according to google com.google.firebase:firebase-ml-vision are Deprecated libraries.

and need to use com.google.mlkit libraries

https://developers.google.com/ml-kit/vision/barcode-scanning/android

when flutter planing to adopt it?

**Comment by A3XXFR** [comment]
Too would like to know

**Comment by wildsurfer** [comment]
Any progress here?

**Comment by prakharb10** [comment]
Any updates on how to migrate to ML Kit from Firebase ML?

**Comment by svenjacobs** [comment]
Google split [ML Kit for Firebase](https://firebase.google.com/docs/ml-kit) into two new projects: [Firebase Machine Learning](https://firebase.google.com/docs/ml), which requires a Firebase project and supports Cloud computation and [ML Kit](https://developers.google.com/ml-kit), which is a standalone solution that does not require Firebase and works on device.

I guess `firebase_ml_vision` would have to be migrated to Firebase ML. I'm not sure if it's possible to support Firebase ML **and** ML Kit with one Flutter plugin? Maybe a new plugin needs to be written for ML Kit?

Trying to use ML Kit with the current version of `firebase_ml_vision` does **not work**.

**Comment by Miko2x** [comment]
Any updates on this? ＞﹏＜
In the written documentation it can be used with or without Firebase but in the usage section to use this plugin should configure Firebase for each platform project o(一︿一+)o , what should i do? just configure it?

**Comment by hugopretorius914** [comment]
Also curious about any updates on this?

**Comment by mazmellow** [comment]
Has anyone know who's trying to convert google new [MK Kit](https://developers.google.com/ml-kit) to flutter plugin?

**Comment by 2shrestha22** [comment]
any updates?

**Comment by Salakar** [comment]
Hey, all :wave:, the `firebase_ml_vision` package is now discontinued since its APIs have been deprecated and removed from the Android & iOS Firebase SDKs.

I'd recommend switching to the alternatives now;

 - **for on-device vision APIs**; switch to Google's standalone ML Kit library via [google_ml_kit](https://pub.dev/packages/google_ml_kit)
 - **for cloud vision APIs**; the recommended approach now is to use Firebase
Authentication and Functions, which gives you a managed, serverless gateway to the Google Cloud Vision APIs. For an example Functions project see the [vision-annotate-images](https://github.com/firebase/functions-samples/tree/master/vision-annotate-images) sample project. You'd deploy this project for example and then call the cloud function from your app with your image data to get the annotation result.

Apologies for any inconvenience here and best of luck switching over the the new APIs. `firebase_ml_custom` is not affected by this deprecation.

Thanks
