### ISSUE TITLE
[firebase_admob] Feature request: Ads in Scrollable views

### ISSUE THREAD

**Issue by JesseBIT** [FirebaseExtended/flutterfire#3105]
I'm surprised we can't have native ads and it's against policy to have banner ads in a scrollview scrollable with content. Think apps like facebook, twitter and reddit. Users are accustomed to seeing ads and sponsered content in this manner. A banner ad at the top or bottom of an app looks unprofessional and certainly ruins the brilliant look of flutter material io when having to consider placement with bottom navigation bars etc.

Please reconsider as i think the policy and guidance is dated, this is a showstopper for me using admob, otherwise i will need to consider another solution.

Thanks

**Comment by kmcgill88** [comment]
As the maintainer of [admob_flutter](https://github.com/kmcgill88/admob_flutter) I would like to get further clarification on the [Admob docs](https://support.google.com/admob/answer/6275345?hl=en&ref_topic=2936214) which states.
`banner ads should not move as a user scrolls, as users may try to click on the menu but end up clicking on the ad accidentally instead. This specific implementation is against policy and we reserve the right to disable ad serving to your app.`

I agree there are many apps out there that in-line ads with content, the biggest being scrollable feeds. [admob_flutter](https://github.com/kmcgill88/admob_flutter) example app is based on this. I would like to update the example app to follow best practices and not have the example app promoting a bad practice. Could you please give direction on this or point me in the direction of someone who can give more definite answers? Thanks!

**Comment by peterkapena** [comment]
We definitely need Native ads!

When are Native ads going to be able to be implemented in the widget tree?
How can one be notified when this is available?

**Comment by mileusna** [comment]
> How can one be notified when this is available?
 Subscribe to this issue and this https://github.com/FirebaseExtended/flutterfire/issues/1175 and wait (indefinitely) to become "Closed".

**Comment by mingosnunes** [comment]
Google is breaking this policy in the Google Play Store. Of course, they are not using the AdMob service, but they can't demand one policy for us (developers) with an excuse of protecting the users when they do exactly that. 

These ads are on scroll views and they look exactly the same as "normal" content with a difference of the label "Ads" in a smaller font than "Suggested for you" title. This is misleading the users and is clearly not optimise for my use because I already have those apps installed. This is purely who pays the most are on the top of list.

I'm not saying that I disagree with this layout approach, I want just that the same. Native ads that the user can scroll and blend in just like other content (blog and social media posts, news, sports' scores, etc), with the label "Ad" or "Advertisement" very clear. Just like any other modern application (Facebook, Instagram, Twitter, Reddit, etc).

I believe that Google is not doing this with an anti-competitive mindset (they earn a lot of money with our ads). They are just protecting their ad network of bad developers, but this is a dated policy which they break on their own apps. 

I like to ear your opinion on this topic and fell free to link this comment to other discussions or just point me where I can link this to spread the word.

Many thanks.

Screenshot links:
- https://photos.app.goo.gl/qiSp6qVxxBHCm8bG9
- https://photos.app.goo.gl/AqjsmX1Rr34wMnMT8

**Comment by JesseBIT** [comment]
https://github.com/kmcgill88/admob_flutter/issues/181#issuecomment-730164900

This is great news! Ironically this is one of 2 minor issues preventing me publishing (Im using Kevins plugin but it's not smooth in list and I havent wanted to release the app with tacky Ads at the bottom of the app), so not sure i'll get selected for Beta ☹

**Comment by russellwheatley** [comment]
The `firebase_admob` plugin will be deprecated in April 2021 in favor of [Google Mobile Ads SDK for Flutter](https://github.com/googleads/googleads-mobile-flutter).
Google Mobile Ads SDK for Flutter is a new Flutter plugin that supports more Ads formats than `firebase_admob` does. Google Mobile Ads SDK for Flutter currently supports loading and displaying banner, interstitial (full-screen), native ads, and rewarded video ads across AdMob and AdManager. It also supports displaying banner and native ads as `Widgets` as opposed to being overlayed over all app content.
We're now recommending projects currently using `firebase_admob` migrate to Google Mobile Ads SDK for Flutter following the [instructions outlined here](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_admob#migrating-to-google-mobile-ads-sdk-for-flutter).
Issues with migrating or with using the new package should now be raised over on the [Google Mobile Ads SDK for Flutter](https://github.com/googleads/googleads-mobile-flutter) repository.

**Comment by JesseBIT** [comment]
Look forward to trying this out.
