### ISSUE TITLE
iOS build crashes settingup firebase_messaging Undefined symbols for architecture arm64: "_OBJC_CLASS_$_FLTFirebaseCorePlugin"

### ISSUE THREAD

**Issue by sandrush73** [FirebaseExtended/flutterfire#3168]
Hi i am trying to setup firebase for my ios project and i did add googleservices-info.plist to my runner project. i am unable to get pass this i have even tried setting it up in a empty project just with firebase_messaging: ^6.0.16 in yaml file, thanks ...

```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_FLTFirebaseCorePlugin", referenced from:
      objc-class-ref in GeneratedPluginRegistrant.o
  "_OBJC_CLASS_$_FLTFirebaseMessagingPlugin", referenced from:
      objc-class-ref in GeneratedPluginRegistrant.o
  "_OBJC_CLASS_$_FLTFirebaseAnalyticsPlugin", referenced from:
      objc-class-ref in GeneratedPluginRegistrant.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)``
```

**Comment by russellwheatley** [comment]
Closing in favour of trying the latest messaging version which has been been heavily reworked, along with documentation, since this issue was raised: [https://firebase.flutter.dev/docs/messaging/overview](https://firebase.flutter.dev/docs/messaging/overview)If you still have a problem please raise a new GitHub issue with up to date information and code snippets if possible. Thanks.
