### ISSUE TITLE
[firebase_ml_vision] Inconsistent behaviour during text recognition

### ISSUE THREAD

**Issue by PolinaGo** [FirebaseExtended/flutterfire#3174]
**Describe the bug**
When recognizing text in an image without text:

On Android:
* Text recognizer returns empty text
* Cloud text recognizer returns Unhandled Exception: PlatformException(textRecognizerError, Internal error has occurred when executing Firebase ML tasks, null)
* Document text recognizer crushes because it tries to .getText() on a null object reference

On IOS:
* All recognizers return empty text

**To Reproduce**
* Check the results of the recognizers in the example app

**Expected behavior**
* Behave in the same way as the native SDKs

**Additional context**
Treating response from the native APIs is inconsistent between IOS and Java:
in IOS the output is checked for being null, in Java it is assumed to be non-null.

It is likely that behaviour of Java SDKs is not consistent either.

**Flutter doctor**
Run `flutter doctor` and paste the output below:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.1, on Mac OS X 10.15.4 19E287, locale en)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio
[✓] Android Studio (version 3.6)
[✓] Connected device (2 available)

• No issues found!
```

**Comment by PolinaGo** [comment]
I am currently working on the fix, and I am hoping to post a pull request sometime this/next week.

**Comment by Salakar** [comment]
Hey, :wave:, the `firebase_ml_vision` package is now discontinued since its APIs have been deprecated and removed from the Android & iOS Firebase SDKs.

I'd recommend switching to the alternatives now;

 - **for on-device vision APIs**; switch to Google's standalone ML Kit library via [google_ml_kit](https://pub.dev/packages/google_ml_kit)
 - **for cloud vision APIs**; the recommended approach now is to use Firebase
Authentication and Functions, which gives you a managed, serverless gateway to the Google Cloud Vision APIs. For an example Functions project see the [vision-annotate-images](https://github.com/firebase/functions-samples/tree/master/vision-annotate-images) sample project. You'd deploy this project for example and then call the cloud function from your app with your image data to get the annotation result.

Apologies for any inconvenience here and best of luck switching over the the new APIs. `firebase_ml_custom` is not affected by this deprecation.

Thanks

**Comment by Duc333333** [comment]
#4200
