### ISSUE TITLE
Firebase Products Depending on Core

### ISSUE THREAD

**Issue by PeterHdd** [FirebaseExtended/flutterfire#3226]
After upgrading the plugins to the latest release, why is it required now to use `firebase_core` and initialize it first before using any other firebase plugin?

In android native for example, you can just add the dependency related to cloud firestore or any other product and use it immediately in your code.

Before we had to use it, but it was changed later on:

>The Firebase Android library firebase-core is **no longer needed**. This SDK included the Firebase SDK for Google Analytics.

>Now, to use Analytics or a product that recommends the use of Analytics (see table below), you need to explicitly add the Analytics dependency: com.google.firebase:firebase-analytics:17.5.0 or com.google.firebase:firebase-analytics-ktx:17.5.0.

https://firebase.google.com/support/release-notes/android

Also back then we needed to only add `firebase-core` as a dependency in the gradle file, but we didn't need to even call `initializeApp()`, according to the documentation:

>For a vast majority of apps, FirebaseInitProvider will handle the initialization of Firebase for the default project that it's configured to work with, via the data contained in the app's google-services.json file. This ContentProvider is merged into the app's manifest by default when building with Gradle, and it runs automatically at app launch. **No additional lines of code are needed in this case.**

https://firebase.google.com/docs/reference/android/com/google/firebase/FirebaseApp

**Comment by Ehesp** [comment]
Without going into too much detail, the main reason for this change is to allow the initialisation of constant values, which helps us to align the API with the JavaScript API. For example, in the previous versions to check whether the `currentUser` on the Authentication module exists required an async call to native, now this is pre-populated when calling `initializeApp()`.

I'll close this since it's a none issue, however happy to discuss.
