### ISSUE TITLE
[Analytics] Support manual logging of screen_view event

### ISSUE THREAD

**Issue by ghost23** [FirebaseExtended/flutterfire#3267]
We currently cannot use the analytics capabilities of the screen_view events in firebase, because the current version of the flutter firebase analytics sdk does not support turning of the automatic screen_view tracking, while at the same still allowing to manually track screen_view events. The result is, we get some automatic screen_view events, which are meaningless to us (events with the class name MainActivity.java, for example).

The native firebase analytics sdks recently received an update to be able to turn off automatic screen_view tracking, while at the same time still allowing to manually track the screen_view events, which can be tracked like a normal event now through logEvent (so it is not a reserved word anymore).

https://firebase.googleblog.com/2020/08/google-analytics-manual-screen-view.html

My feature request is: please support the possibility to turn off the automatic screen_view tracking for both android and iOS and enable calling logEvent with 'screen_view".

**Comment by benPesso** [comment]
You can kind of do that with `FirebaseAnalyticsObserver`. But that will still trigger the `MainActivity` event. It also requires some additional hooks in the code for routes that are not named, and overall doesn't provide the same flexibility as just doing your own implementation with 'logEvent'.

At minimum, we should be able to enable/disable it via `FirebaseOptions` on initialization. Maybe as an array of exclusions:
```dart
await Firebase.initializeApp(
  options: FirebaseOptions(
    excludeDefaultEvents: [
      FirebaseEvent.appException,
      FirebaseEvent.screenView,
    ],
  ),
);
```

**Comment by jpgpuyo** [comment]
Hello, I agree with this request. Events like 'MainActivity' are not useful for metrics:

![image](https://user-images.githubusercontent.com/7917956/105646385-fea57780-5e9f-11eb-9d8e-2511bcbe8783.png)

![image](https://user-images.githubusercontent.com/7917956/105646748-e7678980-5ea1-11eb-85cd-043452adab85.png)

It is difficult to find a reason to consider this a desired behaviour, so from my point of view this issue should be fixed in firebase analytics side.

Not sure if send screen view as event it is enough, because this would be a breaking change for the people that is analyzing the dashboards.

If someone finds a solution for this, it would be amazing!

Thanks!

**Comment by FranzSw** [comment]
> If someone finds a solution for this, it would be amazing!

The current solution is to copy the firebase analytics file and remove the check for reserved event names. It works well, we are using that in an app.

**Comment by danilofuchs** [comment]
For now we are sticking with the old `setCurrentScreen` API. Firebase should fix this ASAP!

We will do a test adding `FirebaseAutomaticScreenReportingEnabled` to `Info.plist` and `google_analytics_automatic_screen_reporting_enabled false` to `AndroidManifest.xml`

**Comment by jjoelson** [comment]
Hi @danilofuchs!  It does seem as though logging the `screen_view` event manually is [officially recommended](https://firebase.googleblog.com/2020/08/google-analytics-manual-screen-view.html), and for some good reasons. Indeed, [setScreenName:screenClass:](https://firebase.google.com/docs/reference/ios/firebaseanalytics/api/reference/Classes/FIRAnalytics#+setscreenname:screenclass:) is marked as deprecated as of Firebase 6.29.0.

So I think it makes sense that at minimum `screen_view` be removed from the disallowed reserved list of event names. I agree that, ideally, `setCurrentScreen` would work with automatic screen reporting is disabled, but it's hard to see that ever getting fixed at this point since it's been deprecated and superseded by a new API.
