### ISSUE TITLE
[<firebase_messaging>] <Unclear instruction for Android Integration>

### ISSUE THREAD

**Issue by pazhut** [FirebaseExtended/flutterfire#3321]
Hi

i am trying to integrate the plugin into my app. i am finding the Android integration section confusing. in the main plugin page (https://pub.dev/packages/firebase_messaging) you are describing a method of creating a new Java class (Application.java) and adding some code to it to initialize the plugin. however looking at your example code (https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_messaging/example) i cannot find any of that implementation. so as you can see there are some confusing around this.
i wonder if you can help and clear this out, what needs to be done, maybe you have other examples?

one more question, i would like to try and get more clear explanation what onBackgroundMessage is being used for, i cannot see this in your exemple code and would like to be sure i am implementing this correctly.

Thanks much

**Comment by russellwheatley** [comment]
Closing in favour of trying the latest messaging version which has been been heavily reworked, along with documentation, since this issue was raised: [https://firebase.flutter.dev/docs/messaging/overview](https://firebase.flutter.dev/docs/messaging/overview)If you still have a problem please raise a new GitHub issue with up to date information and code snippets if possible. Thanks.
