### ISSUE TITLE
Flutter FCM works in debug environment but doesn't work in foreground of release version.

### ISSUE THREAD

**Issue by Doetheman** [FirebaseExtended/flutterfire#3349]
FCM works in the background of my app. I followed the documentation to integrate firebase messageing. See my flutter version below. When I test on a simulator, I get all notifications. What could be the issue?

[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.4 19E266, locale en-CA)
 
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    ✗ Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 4.0)
[✓] Connected device (1 available)

**Comment by TahaTesser** [comment]
Hi @Doetheman 
Can you please provide  `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by rever96** [comment]
I have the same problem: the app-release.apk doesn't get any notification.
With flutter run the app gets all notification correctly.
using `flutter run --release --verbose` I get these lines when i send the notification:
`[+110260 ms] E/FlutterFcmService(28203): Fatal: failed to find callback
[  +59 ms] I/flutter (28203): onMessage: {notification: {body: Utilizzando API Firebase, title: Notifica tramite server Heroku}, data: {}}`

the first message arrives because I didn't configurate the onBackground callback.
the second message describes the notification content.

**Comment by rever96** [comment]
For me it wasn't a fcm problem. I had a problem on the first login firebase auth id that cause me to not initialize of fcm.configure.
Hope it helps
