### ISSUE TITLE
🐛 [FIREBASE_CORE] Could not find method implementation() for arguments [project ':firebase_core']

### ISSUE THREAD

**Issue by lrmyr** [FirebaseExtended/flutterfire#3368]
## Bug report

After updating according to the migration guide (https://flutter-firebase-docs.web.app/docs/migration) I receive the following build error:

FAILURE: Build failed with an exception.

* Where:
Script 'D:\Projekt\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 362

* What went wrong:
A problem occurred configuring project ':cloud_firestore_web'.
> Could not find method implementation() for arguments [project ':firebase_core'] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 16s
Finished with error: Gradle task assembleDebug failed with exit code 1

### Steps to reproduce

1. Open new flutter project
2. Follow this guide: https://flutter-firebase-docs.web.app/docs/installation/android
3. Add  firebase_core: "^0.5.0", firebase_auth: "^0.18.0+1" and  cloud_firestore: "^0.14.0+2" to the pubspec.yaml
4. Run pub get
5. Try flutter run on emulator

### Expected behavior

Build success without the described exception thrown.

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[√] Flutter (Channel stable, v1.12.13+hotfix.7, on Microsoft Windows [Version 10.0.18362.1016], locale de-DE)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.
[√] Android Studio (version 4.0)
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

**Comment by Ehesp** [comment]
What version of gradle do you have?

**Comment by lrmyr** [comment]
gradle: 4.0.1 in android/build.gradle and https\://services.gradle.org/distributions/gradle-6.1.1-all.zip as distributionURl

**Comment by Salakar** [comment]
Please update your gradle to 5.6.2 to fix this. See the steps mentioned here in the migration guide: https://firebase.flutter.dev/docs/migration#a-android-installation

**Comment by lrmyr** [comment]
Sorry for the misunderstanding. I'm already using the newest gradle version (6.1.1). Even after downgrading to 5.6.2 I get the same error. 4.0.1 is the plugin version I'm using (https://developer.android.com/studio/releases/gradle-plugin)

**Comment by lrmyr** [comment]
Solved the issue by running flutter upgrade first. Add the following dependecy `implementation "com.google.firebase:firebase-messaging:20.2.4" ` to your android/app/build.gradle if you want to continue using the cloud messaging plugin

**Comment by MohTarekElbro** [comment]
> Solved the issue by running flutter upgrade first. Add the following dependecy `implementation "com.google.firebase:firebase-messaging:20.2.4" ` to your android/app/build.gradle if you want to continue using the cloud messaging plugin

I did that but I'm still facing the same problem, any one help please

**Comment by thassio-vinicius** [comment]
I'm facing the same issue. Any solution yet? I've tried downgrading my gradle to 5.6.2 but it didn't work

**Comment by lrmyr** [comment]
Could you provide your flutter doctor output?

**Comment by jippylong12** [comment]
Howdy all, 

I would love to give my feedback on what I think helped solve this problem. I will order them not in the results I found them but in what I think was the most important. 

**1) Upgrade Flutter**

Command `flutter upgrade`
I installed Flutter long ago and I thought I upgraded it recently when creating this new app. Regardless I wasn't on the latest version and so my Flutter upgraded. 

2**) Update Firebase Packages**
If you're like me and use FlutterFire then you most likely ran into this issue where parity is gone between questions you may find on StackOverflow and the current FlutterFire docs. As always try to use the docs on FlutterFire, but what you may find like I did was all my Firebase dependencies were versions behind the docs. 

So starting from the [Overview of the Doc in FlutterFire](https://firebase.flutter.dev/docs/overview)

Be sure to install the correct Firebase_core version and then for every other library you use, be sure that the version in the pubspec.yaml is matching what is in the docs. 

**3) Updating Gradle**
Perhaps this was because my Android Studio version was behind when I created my project or perhaps this is just another issue of parity between Android Studio and Flutter updates. But I had to update my Gradle file in two places. 

1) /android/build.gradle
Android studio helped me out but make sure your com.android.tools.build:gradle: is at the latest version which in my case of now is 4.0.1.
> dependencies {
        classpath 'com.android.tools.build:gradle:4.0.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.3'  // Google Services plugin
    }

2) android/gradle/wrapper/gradle-wrapper.properties
I had to update this also what the errors told me was the latest version in this case as of now being 6.1.1
> #Fri Jun 23 08:50:38 CEST 2017
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-6.1.1-all.zip

So if there is a newer version just replace the 6.1.1 with the latest distribution version. 

Once I did all of this, I was able to compile the code again and also use the Flutter docs just as they are. 
Hopefully this resolves the issue for any one else.

**Comment by chetankatke** [comment]
upgrading flutter solved my problem
