### ISSUE TITLE
[docs] Moving Flutterfire plugins to FirebaseExtended broke many links

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#341]
Pretty much every link on this page is broken:

https://firebaseopensource.com/projects/flutter/plugins/

Thanks to this commit...

https://github.com/flutter/plugins/commit/3ad2d1d300b0d901ea9739e3b9f08eeebda8be04

Where is the source code now? Just a big treasure hunt. =(

**Comment by kroikie** [comment]
@lookfirst

The issue at https://github.com/flutter/flutter/issues/39975 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by Levi-Lesches** [comment]
Well the [Firebase website](https://firebaseopensource.com/projects/flutter/plugins/) is fine, for what it's worth. As mentioned in the issue above, codelabs and flutter sample apps are probably still broken. Pub seems to be updated, but perhaps the "Homepage" link can point to the Firebase site instead of just the GitHub page, and the "Repository" link can be changed to the package-specific folder in the repo. I would start a GitHub checklist thing, but maybe that should be done by someone who's actually going to fix it.

**Comment by Levi-Lesches** [comment]
Also, cc @Hixie and @collinjackson from the original issue.

**Comment by iapicca** [comment]
Hi @lookfirst
from [Collin's post](https://github.com/flutter/flutter/issues/39975#issuecomment-530910935) and what I can observe [here](https://firebaseopensource.com/projects/flutter/plugins/) the situation you described seams to be changed.
Is there any pending issue on the matter?
Thank you

**Comment by Levi-Lesches** [comment]
The previous issue also mentioned codelabs, those should be double checked too.
