### ISSUE TITLE
Firebase ML Vision Flutter plugin 0.9.6+2 does not work with ML Kit

### ISSUE THREAD

**Issue by i3games** [FirebaseExtended/flutterfire#3473]
In the Readme for `firebase_ml_vision` 0.9.6+2 from August 2020 on [//pub.dev/packages/firebase_ml_vision](//pub.dev/packages/firebase_ml_vision ) the description states that the plugin works with  "[...] ML Kit, a standalone library for on-device ML, which can be used with or without Firebase."

This is not the case. The plugin currently does not work with the new **ML Kit**. In addition, the documentation of the plugin refers to the deprecated **Firebase ML Kit**, e.g..

```
api 'com.google.firebase:firebase-ml-vision-face-model:17.0.2'
```

According to the ML Kit documentation (https://developers.google.com/ml-kit/migration/android), these APIs are deprecated and should be replaced with ML Kit dependencies. Simply replacing the dependencies does not work, however.

related #3469, #3026

**Comment by i3games** [comment]
More information and context: https://gist.github.com/i3games/b30471060c6ca723619e21330a66c1f8

**Comment by enrichman** [comment]
In my case I think that XCode set up the min target to 11. I've downgrade it to `platform :ios, '9.0'` and then run a `flutter clean` and a `pod deintegrate` (just to be sure.

It worked. I know that is not a "solution" but it's a workaround (for me targeting iOS 9 was fine).

**Comment by Salakar** [comment]
Hey, :wave:, the `firebase_ml_vision` package is now discontinued since its APIs have been deprecated and removed from the Android & iOS Firebase SDKs.

I'd recommend switching to the alternatives now;

 - **for on-device vision APIs**; switch to Google's standalone ML Kit library via [google_ml_kit](https://pub.dev/packages/google_ml_kit)
 - **for cloud vision APIs**; the recommended approach now is to use Firebase
Authentication and Functions, which gives you a managed, serverless gateway to the Google Cloud Vision APIs. For an example Functions project see the [vision-annotate-images](https://github.com/firebase/functions-samples/tree/master/vision-annotate-images) sample project. You'd deploy this project for example and then call the cloud function from your app with your image data to get the annotation result.

Apologies for any inconvenience here and best of luck switching over the the new APIs. `firebase_ml_custom` is not affected by this deprecation.

Thanks
