### ISSUE TITLE
Versions newer than 0.12.11 produces just  a blank web page

### ISSUE THREAD

**Issue by lipocodes** [FirebaseExtended/flutterfire#3513]
## Bug report

**Describe the bug**
When I run the command:  flutter build web   => I get a blank web page.  If I use cloud_firestore::0.12.11 OR older,  all runs perfectly well.

### Steps to reproduce

1. flutter doctor.   No issues found.
2. flutter run -d chrome.  The app runs OK on the local browser.
3. flutter build web.  The app runs and shows a blank page.
4.  In pubspec.yaml:  remove the dependency  cloud_firestore:  The app runs OK.
5. In pubspec.yaml:  add the dependency cloud_firestore:0.12.11  (older version), The app runs OK.

### Expected behavior

I need to use cloud_firestore: 0.14.0+2   so I can use the data type FirebaseFirestore.

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, 1.22.0-9.0.pre, on Microsoft Windows [Version 10.0.18362.1082], locale he-IL)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 4.0)
[√] Connected device (3 available)

• No issues found!
```

PASTE OUTPUT INSIDE HERE

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

```

dependencies:
- characters 1.1.0-nullsafety.2
- cloud_firestore 0.12.11 [flutter meta collection firebase_core]
- cupertino_icons 0.1.3
- dio 3.0.10 [http_parser path]
- firebase 7.3.0 [http http_parser js]
- firebase_auth 0.16.1 [meta firebase_core firebase_auth_platform_interface firebase_auth_web flutter]    
- firebase_storage 3.1.6 [flutter firebase_core]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_localizations 0.0.0 [flutter intl characters collection meta path typed_data vector_math]       
- flutter_mobx 1.1.0+2 [mobx flutter]
- flutter_webview_plugin 0.3.11 [flutter]
- flutter_widget_from_html_core 0.4.3 [flutter html]
- font_awesome_flutter 8.8.1 [flutter]
- http 0.12.2 [http_parser path pedantic]
- image_picker_web 1.0.9 [flutter flutter_web_plugins]
- mobx 1.2.1+2 [meta]
- random_string 2.1.0
- shared_preferences 0.5.8 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web]
- url_launcher 5.5.0 [flutter url_launcher_platform_interface url_launcher_web url_launcher_linux url_launcher_macos]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- async 2.5.0-nullsafety [collection]
- boolean_selector 2.1.0-nullsafety [source_span string_scanner]
- charcode 1.2.0-nullsafety
- clock 1.1.0-nullsafety
- collection 1.15.0-nullsafety.2
- csslib 0.16.2 [source_span]
- fake_async 1.1.0-nullsafety [clock collection]
- file 5.2.1 [intl meta path]
- firebase_auth_platform_interface 1.1.8 [flutter meta plugin_platform_interface]
- firebase_auth_web 0.1.3+1 [firebase_auth_platform_interface flutter flutter_web_plugins firebase http_parser meta js]
- firebase_core 0.4.5 [firebase_core_platform_interface flutter meta firebase_core_web]
- firebase_core_platform_interface 1.0.4 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.1.1+2 [firebase firebase_core_platform_interface flutter flutter_web_plugins meta js]
- flutter_web_plugins 0.0.0 [flutter characters collection meta typed_data vector_math]
- html 0.14.0+3 [csslib source_span]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- intl 0.16.1 [path]
- js 0.6.2
- matcher 0.12.10-nullsafety [stack_trace]
- meta 1.3.0-nullsafety.2
- path 1.8.0-nullsafety
- path_provider_linux 0.0.1+2 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_platform_interface 1.0.3 [flutter meta platform plugin_platform_interface]
- pedantic 1.9.0
- platform 2.2.1
- platform_detect 1.4.0 [meta pub_semver]
- plugin_platform_interface 1.0.2 [meta]
- process 3.0.13 [file intl meta path platform]
- pub_semver 1.4.4 [collection]
- quiver 2.1.3 [matcher meta]
- shared_preferences_linux 0.0.2+2 [file flutter meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 0.0.1+10 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 1.0.4 [meta flutter]
- shared_preferences_web 0.1.2+7 [shared_preferences_platform_interface flutter flutter_web_plugins meta] 
- sky_engine 0.0.99
- source_span 1.8.0-nullsafety [charcode collection path term_glyph]
- stack_trace 1.10.0-nullsafety [path]
- stream_channel 2.1.0-nullsafety [async]
- string_scanner 1.1.0-nullsafety [charcode source_span]
- term_glyph 1.2.0-nullsafety
- test_api 0.2.19-nullsafety [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0-nullsafety.2 [collection]
- url_launcher_linux 0.0.1+1 [flutter]
- url_launcher_macos 0.0.1+7 [flutter]
- url_launcher_platform_interface 1.0.7 [flutter meta plugin_platform_interface]
- url_launcher_web 0.1.2+1 [url_launcher_platform_interface platform_detect flutter flutter_web_plugins meta]
- vector_math 2.1.0-nullsafety.2
- xdg_directories 0.1.0 [path process flutter]

```

**Comment by TahaTesser** [comment]
Hi @lipocodes 
Can you please provide `flutter run --release -d chrome --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
Thank you

**Comment by amanv8060** [comment]
I am Facing Same problem  , here is the output of `flutter run --release -d chrome --verbose`

> [ +113 ms] executing: [/home/aman/Android/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +38 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 81a45ec2e5f80fa71d5135f1702ce540558b416d
[   +1 ms] executing: [/home/aman/Android/flutter/] git tag --contains HEAD
[ +216 ms] Exit code 0 from: git tag --contains HEAD
[        ] 1.21.0-9.2.pre
[  +19 ms] executing: [/home/aman/Android/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +7 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [/home/aman/Android/flutter/] git ls-remote --get-url origin
[   +6 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +67 ms] executing: [/home/aman/Android/flutter/] git rev-parse --abbrev-ref HEAD
[   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[  +66 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +29 ms] executing: /home/aman/Android/Sdk/platform-tools/adb devices -l
[  +37 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +108 ms] executing: /home/aman/Android/Sdk/platform-tools/adb devices -l
[  +72 ms] Found plugin cloud_firestore at /home/aman/Android/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.14.0+2/
[  +10 ms] Found plugin cloud_firestore_web at /home/aman/Android/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore_web-0.2.0+1/
[  +15 ms] Found plugin firebase_auth at /home/aman/Android/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.18.0+1/
[   +8 ms] Found plugin firebase_auth_web at /home/aman/Android/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth_web-0.3.0+1/
[   +3 ms] Found plugin firebase_core at /home/aman/Android/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.5.0/
[   +7 ms] Found plugin firebase_core_web at /home/aman/Android/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-0.2.0/
[  +99 ms] Found plugin cloud_firestore at /home/aman/Android/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.14.0+2/
[   +4 ms] Found plugin cloud_firestore_web at /home/aman/Android/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore_web-0.2.0+1/
[   +7 ms] Found plugin firebase_auth at /home/aman/Android/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.18.0+1/
[   +5 ms] Found plugin firebase_auth_web at /home/aman/Android/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth_web-0.3.0+1/
[   +2 ms] Found plugin firebase_core at /home/aman/Android/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.5.0/
[   +3 ms] Found plugin firebase_core_web at /home/aman/Android/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-0.2.0/
[  +99 ms] Generating /home/aman/Desktop/projects/allcppprogramswebappadmin/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +86 ms] List of devices attached
[   +3 ms] List of devices attached
[  +89 ms] Launching lib/main.dart on Chrome in release mode...
[  +62 ms] Found plugin cloud_firestore at /home/aman/Android/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.14.0+2/
[   +3 ms] Found plugin cloud_firestore_web at /home/aman/Android/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore_web-0.2.0+1/
[   +5 ms] Found plugin firebase_auth at /home/aman/Android/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.18.0+1/
[   +2 ms] Found plugin firebase_auth_web at /home/aman/Android/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth_web-0.3.0+1/
[   +1 ms] Found plugin firebase_core at /home/aman/Android/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.5.0/
[   +2 ms] Found plugin firebase_core_web at /home/aman/Android/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-0.2.0/
[  +33 ms] Found plugin cloud_firestore at /home/aman/Android/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.14.0+2/
[   +5 ms] Found plugin cloud_firestore_web at /home/aman/Android/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore_web-0.2.0+1/
[   +5 ms] Found plugin firebase_auth at /home/aman/Android/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.18.0+1/
[   +3 ms] Found plugin firebase_auth_web at /home/aman/Android/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth_web-0.3.0+1/
[   +1 ms] Found plugin firebase_core at /home/aman/Android/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.5.0/
[   +4 ms] Found plugin firebase_core_web at /home/aman/Android/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-0.2.0/
[  +30 ms] Generating /home/aman/Desktop/projects/allcppprogramswebappadmin/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[   +9 ms] Compiling lib/main.dart for the Web...
[  +21 ms] Initializing file store
[  +43 ms] Skipping target: gen_localizations
[  +21 ms] web_entrypoint: Starting due to {InvalidatedReason.inputChanged}
[  +10 ms] web_entrypoint: Complete
[   +8 ms] dart2js: Starting due to {}
[+32241 ms] dart2js: Complete
[ +797 ms] web_release_bundle: Starting due to {}
[ +135 ms] web_release_bundle: Complete
[ +814 ms] web_service_worker: Starting due to {}
[  +64 ms] web_service_worker: Complete
[  +74 ms] Persisting file store
[  +11 ms] Done persisting file store
[  +30 ms] Compiling lib/main.dart for the Web... (completed in 34.3s)
[ +274 ms] [CHROME]:
[   +1 ms] [CHROME]:DevTools listening on ws://127.0.0.1:41409/devtools/browser/6928a442-d6c2-4cff-aafa-b5cc3309c4c7
[ +432 ms] Warning: Flutter's support for web development is not stable yet and hasn't
[        ] been thoroughly tested in production environments.
[        ] For more information see https://flutter.dev/web
[   +1 ms] 🔥  To hot restart changes while running, press "r" or "R".
[   +3 ms] For a more detailed help message, press "h". To quit, press "q".


here is the code 

```
import 'package:flutter/material.dart';
void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.light(),
      // initialRoute: "/",
      title: 'Flutter Demo',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text("Hey"),
        ),
        body: Container(
          child: Text("Hey"),
          height: 200,
          width: 400,
          color: Colors.green,
        ));
  }
}

here is my pubspec.yaml
```
name: test
description: A new Flutter application.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  responsive_framework: ^0.0.8

  cupertino_icons: ^0.1.3
  firebase_core: ^0.5.0
  cloud_firestore: ^0.14.0+2
  firebase_auth: ^0.18.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

 ```

also the

**Comment by lipocodes** [comment]
> Hi @lipocodes
> Can you please provide `flutter run --release -d chrome --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
> Thank you

[ +214 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +117 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 7a4317519865146acda84702bba8775610598c0c
[   +1 ms] executing: [C:\flutter/] git tag --points-at HEAD
[ +117 ms] Exit code 0 from: git tag --points-at HEAD
[   +1 ms] 1.22.0-9.0.pre
[  +40 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +78 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/dev
[        ] executing: [C:\flutter/] git ls-remote --get-url origin
[  +58 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +121 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[  +58 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] dev
[ +122 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[  +19 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +8 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[  +28 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[  +29 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +54 ms] executing: C:\Users\Lior.LIPO\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +96 ms] List of devices attached
           65cb5487d340           device product:rolex model:Redmi_4A device:rolex transport_id:4
[  +55 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[  +22 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +224 ms] Found plugin cloud_firestore at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.14.0+2\
[  +23 ms] Found plugin cloud_firestore_web at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore_web-0.2.0+1\
[  +24 ms] Found plugin firebase_core at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.5.0\
[  +15 ms] Found plugin firebase_core_web at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-0.2.0\
[ +237 ms] Found plugin cloud_firestore at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.14.0+2\
[   +9 ms] Found plugin cloud_firestore_web at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore_web-0.2.0+1\
[  +26 ms] Found plugin firebase_core at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.5.0\
[  +12 ms] Found plugin firebase_core_web at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-0.2.0\
[  +59 ms] Generating
D:\versions_Toogle\lior\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java       
[ +273 ms] Launching lib\main.dart on Chrome in release mode...
[ +117 ms] Found plugin cloud_firestore at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.14.0+2\
[   +7 ms] Found plugin cloud_firestore_web at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore_web-0.2.0+1\
[  +21 ms] Found plugin firebase_core at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.5.0\
[  +14 ms] Found plugin firebase_core_web at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-0.2.0\
[  +67 ms] Found plugin cloud_firestore at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.14.0+2\
[   +5 ms] Found plugin cloud_firestore_web at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore_web-0.2.0+1\
[   +7 ms] Found plugin firebase_core at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.5.0\
[  +14 ms] Found plugin firebase_core_web at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-0.2.0\
[  +53 ms] Generating
D:\versions_Toogle\lior\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java       
[  +15 ms] Compiling lib\main.dart for the Web...
[  +33 ms] Initializing file store
[  +19 ms] Done initializing file store
[ +146 ms] Skipping target: gen_localizations
[  +58 ms] Skipping target: web_entrypoint
[+1059 ms] Skipping target: dart2js
[ +177 ms] Skipping target: web_release_bundle
[  +72 ms] Skipping target: web_service_worker
[   +1 ms] Persisting file store
[  +33 ms] Done persisting file store
[  +35 ms] Compiling lib\main.dart for the Web... (completed in 1.6s)
[+2077 ms] [CHROME]:
[   +3 ms] [CHROME]:DevTools listening on
ws://127.0.0.1:52813/devtools/browser/3e81927b-3939-4c09-89a3-7ebe73156a74
[ +779 ms] Warning: Flutter's support for web development is not stable yet and hasn't
[   +3 ms] been thoroughly tested in production environments.
[   +1 ms] For more information see https://flutter.dev/web



name: lior
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  cloud_firestore:

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

**Comment by lipocodes** [comment]
The issue was caused by a bug in the library.  Solved by now.
