### ISSUE TITLE
'Flutter run' in terminal cannot connect to VM Service, connection refused

### ISSUE THREAD

**Issue by Annelein** [FirebaseExtended/flutterfire#3514]
If I run 'Flutter run' in my terminal after a while it says:

Connecting to the VM Service is taking longer than expected...
Still attempting to connect to the VM Service...

Exception attempting to connect to the VM Service: SocketException: OS Error: Connection refused, errno = 61, address = 127.0.0.1, port = 50940
This was attempt #50. Will retry in 0:00:01.600000

But if I run it in X Code it works..

I have no clue what I am doing wrong,
flutter doctor -v doesn't give any exceptions (see screenshot)
I also attached a screenshot of flutter run --verbose and the pubspec.yaml

Apparently it is not a Flutter issue but a Firebase issue that's why I'm asking here..

Anyone that could help me out?
![Schermafbeelding 2020-09-07 om 17 14 18](https://user-images.githubusercontent.com/48122190/92725808-f9221780-f36c-11ea-8631-ceb0066af3ed.png)
![Schermafbeelding 2020-09-07 om 17 16 19](https://user-images.githubusercontent.com/48122190/92725822-fb847180-f36c-11ea-8893-e001f21193bb.png)
![Schermafbeelding 2020-09-09 om 10 27 00](https://user-images.githubusercontent.com/48122190/92725852-09d28d80-f36d-11ea-9518-01ae1b51a8f9.png)

**Comment by darshankawar** [comment]
Hi @Annelein,
Since you are also getting the error while creating a new project (`flutter create demo`) which doesn't have any Firebase related plugins, this doesn't seem to be specific to Firebase.  As we are already discussing this issue [here](https://github.com/flutter/flutter/issues/65349#issuecomment-690050759), I am closing this one to avoid duplication.
Thanks.
