### ISSUE TITLE
[firebase_auth] Migrate linkWithCredential function from FirebaseAuth to FirebaseUser

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#377]
Firebase authentication plugin should have `linkWithCredential` function inside the user object, currently, it is on the FirebaseAuth class which makes no sense. As the linking should be done to an existing user, adding the function to the user object would make more sense. 

Its similar approach to the native firebase auth SDKs on Android and IOS. Documentation to the `linkWithCredential` on Android is [here](https://firebase.google.com/docs/auth/android/account-linking).

**Comment by dotdoom** [comment]
There's an incomplete thread at https://github.com/flutter/flutter/issues/32317 with discussion (+cc @ebologger, @awazgyawali).

The issue description says "[linkWithCredential] is on the FirebaseAuth class which makes no sense". I tend to disagree: since linkWithCredential references no dynamic fields of FirebaseUser, it makes sense as a static method.

This change has broken the current architecture of our app since there's no FirebaseUser instance in the code path that used to invoke linkWithCredential.

**Comment by dotdoom** [comment]
Additionally I'd like to re-iterate that the following workflow now looks like it's making what you want, but doesn't:

```
user1 = login();
logout();
user2 = login();
user1.link(account);
```

because in reality this will do `user2.link(account)` since linkToCredential always operates on the currentUser.
