### ISSUE TITLE
[cloud_firestore] snapshots should have stream errors when errors occur in Query

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#384]
_Originally posted by @ened in https://github.com/flutter/flutter/issues/13904#issuecomment-473118195_

Can confirm Firestore does not crash anymore in case of a missing index. There is clear error description in the logs.

I would, however, expect the AsyncSnapshot to have the error field clearly set.

Sample code:

``` dart
StreamBuilder<QuerySnapshot>(
  stream: state.myQuery,
  builder: (BuildContext context, AsyncSnapshot<QuerySnapshot> snapshot) {
    if (snapshot.hasError) {
      return Text('Error: ${snapshot.error}');
    }
    print('snapshot: ${snapshot.connectionState}');
    switch (snapshot.connectionState) {
      case ConnectionState.done:
      case ConnectionState.waiting:
        return Container(
          child: const Center(child: CircularProgressIndicator()),
        );

      default:
        if (snapshot.data.documents.isEmpty) {
          return _buildEmptyPage();
        }

        return _buildListView(snapshot, context);
    }
  },
),
```

`snapshot.error` & `snapshot.hasError` really should be set in that case.

**Comment by kroikie** [comment]
@collinjackson

The issue at https://github.com/flutter/flutter/issues/31988 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by dustin-graham** [comment]
@kroikie Any update on this? This is definitely a challenge in our project. When we stream snapshots we will often find ourselves waiting for data which never returns because there was an underlying error which is never reported to us. When we go fetch the data once we get errors right away. Errors need to be reported consistently regardless of doing a single fetch or observing a stream of changes.   I think the only way we can work around this failure mode is to always do a single fetch first and then a stream of snapshots after. Is there any plans to change this behavior?

**Comment by allco** [comment]
@dustin-graham I have the same issue with error is not being reported, I have created another issue for this: https://github.com/FirebaseExtended/flutterfire/issues/2334

**Comment by Salakar** [comment]
Consolidating under #1223 - we'll be looking at parsing native error messages & codes and bubbling these up to the Dart layer in a consistent cross-platform format.
