### ISSUE TITLE
🐛 [admob? analytics?] console dashboard etc NO tracking

### ISSUE THREAD

**Issue by peterweb2005** [FirebaseExtended/flutterfire#3919]
## Bug report

**Platform**

 IOS only

**Describe the bug**
firebase console, Dashboard & Crashlytics > "Latest Release", no tracking on my app which used newest version of admob / crashlytics 
ie:
after Oct 2020,
Dashboard, user graph drop 9x% (other % may not upgrade newest version of my app)
Latest Release, no user use newest version of my app

### Steps to reproduce
used newest version after Oct 2020

**Comment by markusaksli-nc** [comment]
Hi @peterweb2005 
There is an open issue regarding this problem #2760
Could you please comment there and if the problem came from updating your dependencies could you include the output of your `flutter pub deps -- --style=compact` before and after the update that broke it?

Closing this as duplicate of #2760
Thank you
