### ISSUE TITLE
crashyltics test crash does not work on ios 

### ISSUE THREAD

**Issue by safield** [FirebaseExtended/flutterfire#4022]
I am deploying my flutter app on a IOS simulator.

I am trying to test crashlytics crashes.

I have followed all the steps here...https://firebase.flutter.dev/docs/crashlytics/overview/

Crashes on the android platform work. Crashes on IOS are not reported.

I am calling...

`FirebaseCrashlytics.instance.crash();`

To invoke a crash.

**Comment by MeshkaniMohammad** [comment]
Hi.
I have same error but for both android and ios and in the firebase panel, it stuck on ```We’ll be listening for your app to communicate with our servers```

**Comment by safield** [comment]
> Hi.
> I have same error but for both android and ios and in the firebase panel, it stuck on `We’ll be listening for your app to communicate with our servers`

This is a separate issue, as my app in initialized with android and crashes are being reported.

**Comment by markusaksli-nc** [comment]
Hi @safield 
Could you please provide your `flutter doctor -v`, `flutter pub deps -- --style=compact`, and `flutter run -v` logs in a plain text file (when crashing the app)?
Thank you

**Comment by andersonmendesdev** [comment]
In the debug console I received the message that the fault was sent, but in my firebase for ios panel I received the following message.
`1 missing dSYM must be uploaded to process 1 failure`

`firebase_core: ^0.5.1`
`firebase_crashlytics: ^0.2.2`

`flutter doctor -v`

[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.7 19H2, locale pt-BR)
    • Flutter version 1.20.4 at /Users/andersonmendes/development/flutter
    • Framework revision fba99f6cf9 (7 weeks ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/andersonmendes/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • iPhone 11 Pro Max (mobile) • 9F81BA84-FD55-4105-9E7D-AAB951E25702 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

**Comment by andersonmendesdev** [comment]
@safield  In order for debug mode to firebase map the ios failures correctly, it is necessary to upload the dSYMs file, for this to happen it is necessary to set DWARF with dSYM File in debug mode. That worked out for me.

[Doc](https://firebase.google.com/docs/crashlytics/get-deobfuscated-reports?platform=ios&authuser=1)

More often than not, dSYM files go missing because Xcode simply isn't producing them. When an upload fails, Crashlytics displays a "Missing dSYM" alert in the Firebase console. If you get this alert, first check that Xcode is producing the correct dSYM for every build:

1 - Open your project in Xcode and select the project file in the Xcode Navigator.

2- Select your main build target.

3 - Open the target's Build Settings tab, then click All.

4 - Search for "debug information format".

5 - Set Debug Information Format to DWARF with dSYM File for all your build types.

6- Rebuild your app.
