### ISSUE TITLE
MissingPluginException(No implementation found for method getAll on channel flutter: plugins.flutter.io/shared_preferences)

### ISSUE THREAD

**Issue by rehamalraee** [FirebaseExtended/flutterfire#4042]
MissingPluginException(No implementation found for method getAll on channel flutter: plugins.flutter.io/shared_preferences)
 when call shared preferences from myBackgroundMessageHandler

**Comment by markusaksli-nc** [comment]
Hi @rehamalraee 
It seems like this issue isn't related to any of the flutterfire plugins. `shared_preferences` is a first-party flutter plugin. Please open a new issue regarding this in the [flutter/flutter](https://github.com/flutter/flutter/issues/new?assignees=&labels=&template=2_bug.md&title=) repository. Closing this since it is not valid here.
Thank you
