### ISSUE TITLE
🐛 [firebase_auth_web] not compatible with latest flutter version (1.24.0-8.0.pre.142)

### ISSUE THREAD

**Issue by talhakosen** [FirebaseExtended/flutterfire#4057]
## Bug report

**Describe the bug**
`firebase_auth_web` needs to depends on `intl ^0.17.0-nullsafety.2` because of the latest version of flutter depends on it

### Temporary Solution

```
dependency_overrides:
  intl: ^0.16.1

```

### Steps to reproduce

1. Update flutter version on master channel
2. Have `firebase_auth: ^0.18.3` and `firebase_auth_web: ^0.3.2` in your dependency
3. run `flutter pub get`

### Expected behavior

It should get all the dependencies without any error

---

## Additional context

Because firebase_auth_web 0.3.2 depends on intl ^0.16.1 and no versions of firebase_auth_web match >0.3.2 <0.4.0, firebase_auth_web ^0.3.2 requires intl ^0.16.1.
So, because styloor depends on both intl ^0.17.0-nullsafety.2 and firebase_auth_web ^0.3.2, version solving failed.
pub get failed (1; So, because styloor depends on both intl ^0.17.0-nullsafety.2 and firebase_auth_web ^0.3.2, version solving failed.)

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel master, 1.24.0-8.0.pre.142, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-NL)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.50.1)
[✓] Connected device (2 available)

```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Cannot get it because of the reason below
The pubspec.yaml file has changed since the pubspec.lock file was generated, please run "pub get" again.
```

</details>

---

**Comment by aiden-d** [comment]
Hi do you know any workarounds to fix this?

**Comment by talhakosen** [comment]
I have already added it, look at   **Temporary Solution** section in my question

dependency_overrides:
  intl: ^0.16.1

**Comment by darshankawar** [comment]
I wasn't able to replicate this on latest Master version (1.24.0-8.0.pre.149) by adding the said dependencies. `flutter pub get` ran without any issues.

<img width="338" alt="Screenshot 2020-11-09 at 7 06 24 PM" src="https://user-images.githubusercontent.com/67046386/98547781-ae664280-22be-11eb-8cf5-1cae020ddb1f.png">

<img width="586" alt="Screenshot 2020-11-09 at 7 06 41 PM" src="https://user-images.githubusercontent.com/67046386/98547813-b9b96e00-22be-11eb-8440-368e17c01f36.png">

Keeping this issue open since @Ehesp would look into it.

**Comment by talhakosen** [comment]
@darshankawar are you working on master channel?

**Comment by Ehesp** [comment]
We generally don't worry about things breaking on master channel, since it is prone to change and breaking things. If it breaks on a good `dev` build, we'll take a look.

**Comment by talhakosen** [comment]
> We generally don't worry about things breaking on master channel, since it is prone to change and breaking things. If it breaks on a good `dev` build, we'll take a look.

Same both master and dev, but have not tried on stable yet

**Comment by salahturkmen** [comment]
Same here, problem not solved?.

**Comment by Lurzapps** [comment]
firebase_auth_web depends on intl ^0.16.1
flutter_localizations depends on intl 0.17.0-nullsafety.2
so what could i do if I wanted to use both?

**Comment by esase** [comment]
any news about the issue? when we should expect it fixed ?

**Comment by felixwortmann** [comment]
@esase 
I just tried again with the latest versions and I get this:
```
Because no versions of firebase_auth match >0.20.0+1 <0.21.0 and firebase_auth 0.20.0+1 depends on firebase_auth_web ^0.3.2+6, firebase_auth ^0.20.0+1 requires firebase_auth_web ^0.3.2+6.
Because firebase_auth_web 0.3.2+6 depends on intl ^0.16.1 and no versions of firebase_auth_web match >0.3.2+6 <0.4.0, firebase_auth_web ^0.3.2+6 requires intl ^0.16.1.
Thus, firebase_auth ^0.20.0+1 requires intl ^0.16.1.
And because every version of flutter_localizations from sdk depends on intl 0.17.0-nullsafety.2, firebase_auth ^0.20.0+1 is incompatible with flutter_localizations from sdk.
```

So the problem still exists. <br><br>
I am using:
```
flutter_localizations:
    sdk: flutter
intl_translation: any
intl: any
firebase_auth: ^0.20.0+1
```

Flutter Doctor gives me:
```
[✓] Flutter (Channel beta, 1.25.0-8.3.pre, on macOS 11.1 20C69 darwin-x64, locale
    en-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.3.1)
[✓] VS Code (version 1.52.1)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by pugazhmara** [comment]
flutter channel stable

flutter upgrade

**Comment by felixwortmann** [comment]
> flutter channel stable
> 
> 
> 
> flutter upgrade

The problem occurs on the beta channel, so obviously this would fix it. You can not build flutter apps for the web on the stable channel though.

**Comment by P3tran** [comment]
It looks like a pretty important issue to remain open for so long. Most applications are using / will require localization and google sign in.

**Comment by felixwortmann** [comment]
@ditman can you look into this?

**Comment by tmatrai** [comment]
Do you have any info about it? It blocks my flutter web project for a while. Thanks a lot!

**Comment by ditman** [comment]
```
[...] firebase_auth ^0.20.0+1 is incompatible with flutter_localizations from sdk.
```

There's a big change coming in the flutter sdk that is rolling some dependencies up (as many have reported above in the thread).

Has anybody tried using the nullsafety versions of the firebase plugins? Those should roll dependencies forward to stay in sync with the framework sdk in beta:

```
firebase_auth: ^0.21.0-nullsafety.0
```

_Note that because of how Dart versioning works: `^0.16.0` will **not** pick up `0.17.0`. That is considered a major version bump. However: `^1.16.0` **will** pick up `1.17.0`. Dart uses the first non-zero value as the major version, not the value at the left of the first dot!_

**Comment by felixwortmann** [comment]
@ditman thanks for looking into it.
I just tried updating all my firebase dependencies to the null safety versions (because they depend on `firebase_core` and updating one of them would cause problems)

So I got some conflicts with the current versions of the plugins, for example `cloud_firestore 0.17.0-1.0.nullsafety.1` is not compatible with `firebase_auth 0.21.0-nullsafety.0` (both latest prerelease). This is the error message:
```
Because firebase_auth >=0.21.0-nullsafety.0 depends on firebase_core_platform_interface ^4.0.0-nullsafety.0 and cloud_firestore >=0.17.0-1.0.nullsafety.1 depends on firebase_core_platform_interface >=4.0.0-1.0.nullsafety.1 <4.0.0-2.0.nullsafety.0, firebase_auth >=0.21.0-nullsafety.0 is incompatible with cloud_firestore >=0.17.0-1.0.nullsafety.1.
```
<br>
Also `cloud_functions: 0.9.1-nullsafety.1` is incompatible with `firebase_auth: 0.21.0-nullsafety.0`

```
Because cloud_functions >=0.9.1-nullsafety.0 depends on firebase_core_platform_interface ^3.0.2-nullsafety.0 and firebase_core >=0.8.0-nullsafety.1 depends on firebase_core_platform_interface ^4.0.0-nullsafety.0, cloud_functions >=0.9.1-nullsafety.0 is incompatible with firebase_core >=0.8.0-nullsafety.1.
```

<br>
There are probably a lot more issues with the null safety firebase plugins since I do not use all of them and just checked it briefly. If they were already released, I would write `any` for all versions and see if it comes up with a solution (which it probably won't, but worth a shot). Is there a way to do this while including the prerelease versions?

<br>
I actually ask myself why there are not more people on this issue because it seems to affect pretty much every flutter web dev who uses the flutterfire plugins.

**Comment by ditman** [comment]
Maybe you need to be more strict on the versions of your dependencies? Observe here how everything package is pretty much pinned to a single version of its dependencies; maybe you need to do something similar:

https://github.com/FirebaseExtended/flutterfire/pull/4926/files

Once the "-nullsafety" suffix goes away, I'm guessing everything is going to go back to normal, where dependencies may float more freely!

_PS: I'm sorry I can't be of more help, I haven't touched this repo in a while!_

**Comment by felixwortmann** [comment]
@ditman do you know where I can find versions of all the plugins that are compatible? Or do I have to try it out / reverse engineer that? <br><br>
Also do you know the timeline for the null safety version release?

**Comment by felixwortmann** [comment]
Just a small update since the `1.0.*-nullsafety` versions of some plugins have been released: <br>
This issue still exists with `firebase_analytics ^7.0.1` (which does not support nullSafety yet)
```
firebase_analytics ^7.0.1 which depends on firebase_core ^0.7.0, firebase_core ^0.7.0 is required
```
If I do not use `firebase_analytics` and just the plugins with the `1.0.*-nullsafety`  versions, I still get an error:
```
Because cloud_functions >=1.0.0-1.0.nullsafety.0 depends on cloud_functions_web >=3.1.4-1.0.nullsafety.2 <3.1.4-2.0.nullsafety.0 which depends on firebase_core >=0.8.0-1.0.nullsafety.2 <0.8.0-2.0.nullsafety.0, cloud_functions >=1.0.0-1.0.nullsafety.0 requires firebase_core >=0.8.0-1.0.nullsafety.2 <0.8.0-2.0.nullsafety.0.
```
<br>
So overall it seems like there are still issues with the dependency versions. Hopefully they will be fixed soon.

**Comment by felixwortmann** [comment]
@talhakosen I think this can be closed. With the new stable flutter version and the new versions of all the plugins, everything works again.

**Comment by ditman** [comment]
Let's close this. There's a section in the [Migration Guide](https://firebase.flutter.dev/docs/migration/) of the Flutterfire docs that suggests a set of versions. I'm going to copy-paste here for now (valid as of the original posting of this message: March 8th, 2021):


Plugin | Version
-- | --
cloud_firestore | ^0.16.0+1
cloud_functions | ^0.9.0
firebase_auth | ^0.20.1
firebase_core | ^0.7.0
firebase_crashlytics | ^0.4.0+1
firebase_storage | ^7.0.0
firebase_messaging | ^8.0.0-dev.15
firebase_remote_config | ^0.8.0-dev.0
