### ISSUE TITLE
In Flutter Firebase crashlytics  report stack trace it only shows crash in dart file not shows the dart file name,location and line where crash occur

### ISSUE THREAD

**Issue by jigarparmar21** [FirebaseExtended/flutterfire#4074]
![Screenshot 2020-11-10 at 10 20 46 AM](https://user-images.githubusercontent.com/59466922/98630747-d8147d80-2341-11eb-8aa7-79599b5f139d.png)

**Comment by markusaksli-nc** [comment]
Hi @jigarparmar21 
The native stack trace is to be expected and is documented as well (see https://github.com/FirebaseExtended/flutterfire/issues/3907#issuecomment-717808207)
Closing this issue, since it is not unexpected, as there cannot be a dart stack trace for a native fatal crash.
If you disagree please write in the comments and I will reopen.
Thank you

**Comment by jigarparmar21** [comment]
Is crashlystics possible in flutter for both fatal and non-fatal exception ?

**Comment by markusaksli-nc** [comment]
Yes, please take a look at the [official example](https://pub.dev/packages/firebase_crashlytics/example).
