### ISSUE TITLE
[firebase_ml_vision] Request for documentation for the following-

### ISSUE THREAD

**Issue by ArnavBansal11** [FirebaseExtended/flutterfire#4087]
Please describe your documentation issue or suggested improvement in detail here and provide links to any pre-existing/relevant documentation and screenshots if necessary:

Hi,
I would appreciate it if documentation for the following could be added-
1) Firebase Face detection/Text Recognistion on the Cloud
2) Using custom models that we uploaded to the firebase console (I heard this could be done using the ImageLabeler but not sure how)

Thanks

**Comment by tperm94** [comment]
hey @darshankawar can you help with my issue if possible?
Thanks

**Comment by Salakar** [comment]
Hey, :wave:, the `firebase_ml_vision` package is now discontinued since its APIs have been deprecated and removed from the Android & iOS Firebase SDKs.

I'd recommend switching to the alternatives now;

 - **for on-device vision APIs**; switch to Google's standalone ML Kit library via [google_ml_kit](https://pub.dev/packages/google_ml_kit)
 - **for cloud vision APIs**; the recommended approach now is to use Firebase
Authentication and Functions, which gives you a managed, serverless gateway to the Google Cloud Vision APIs. For an example Functions project see the [vision-annotate-images](https://github.com/firebase/functions-samples/tree/master/vision-annotate-images) sample project. You'd deploy this project for example and then call the cloud function from your app with your image data to get the annotation result.

Apologies for any inconvenience here and best of luck switching over the the new APIs. `firebase_ml_custom` is not affected by this deprecation.

Thanks
