### ISSUE TITLE
CLOUD_FIRESTORE error. 

### ISSUE THREAD

**Issue by PartapSBimrah** [FirebaseExtended/flutterfire#4104]
I have an error while running the app to a physical device. Please see the screenshot and let me know the solution. I'm getting this error last two weeks. Please 🙏 I am using both android studio and vs code. But the problem is the same. ![98801717-39b71380-2438-11eb-95c1-b2d1ad85b6c2.png](https://user-images.githubusercontent.com/39325207/98902505-de3e6180-24db-11eb-800c-d883d85c7f63.png)

**Comment by markusaksli-nc** [comment]
Hi @PartapSBimrah 
Could you please provide your `flutter doctor -v` and `flutter pub deps -- --style=compact`?
What verion of Gradle are you using to build the project?
Thank you

**Comment by PartapSBimrah** [comment]
Latest Gradle am using.  This is my latest` flutter doctor -v `command output
![Screenshot (311)](https://user-images.githubusercontent.com/39325207/98943928-3e51f980-2516-11eb-822e-9d49aa247c2e.png)

**Comment by markusaksli-nc** [comment]
Could you provide the exact gradle version in your `android/build.gradle`?

**Comment by PartapSBimrah** [comment]
Am using `Gradle version 6.5` see in this screenshot.

![Screenshot (313)](https://user-images.githubusercontent.com/39325207/99135001-3b562680-2646-11eb-80d3-e74cbb6a3aee.png)

**Comment by markusaksli-nc** [comment]
This error will show up due to a package visibility change in Android 11. There were updates for the Android Gradle plugin to remedy this but there should be no problem with the 4.1.1 version (see [this blogpost](https://android-developers.googleblog.com/2020/07/preparing-your-build-for-package-visibility-in-android-11.html) for more).

Are you sure `cloud_firestore` is causing this? Seems like an issue with your gradle environment.

**Comment by PartapSBimrah** [comment]
Everything sorted out now.

**Comment by markusaksli-nc** [comment]
Thank you

Closing this as solved based on your last comment.

**Comment by PartapSBimrah** [comment]
Yes you can close this case.
