### ISSUE TITLE
🐛 [firebase_messaging] {"message":"Internal Server Error","error":"SenderId mismatch"} 

### ISSUE THREAD

**Issue by daebak** [FirebaseExtended/flutterfire#4611]
I have compiled the following project with a sample.
Project path: ..\flutterfire\packages\firebase_messaging\firebase_messaging\example
Normal sample works normally.

Next, when the google-services.json file is changed to mine, if the following error occurs, the message will not be sent.

Please tell me how to fix it

source

 final response = await http.post(
    'https://api.rnfirebase.io/messaging/send',
    headers: <String, String>{
      'Content-Type':'application/json; charset=UTF-8',
    },
    body: constructFCMPayload(_token),
  );
  print(response.request.headers.values.toString()+response.body);
  print('FCM request for device sent!');
log (response)
{"message":"Internal Server Error","error":"SenderId mismatch"}

**Comment by markusaksli-nc** [comment]
The post address is only meant to be used with the sample project.

To change it you need to take a look at https://firebase.google.com/docs/cloud-messaging/server and start figuring out your implementation from there.

If you just want to edit the official example and make it work you can replace with this
```
      final response = await http.post(
        'https://fcm.googleapis.com/v1/projects/myproject-b5ae1/messages:send',
        headers: <String, String>{
          'Content-Type': 'application/json; charset=UTF-8',
          'Authorization': 'Bearer ya29.ElqKBGN2Ri_Uz...HnS_uNreA'
        },
        body: constructFCMPayload(_token),
      );
```
`myproject-b5ae1` needs to be replaced with your firebase project ID. Then you need to add a proper authorization to the headers array (see https://firebase.google.com/docs/cloud-messaging/migrate-v1#update-authorization-of-send-requests).

Closing since this isn't a problem with the plugin itself. If you have any more trouble please feel free to seek help in the community https://stackoverflow.com/tags/flutter https://www.reddit.com/r/FlutterDev/.
