### ISSUE TITLE
🐛 [firebase_messaging] Failed assertion: line 481 pos 16: '_displacementTickerLastElapsed == null': is not true. overscroll_indicator.dart

### ISSUE THREAD

**Issue by GilbertoGmobil** [FirebaseExtended/flutterfire#4768]
In my flutter App i'm implementing FCM and local Notifications for some users. But now i'm facing an error which throws every time I go to phone's main screen ( When I put the app in background) :

```console
======== Exception caught by gesture ===============================================================
The following assertion was thrown while handling a gesture:
'package:flutter/src/widgets/overscroll_indicator.dart': Failed assertion: line 481 pos 16: '_displacementTickerLastElapsed == null': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack: 
#2      _GlowController.pull (package:flutter/src/widgets/overscroll_indicator.dart:481:16)
#3      _GlowingOverscrollIndicatorState._handleScrollNotification (package:flutter/src/widgets/overscroll_indicator.dart:304:28)
#4      NotificationListener._dispatch (package:flutter/src/widgets/notification_listener.dart:133:41)
#5      Notification.visitAncestor (package:flutter/src/widgets/notification_listener.dart:49:20)
#6      ViewportNotificationMixin.visitAncestor (package:flutter/src/widgets/scroll_notification.dart:33:18)
...
Handler: "onUpdate"
Recognizer: VerticalDragGestureRecognizer#a057b
  start behavior: start
```

This is my main function:
```dart
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  SharedPreferences.setMockInitialValues({});
  await SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
    DeviceOrientation.portraitDown,
  ]);

  await Hive.initFlutter();

  await Firebase.initializeApp();
  await PushNotificationsManager().init();

  runApp(MyApp());
}
```

I'm using firebase_messaging 8.0.0 dev-14.
How to handle that? Why is this happening?

**Comment by markusaksli-nc** [comment]
Hi @GilbertoGmobil 
Are you sure this is being caused by the `firebase_messaging` plugin? It seems like a part of the app layout is throwing this error so we would need a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) if that is the case.
Have you opened an issue in https://github.com/flutter/flutter/issues/new?template=BUG.md already or was this clearly caused **only due to implementing `firebase_messaging`** so you filed it here?
Thank you

**Comment by markusaksli-nc** [comment]
In that case we would need a full [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) to diagnose this. This is throwing a layout error so the layout is important. Try to strip out as much of the code as you can while still seeing if the issue is there.

Could you also provide your `flutter doctor -v` and `flutter pub deps -- --style=compact`?
