### ISSUE TITLE
🐛 [PLUGIN_NAME_HERE] Unable to instantiate activity ComponentInfo

### ISSUE THREAD

**Issue by contactlutforrahman** [FirebaseExtended/flutterfire#4819]
## Bug report

**After I've create the Application.java file, at the same location where MainActivity.java is located, I'm getting the bellow error**

E/AndroidRuntime(20099): Caused by: java.lang.ClassCastException: com.example.app.Application cannot be cast to android.app.Activity
E/AndroidRuntime(20099): 	at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
E/AndroidRuntime(20099): 	at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:45)
E/AndroidRuntime(20099): 	at android.app.Instrumentation.newActivity(Instrumentation.java:1253)
E/AndroidRuntime(20099): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3353)
E/AndroidRuntime(20099): 	... 11 more

**Comment by markusaksli-nc** [comment]
Hi @contactlutforrahman 
Please just use the latest `firebase_messaging: ^8.0.0-dev.14` so you don't have to use the `Application.java` hack.
Follow the official documentation at https://firebase.flutter.dev/docs/overview and https://firebase.flutter.dev/docs/messaging/overview
Closing since the issue provides none of the info in the template.
Thank you
