### ISSUE TITLE
firebase_messaging - update dependency needed

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [FirebaseExtended/flutterfire#4900]
Hello,

i get this error when trying to use firebase_messaging latest with firebase_auth plugin

Because firebase_messaging >=7.0.3 <8.0.0-dev.7 depends on firebase_core ^0.5.0+1 and firebase_auth >=0.20.0 <0.21.0-1.0.nullsafety.0 depends on firebase_core ^0.7.0, firebase_messaging >=7.0.3 <8.0.0-dev.7 is incompatible with firebase_auth >=0.20.0 <0.21.0-1.0.nullsafety.0.

firebase_core needs to be updated

**Comment by markusaksli-nc** [comment]
Hi @vytautas-pranskunas- 
You are getting this message because you cannot mix and match the firebase plugin versions after the recent updates to the minimum ios constraint. You should use all of the latest versions for the plugins (you dont need to use nullsafety).

Upgrading to the latest `firebase_messaging: ^8.0.0-dev.14` should fix the issue for you.

Closing since this isn't an issue with the plugins themselves and the versioning is described in the error message itself.
Thank you
