### ISSUE TITLE
🐛 [firebase_messaging] Updated migration guide contains messaging 7.0.3 causing incompatibility

### ISSUE THREAD

**Issue by pratikbutani** [FirebaseExtended/flutterfire#4955]
## flutter_core is not working with firebase_remote_config and firebase_messaging together for version given in the migration guide.

**Describe the bug**
I want to use **firebase_messaging** and **firebase_remote_config** together. But It has conflicts with **firebase_core**.

## Additional context
**Working Perfect When:**

    firebase_core: ^0.5.0+1
    firebase_messaging: ^7.0.3

Problem Occurs When I add **firebase_remote_config**:

    firebase_remote_config: ^0.6.0

**Getting Error:**

> Because firebase_remote_config >=0.6.0 depends on firebase_core ^0.7.0
> and flutter_app depends on firebase_core ^0.5.0+1,
> firebase_remote_config >=0.6.0 is forbidden. So, because flutter_app
> depends on firebase_remote_config ^0.6.0, version solving failed.

and If I change the version of the **firebase_core** to the latest, It's giving me the same error for **firebase_messaging**

I had given versions same as [migration][1] guide but not working.

Can anyone help, please?

**Comment by markusaksli-nc** [comment]
Hi @pratikbutani 
The latest versions of the firebase plugins are not compatible with older ones because of an update to the underlying iOS SDK constraints. You need to use either the latest non-nullsafety version `firebase_messaging: ^8.0.0-dev.14` or the latest version `^9.0.0-1.0.nullsafety.0`

Looks like when https://github.com/FirebaseExtended/flutterfire/issues/4885 got fixed we now have this issue instead.

**Comment by GrahamDi** [comment]
Same problem here. Migration guide still incorrect. I am getting:
`Because firebase_messaging 7.0.3 depends on firebase_core ^0.5.0+1 and no versions of firebase_messaging match >7.0.3 <8.0.0, firebase_messaging ^7.0.3 requires firebase_core ^0.5.0+1.`

**Comment by markusaksli-nc** [comment]
I'm pretty sure this also caused an issue where the old messaging version is mentioned here https://firebase.flutter.dev/docs/messaging/overview/ but it really shouldn't be.

**Comment by GrahamDi** [comment]
@markusaksli-nc 
Sorry I am unclear what the resolution is here.
You have closed the issue, so are you saying it will now work as per your migration guide, or should I just give up trying to  upgrade the Flutterfire packages?

**Comment by syonip** [comment]
> @markusaksli-nc
> Sorry I am unclear what the resolution is here.
> You have closed the issue, so are you saying it will now work as per your migration guide, or should I just give up trying to upgrade the Flutterfire packages?

I think #4887 is closed but this issue is still open.
I also had this issue, the migration guide needs to be updated to have messaging version ^8.0.0-dev.14

**Comment by markusaksli-nc** [comment]
@GrahamDi https://github.com/FirebaseExtended/flutterfire/issues/4887 was closed since it was ultimately solved.

As I already said before this issue was as a result of https://github.com/FirebaseExtended/flutterfire/issues/4885 getting fixed. Instead of including the latest non-nullsafety version `8.0.0-dev.14` it changed to the old `7.0.3` version.

The resolution is to just use the `8.0.0-dev.14` version instead of the mentioned wrong version. This issue is open to track that the wrong version is mentioned in the migration guide and the messaging installation guide.

**Comment by russellwheatley** [comment]
Neither the migration guide nor the installation guide for messaging reference the incorrect version (`7.0.3`) anymore so I'm going to go ahead and close this.
