### ISSUE TITLE
Firebase Messaging: FlutterFcmService: failed to find callback

### ISSUE THREAD

**Issue by jimmyff** [FirebaseExtended/flutterfire#5151]
Hi, I've found so many people with this issue on stack overflow and github but I'm unable to find a solution. It seems like most people were trying to do background notifications or the topics were closed/locked when the pub package was revamped. I'm using firebase_messaging: 7.0.3.

I am not attempting to receive background notifications at this stage, I skipped those optional instructions on the installation guide and I haven't specified an `onBackgroundMessage` handler.

My app receives push notifications fine, however when I click on it I get the following error:
```
E/FlutterFcmService(20860): Fatal: failed to find callback
```
My app opens but does not trigger the callbacks as specified in my `_firebaseMessaging.configure(...`

Doctor output:
- Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version
    10.0.19042.804], locale en-GB)
- VS Code, 64-bit edition (version 1.52.1)
- firebase_messaging: 7.0.3
- flutterEmbedding v2

I have followed all the installation instructions and I do have the following intent in my AndroidManifest, (I also tried it without as I was confused by the seemingly contradictory instructions on the [migration guide](https://github.com/FirebaseExtended/flutterfire/issues/5150)).
```
      <intent-filter>
        <action android:name="FLUTTER_NOTIFICATION_CLICK" />
        <category android:name="android.intent.category.DEFAULT" />
      </intent-filter>
```

**Comment by markusaksli-nc** [comment]
Hi @jimmyff 
These issues have been closed/locked due to the non-nullsafety prerelease version pretty much fixing all of them. The migration guide has the wrong old stable version due to a documentation bug https://github.com/FirebaseExtended/flutterfire/issues/4955
All of the native workarounds are no longer necessary and the plugin is more reliable and stable in general. Please switch to the latest `firebase_messaging: ^8.0.0-dev.14` (which does not need any native workarounds and works out-of-the-box).
Thank you
