### ISSUE TITLE
🐛 firebase_auth Same as Closed issue #1925

### ISSUE THREAD

**Issue by kushalgoel786** [FirebaseExtended/flutterfire#5160]
## Bug report

Pretty much the same as Closed Issue #1925. 

The issue is closed, but the problem still persists. 

Steps to reproduce and all the details are same

**Comment by markusaksli-nc** [comment]
Hi @kushalgoel786 
If the details are all the same then please switch to the latest `firebase_auth: ^0.20.1` since the plugin has been heavily reworked.

When opening an issue, please try to provide all of the information indicated in the template.
Closing this issue, since no information has been provided.
Thank you.
