### ISSUE TITLE
[📚] iOS setup is not complete - Will not work

### ISSUE THREAD

**Issue by sp00ne** [FirebaseExtended/flutterfire#5237]
Follow the directions on [Getting Started - iOS Installation](https://firebase.flutter.dev/docs/installation/ios) will not yield a working setup. It is missing hooking up the URL schemes. 

I.e [Add a URL schema to your project](https://developers.google.com/identity/sign-in/ios/start-integrating#add_a_url_scheme_to_your_project)

Ignoring this step will thrown an error for iOS in the format: 

```
Your app is missing support for the following URL schemes: ***
```

**Comment by markusaksli-nc** [comment]
This page is just for general setup that is needed for all the firebase packages. For all of the other packages there are separate more detailed instructions.

Not sure what missing scheme you are referring to?

**Comment by sp00ne** [comment]
Yeah but that general setup does not work for iOS. The error message that is outputted is what is shown and the link to the URL schema I refer to is given above, 

I am not sure what else to tell you?

The instructions are not complete. If we follow these we will not have a working for at least one of the firebase packages. So either the information architecture of the docs are need of improvement or the docs are missing info.

**Comment by markusaksli-nc** [comment]
As I already mentioned the page you referenced is regarding to general setup for firebase packages. Even if the issue was about firebase packages then you would have to mention which specific package documentation is missing this step instead of the general setup.

However, the missing URL you referred to is for `google_sign_in` and is already documented on the package readme https://pub.dev/packages/google_sign_in#ios-integration

Closing this since there is nothing for us to fix here.
