### ISSUE TITLE
🐛 [firebase_auth] Reauthenticating a user

### ISSUE THREAD

**Issue by tonujewel** [FirebaseExtended/flutterfire#5346]
## Bug report

**Describe the bug**
I am working on a project which based on firebase authentication (email/password). 
Then i want change password. But [Reauthenticating a user ](https://firebase.flutter.dev/docs/auth/usage#reauthenticating-a-user)  Not working  . It showing "The password is invalid or the user does not have a password."

<img width="1153" alt="Screenshot 2021-03-14 at 11 52 32 PM" src="https://user-images.githubusercontent.com/23281909/111080007-a9dcbf80-8526-11eb-96f8-30806c63bdc7.png">

> My code

```
  FirebaseAuth auth = FirebaseAuth.instance;

  checkUser() {
    if (auth.currentUser != null) {
      print(auth.currentUser.email);
      changePass();
    } else {
      print("user not found");
    }
  }

  void changePass() async {
    EmailAuthCredential credential =
        EmailAuthProvider.credential(email: auth.currentUser.email, password: "Password@3221");

    await auth.currentUser.reauthenticateWithCredential(credential);
  }

```

### Flutter doctor 

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.0, on macOS 11.2.1 20D74 darwin-arm, locale en-BD)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.54.1)
[✓] Connected device (3 available)

• No issues found!

```

---

### Flutter dependencies

```
  # Firebase auth
  firebase_auth: ^0.20.0+1
  # Firebase cloud store
  cloud_firestore: ^0.16.0
```

---

**Comment by markusaksli-nc** [comment]
Hi @tonujewel 
Does the issue persist if you use the latest version `firebase_auth: ^1.0.1`?
Thank you

**Comment by tonujewel** [comment]
> Hi @tonujewel
> Does the issue persist if you use the latest version `firebase_auth: ^1.0.1`?
> Thank you

Yes

**Comment by markusaksli-nc** [comment]
Now that I read your code a bit more are you expecting the reauthentication flow itself to change the password so you provide a new password there? Because that is not what it does and not what the documentation says it does. As mentioned in the documentation this method simply provides you with a new `AuthCredential` with your exisiting login credentials **without logging you out and back in again**.

This is only a step required to be done before you can do something like changing the password. To change the password itself you need to use `user.updatePassword(newPassword)`.

Let me know if this was not your issue.
