### ISSUE TITLE
GoogleDataTransport Issue

### ISSUE THREAD

**Issue by hennonoman** [FirebaseExtended/flutterfire#5665]
I tried to upload toe the apple store but I got this error:

<img width="705" alt="Screen Shot 1442-08-23 at 1 25 48 PM" src="https://user-images.githubusercontent.com/25689733/113577424-ebdeba00-9629-11eb-9cf2-fd8156e2718a.png">

**Comment by darshankawar** [comment]
@hennonoman 
I am not sure if this issue is specific to FlutterFire, but with your Xcode setup and config. I suggest you ask this question on support channels like StackOverflow to get help on.  See [this](https://stackoverflow.com/questions/46751712/no-suitable-application-records-were-found-verify-your-bundle-identifier-org-c) similar SO link and check if any of the underlying comments helps to resolve this.

I am going ahead and closing this as not specific to Flutterfire. If you disagree, write in comments and I'll reopen it.
Thanks.
