### ISSUE TITLE
Flutter FCM iOS Issue - APNS device token not set before retrieving FCM Token

### ISSUE THREAD

**Issue by karthikeyanp307** [FirebaseExtended/flutterfire#5687]
Hi Team,

I am using firebase_messaging v9.0.1 in my Flutter application. On configuring this library based on the https://pub.dev/packages/firebase_messaging/example, I am able to receive the notification for android in both foreground and background states. But the same for iOS is not working. I am getting the below error,

APNS device token not set before retrieving FCM Token for Sender ID ''. Notifications to this FCM Token will not be delivered over APNS.Be sure to re-retrieve the FCM token once the APNS device token is set.
My iOS device is connected to internet and there were no network related issues while running this.

Do I want to call any other function apart from FirebaseMessaging.instance.getToken() for iOS? Please help.

Thanks.

**Comment by darshankawar** [comment]
@karthikeyanp307 
I believe this is the same issue as you reported earlier, https://github.com/FirebaseExtended/flutterfire/issues/5529.
I suggest you to update the original issue with your latest findings, because I think you are now getting a different error than it was reported in 5529. You may update the original issue and let's track it there, instead of opening duplicate issue.

Closing this as self-duplicate.
