### ISSUE TITLE
Support for notifications to terminated app in iOS

### ISSUE THREAD

**Issue by andreaslans** [FirebaseExtended/flutterfire#5695]
We are building an app where notifications are extremly important and have just now realized that a lot of users are having problems with the fact that they are swiping to close all apps. 

We have reread the documentation and found this:
```
On iOS, if the user swipes away the application from app Switcher, it must be manually reopened again for background messages to start working again.

```
We are now unsure as the meaning of this. 

Are we to conclude that we cannot receive any notifications at all if the user has forced closed the app? Or is it just that we cant handle the notification in the app and that it should be added to the notification drawer inside the phones operating system?

**Comment by darshankawar** [comment]
@andreaslans 
There are couple of open issues reported regarding notifications not triggering when app is terminated / killed or in background or sometimes fails silently. 

https://github.com/FirebaseExtended/flutterfire/issues/2854
https://github.com/FirebaseExtended/flutterfire/issues/2603 

> Are we to conclude that we cannot receive any notifications at all if the user has forced closed the app?

This may not be an expected behavior, and in ideal scenario, the notifications should be triggered / displayed even if app is forced closed or killed, atleast the above referred issues indicate the same.

Please see above issues and confirm if either of them resemble your scenario, so that you may track your query in respective issue.

**Comment by Salakar** [comment]
> Are we to conclude that we cannot receive any notifications at all if the user has forced closed the app?

Correct, see https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1623013-application, specifically: 

> In addition, if you enabled the remote notifications background mode, the system launches your app (or wakes it from the suspended state) and puts it in the background state when a remote notification arrives. **However, the system does not automatically launch your app if the user has force-quit it. In that situation, the user must relaunch your app or restart the device before the system attempts to launch your app automatically again.**
