### ISSUE TITLE
🐛 [firebase_performance] why there is no null-safe label is it null-safe?

### ISSUE THREAD

**Issue by uc-dve** [FirebaseExtended/flutterfire#5696]
[firebase_performance] why there is no null-safe label. is it null-safe?

**Comment by darshankawar** [comment]
@uc-dve 
There's an active open PR to address this issue, https://github.com/FirebaseExtended/flutterfire/pull/5540.
Please follow-up or subscribe to it to get latest updates. Once it is merged, you'll see the `null-safe` label for the plugin.

I am going ahead and closing this, since there's open PR which will be merged soon.
