### ISSUE TITLE
[cloud_firestore] Retrieve displayName and photoUrl of other users without Firestore

### ISSUE THREAD

**Issue by Golax** [FirebaseExtended/flutterfire#59]
Hi!
Just a quick question that came to my mind. Firebase stores displayName and photoUrl of the users in a different "database" that is inaccessible for other users (only the current user can retrieve his data); for this reason, I have to store for example the user's photo in Firestore with his uid. In this way, the photo is stored 2 times and it's not very handy because it needs a separate collection etc.
Is there a better approach to this problem or you think this could be implemented in future updates? Greetings.

**Comment by Ehesp** [comment]
Hello - this is by design in Firebase. A database (Firestore or Database) should be used to store metadata not available with the authentication plugin.

I'll close this, however you may wish to raise a feature request with Firebase: https://firebase.google.com/support/troubleshooter/report/features/
