### ISSUE TITLE
What kind of value pass to isSignInWithEmailLink(String value) in firebase

### ISSUE THREAD

**Issue by ChkBuk** [FirebaseExtended/flutterfire#5913]
When I implement firebase signInemaillink authentication, auth.isSignInWithEmailLink() is always false. my

```
actionCodeSettings: ActionCodeSettings(
        url: 'https://mydomain.page.link/test',
        androidPackageName: 'com.mydomain.mob.firebase_login',
        handleCodeInApp: true,
        androidMinimumVersion: '16',
        androidInstallApp: true
      )
```
and

print(link) ==> https://mydomain.page.link.com
auth.isSignInWithEmailLink(String link)
However, I noticed that implementation of isSignInWithEmailLink is as follows,

```
bool isSignInWithEmailLink(String emailLink) {
    assert(emailLink != null);
    return (emailLink.contains('mode=signIn') ||
            emailLink.contains('mode%3DsignIn')) &&
        (emailLink.contains('oobCode=') || emailLink.contains('oobCode%3D'));
  }
```
even though the link in the my email contains 'mode=signIn' and 'oobCode=', isSignInWithEmailLink() get always 'false' as it receives link as 'https://mydomain.page.link.com'

Anybody can help me to solve this issue?

**Comment by markusaksli-nc** [comment]
Hi @ChkBuk 
This issue was already fixed https://github.com/FirebaseExtended/flutterfire/issues/4711
However this could also be caused by not having an intent filter for the link. https://github.com/FirebaseExtended/flutterfire/issues/5530
Please use the latest version of the package and make sure you have an intent filter for your dynamic links.
Thank you
