### ISSUE TITLE
🐛 [firebase_database] pub get failed (66; Because firebase_database_example depends on firebase_core from path

### ISSUE THREAD

**Issue by heinzan** [FirebaseExtended/flutterfire#6064]
Running "flutter pub get" in example...
Because firebase_database_example depends on firebase_core from path which doesn't exist (could not find package firebase_core at "../../firebase_core/firebase_core"), version solving failed.
pub get failed (66; Because firebase_database_example depends on firebase_core from path which doesn't exist (could not find package firebase_core at "../../firebase_core/firebase_core"), version solving failed.)

This is plugin
  firebase_core: 1.1.0
  firebase_auth: ^1.1.3
  firebase_database: ^6.1.2

This is flutter doctor
[✓] Flutter (Channel stable, 2.0.6, on macOS 11.2.3 20D91 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] Connected device (2 available)

I cann't run app.I clear cache and restart ide cann't solve

**Comment by markusaksli-nc** [comment]
Hi @heinzan 
When you attempt to use the entire official example project you will need the entire repository since firebase packages are depended on with paths.
Please either just use the example code in your own project or replace the path refs with the pub versions (such as `firebase_core: ^1.1.0`)
Thank you
