### ISSUE TITLE
Can't build "on device" textrecognizer or barcodescanner

### ISSUE THREAD

**Issue by arrrrny** [FirebaseExtended/flutterfire#6081]
below is my result from pod install. I tried everything to clear pod, repo updates all same. 
Please update Firebase/CoreOnly dependency of these 2 on device models. to newer

  pod 'Firebase/MLVisionBarcodeModel'
  pod 'Firebase/MLVisionTextModel'

firebase_ml_vision: Using Firebase SDK version '7.11.0' defined in 'firebase_core'
firebase_storage: Using Firebase SDK version '7.11.0' defined in 'firebase_core'
[!] CocoaPods could not find compatible versions for pod "Firebase/CoreOnly":
  In Podfile:
```
    Firebase/MLVisionTextModel was resolved to 5.0.0, which depends on
      Firebase/CoreOnly (= 5.0.0)
    firebase_core (from `.symlinks/plugins/firebase_core/ios`) was resolved to 1.1.0, which depends on
      Firebase/CoreOnly (= 7.11.0)
````

**Comment by Salakar** [comment]
Hey all, :wave:, the `firebase_ml_vision` package is now discontinued since its APIs have been deprecated and removed from the Android & iOS Firebase SDKs.

I'd recommend switching to the alternatives now;

 - **for on-device vision APIs**; switch to Google's standalone ML Kit library via [google_ml_kit](https://pub.dev/packages/google_ml_kit)
 - **for cloud vision APIs**; the recommended approach now is to use Firebase
Authentication and Functions, which gives you a managed, serverless gateway to the Google Cloud Vision APIs. For an example Functions project see the [vision-annotate-images](https://github.com/firebase/functions-samples/tree/master/vision-annotate-images) sample project. You'd deploy this project for example and then call the cloud function from your app with your image data to get the annotation result.

Apologies for any inconvenience here and best of luck switching over the the new APIs. `firebase_ml_custom` is not affected by this deprecation.

Thanks
