### ISSUE TITLE
QR Code not scanning

### ISSUE THREAD

**Issue by sooraj-beebakhy** [FirebaseExtended/flutterfire#6098]
Hello, am using flutter to scan a QR code.

The following plugin is integrated in the App: 
https://pub.dev/packages/flutter_camera_ml_vision
https://pub.dev/packages/firebase_ml_vision

But it can't scan the code. Attach is the example of the QR code not scanning:
![qrcode](https://user-images.githubusercontent.com/5858364/117658798-395fc100-b1ac-11eb-941e-b9e82d0fd153.png)

Waiting for your reply.

Regards, 
Sooraj

**Comment by Salakar** [comment]
Hey, :wave:, the `firebase_ml_vision` package is now discontinued since its APIs have been deprecated and removed from the Android & iOS Firebase SDKs.

I'd recommend switching to the alternatives now;

 - **for on-device vision APIs**; switch to Google's standalone ML Kit library via [google_ml_kit](https://pub.dev/packages/google_ml_kit)
 - **for cloud vision APIs**; the recommended approach now is to use Firebase
Authentication and Functions, which gives you a managed, serverless gateway to the Google Cloud Vision APIs. For an example Functions project see the [vision-annotate-images](https://github.com/firebase/functions-samples/tree/master/vision-annotate-images) sample project. You'd deploy this project for example and then call the cloud function from your app with your image data to get the annotation result.

Apologies for any inconvenience here and best of luck switching over the the new APIs. `firebase_ml_custom` is not affected by this deprecation.

Thanks
