### ISSUE TITLE
[firebase_storage] i can't upload file because => No App Check token for

### ISSUE THREAD

**Issue by Joseph-Nathan** [FirebaseExtended/flutterfire#6265]
No App Check token for request.
I got this massage when i try to upload pdf file ,
```
rules_version = '2';
service firebase.storage {
  match /b/{bucket}/o {
    match /{allPaths=**} {
      allow read, write;
    }
  }
}
```
when i used
```
firebase_app_check: ^0.0.1
```
as
```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();

  await FirebaseAppCheck.instance
      .activate();

  runApp(MyApp());
}
```
i got
```
Error getting App Check token; using placeholder token instead. Error: com.google.firebase.FirebaseException: 7:
```
note: in two cause file will upload but it was empty => 0kb

**Comment by darshankawar** [comment]
@Joseph-Nathan 
Can you provide `flutter doctor -v` and the platform on which you are trying to run app check ?

**Comment by Xordelish** [comment]
I had the same issue. I'm running on Flutter mobile

Here's my flutter doctor -v:

`C:\Users\JAN\AndroidStudioProjects\app1>flutter doctor -v
[√] Flutter (Channel stable, 2.2.2, on Microsoft Windows [Version 10.0.19041.1052], locale en-PH)
    • Flutter version 2.2.2 at C:\Flutter\flutter
    • Framework revision d79295af24 (5 days ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc3)
    • Android SDK at C:\Users\JAN\AppData\Local\Android\sdk
    • Platform android-30, build-tools 31.0.0-rc3
    • Java binary at: C:\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Users\JAN\AppData\Local\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\AndroidStudio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] Connected device (3 available)
    • Armor X5 Pro (mobile) • 3082SH2001018220 • android-arm64  • Android 10 (API 29)
    • Chrome (web)          • chrome           • web-javascript • Google Chrome 91.0.4472.106
    • Edge (web)            • edge             • web-javascript • Microsoft Edge 91.0.864.48

• No issues found!

C:\Users\JAN\AndroidStudioProjects\app1>
`



I am new to development and I just wanted to upload image to firebase storage but that exception is always thrown. Currently, the documentation on FlutterFire for App Check only shows this method for default provider. The rest is debug. But debugs won't work for me because I can't directly run MainActivity.java and IOS, I'm running in dart. I'm stuck atm. 

Check the documentation: https://firebase.flutter.dev/docs/app-check/usage/

**Comment by gautam-letzrent** [comment]
Any updates on this? Same issue here.
