### ISSUE TITLE
[firebase_admob] ios InterstitialAd listener not working

### ISSUE THREAD

**Issue by linbintie** [FirebaseExtended/flutterfire#63]
My app consists of BannerAd and InterstitialAd. Whenever I initialise both type of ads, listener of InterstitialAd not responding, always intercept by BannerAd listener.

If interstitial ad is loaded:
BannerAd event is MobileAdEvent.loaded, expect InterstitialAd event is MobileAdEvent.loaded

If interstitial ad is clicked:
BannerAd event is MobileAdEvent.clicked, expect InterstitialAd event is MobileAdEvent.clicked

If interstitial ad is closed:
BannerAd event is MobileAdEvent.closed, expect InterstitialAd event is MobileAdEvent.closed

**Comment by linbintie** [comment]
same to this [issue](https://github.com/flutter/flutter/issues/27671#issue-407980963)

**Comment by linbintie** [comment]
this issue[https://github.com/flutter/flutter/issues/27520#issue-406584900](url) 
I think it is the same.

**Comment by edscodeblenders** [comment]
We're experiencing the same issue only on iOS. Works fine on Android. In our case, we create a banner, then an insterstitial. Banner callbacks are received by the interstitial listener. Please provide a fix asap.

**Comment by ThrowJojo** [comment]
Can also confirm having this issue on iOS

**Comment by marciorr** [comment]
This problem still persists.

**Comment by iapicca** [comment]
Hi all
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose` 
and your `pubspec.yaml` 
Thank you

**Comment by ThrowJojo** [comment]
Hey there @iapicca,

It turns out that this issue is actually related to https://github.com/FirebaseExtended/flutterfire/issues/1328 

It's not an issue with the underlying Flutter framework or setup. It's just how the plugin has been written(specifically the iOS/Objective-C native code). This is why there is only an issue on iOS and Android works fine. To summarize the above issue, `FLTMobileAd.m`(https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_admob/ios/Classes/FLTMobileAd.m#L13) isn't properly using member variables and because of it the static variables(maybe global is a better word in this case?) inside the class are basically being overwritten every time a new instance is created. 

If you still want me to run the doctor commands above I am happy to create a fresh project, add the AdMob plugin, run the commands and post the output here. The above issue will exist for basically any project that uses the AdMob plugin on iOS devices on any version of Flutter.

**Comment by blasten** [comment]
@bparrishMines to verify fix.

**Comment by blasten** [comment]
Potentially related to https://github.com/FirebaseExtended/flutterfire/issues/135

**Comment by russellwheatley** [comment]
The `firebase_admob` plugin will be deprecated in April 2021 in favor of [Google Mobile Ads SDK for Flutter](https://github.com/googleads/googleads-mobile-flutter).
Google Mobile Ads SDK for Flutter is a new Flutter plugin that supports more Ads formats than `firebase_admob` does. Google Mobile Ads SDK for Flutter currently supports loading and displaying banner, interstitial (full-screen), native ads, and rewarded video ads across AdMob and AdManager. It also supports displaying banner and native ads as `Widgets` as opposed to being overlayed over all app content.
We're now recommending projects currently using `firebase_admob` migrate to Google Mobile Ads SDK for Flutter following the [instructions outlined here](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_admob#migrating-to-google-mobile-ads-sdk-for-flutter).
Issues with migrating or with using the new package should now be raised over on the [Google Mobile Ads SDK for Flutter](https://github.com/googleads/googleads-mobile-flutter) repository.
