### ISSUE TITLE
Unable to either login with google or email and password using Firebase Auth on Flutter (with and without emulator)

### ISSUE THREAD

**Issue by TheMineWay** [FirebaseExtended/flutterfire#6486]
I read all the documentations but I'm still unable to resolve my problems.

I initialize the Firebase API:
`    await Firebase.initializeApp();

    // Auth
    auth = FirebaseAuth.instance;
    await auth.useEmulator("http://localhost:9099"); // <-- Setup AUTH emulator`

And when I try to login or register with email and password (using the code written below):
`      FirebaseAuth.instance.signInWithEmailAndPassword(
          email: loginEmail.text,
          password: loginPassword.text
      );`

I get this error:
**[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: [firebase_auth/unknown] com.google.firebase.FirebaseException: An internal error has occurred. [ Cleartext HTTP traffic to 10.0.2.2 not permitted ]**

And also when trying to login with Google (wich should be easy):
`    GoogleSignIn googleSignIn = new GoogleSignIn();
    await googleSignIn.signIn();`

I get this error:
**[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 10: , null, null)**

Hope to resolve this problem soon.

Thanks!

**Comment by darshankawar** [comment]
@TheMineWay 
According to [this](https://firebase.flutter.dev/docs/installation/android/#enabling-use-of-firebase-emulator-suite) documentation, you need to add `<application android:usesCleartextTraffic="true">` in your manifest file.

For `[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 10: , null, null)`, check this similar open issue and follow-up in it for further updates, https://github.com/flutter/flutter/issues/33393

I am going ahead and closing this, since adding the entry in manifest file should resolve your first issue.
If not still, write in comments and I'll reopen it.
