### ISSUE TITLE
🐛 [google_sign_in][firebase_auth] MissingPluginException(No implementation found for method init on channel plugins.flutter.io/google_sign_in)

### ISSUE THREAD

**Issue by jhlabs** [FirebaseExtended/flutterfire#6582]
I have exactly the same issue as detailed here https://github.com/FirebaseExtended/flutterfire/issues/5444#issue-839217332. I am not sure how the author @bwobst solved it as the issue was closed without any further comment, and I cannot comment on it. I have followed the instructions on integrating the Google Auth into a **macOS** step by step and am facing the exact same error. Thanks for your help.

**Comment by markusaksli-nc** [comment]
The reason you are getting this error message is that google_sign_in is not supported on macOS (https://github.com/flutter/flutter/issues/46157).

**Comment by jhlabs** [comment]
@markusaksli-nc I found that out now after debugging for hours. However, this is impossible to know from reading the documentation of Flutterfire if I didn't miss anything?

**Comment by markusaksli-nc** [comment]
Well google sign-in isn't really a part of FlutterFire since it can be used separately. Thus why it has it's own documentation on https://pub.dev/packages/google_sign_in

The missing platform method channel implementation error message is actually common for plugins when you try to use them on an unsupported platform but the message could be improved.

However, issues about google sign in belong on [flutter/flutter](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3A%22p%3A+google_sign_in%22)

**Comment by jhlabs** [comment]
Ok, thanks for your reply @markusaksli-nc!
