### ISSUE TITLE
🐛 [firebase_messaging]  Question regarding the setup documentation for app store apps

### ISSUE THREAD

**Issue by febg11** [FirebaseExtended/flutterfire#6632]
Hi

I have a question regarding the iOS setup of firebase messaging with flutter.

On the provisioning profile section in the documentation 

https://firebase.flutter.dev/docs/messaging/apple-integration/#3-generating-a-provisioning-profile

There is this section 

```
On the "Profiles" menu item, register a new Profile. Select the "iOS App Development" (or macOS) checkbox and click "Continue".

```

Now I have done this and my notifications are working fine on my device. However I noticed another type on the page when i was setting up the provisioning profile that was labelled "Distribution->App Store". 

I also noticed that the "iOS App Development" was also labelled with "Create a provisioning profile to install development apps on test devices." -> The test devices section concerns me a bit. 

![image](https://user-images.githubusercontent.com/50048162/125985498-542807e8-7a8b-475a-834a-ce40230cd298.png)

Do we actually have to make another provisioning profile using this "Distribution->App Store" type if we plan on releasing on the app store?

If so how do add it to my app instead of the development one

**Comment by markusaksli-nc** [comment]
Yes, you will need to build the app with a distribution profile in order to prepare to distribute the archived app. The provisioning profiles work like this:

- iOS App Development: for testing the app on a physical device while developing.
- Ad Hoc: for distributing the app to non-TestFlight testers (e.g. via HockeyApp).
- App Store: for distributing the app via TestFlight or the App Store. (Note that this one doesn't work on its own: your app will still need signing by Apple.)

However, this is more related to the use of Xcode and the iOS distribution steps rather than FlutterFire so I'm going to close the issue. If you have any more questions feel free to write on the Xcode forums or StackOverflow.
