### ISSUE TITLE
GoogleServices-Info.plist is imported but not locating

### ISSUE THREAD

**Issue by heeshala** [FirebaseExtended/flutterfire#6678]
Although it has been imported firebase can not be initialized

VS Code
![image](https://user-images.githubusercontent.com/50227550/126628319-8b3a128d-4d2b-4835-bfbf-c1e63f86b1ce.png)

Xcode
![image](https://user-images.githubusercontent.com/50227550/126628389-ce33eee7-86bd-4ab3-81c8-a7f825491f7a.png)

Info.plist
![image](https://user-images.githubusercontent.com/50227550/126628531-67321a69-8084-4192-abd5-6ec7b00905ac.png)

**Comment by KlemenAndrasic** [comment]
Put it into the the Runner folder and it should work

**Comment by markusaksli-nc** [comment]
Same advice as mentioned, also going to close this since it isn't a documentation issue. 

If you run into any more issues like this, please either seek help in the community or open up a bug report and fill out the template. If you are able to solve your issue and found that the documentation is wrong or lacking in some area you can open a new documentation bug report.

Thank you
