### ISSUE TITLE
terminated

### ISSUE THREAD

**Issue by srinivas-kodi** [FirebaseExtended/flutterfire#6783]

**Comment by darshankawar** [comment]
Please use the `new issue` template to fill the required details describing your issue. https://github.com/FirebaseExtended/flutterfire/issues/new?assignees=&labels=Needs+Attention%2C+type%3A+bug&template=---bug-report.md&title=%F0%9F%90%9B+%5BPLUGIN_NAME_HERE%5D+Your+issue+title+here

Closing since no information is provided.
