### ISSUE TITLE
🐛 [firebase_app_check] App Check is not working with callable cloud functions: `[firebase_functions/unauthenticated] Unauthenticated`

### ISSUE THREAD

**Issue by nilsreichardt** [FirebaseExtended/flutterfire#6794]
## Bug report

**Describe the bug**
If you add `firebase_app_check` to your Flutter projects, callable cloud functions will not work anymore.

Parameter:
* App Check is **not** enforced
* No debug provider is provided

### Steps to reproduce

1. Add `firebase_app_check` to your project
2. Call a callable cloud function

If you remove `firebase_app_check` everything is working.

### Expected behavior
I would expect that I can run a callable cloud function, even if I not enforced Firebase App Token or using no debug provider (because I not enforced it)

### Exception
**Flutter**
```sh
flutter: [firebase_functions/unauthenticated] Unauthenticated
#0      StandardMethodCodec.decodeEnvelope
package:flutter/…/services/message_codecs.dart:597
#1      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:158
<asynchronous suspension>
#2      MethodChannelHttpsCallable.call
package:cloud_functions_platform_interface/…/method_channel/method_channel_https_callable.dart:22
<asynchronous suspension>
#3      HttpsCallable.call
package:cloud_functions/src/https_callable.dart:34
<asynchronous suspension>
#4      _FutureBuilderState._subscribe.<anonymous closure> (package:flutter/src/widgets/async.dart)
package:flutter/…/widgets/async.dart:1
<asynchronous suspension>
```

**Cloud Function**
```sh
Failed to validate AppCheck token. FirebaseAppCheckError: Decoding App Check token failed. Make sure you passed the entire string JWT which represents the Firebase App Check token.
    at FirebaseAppCheckError.FirebaseError [as constructor] (/workspace/node_modules/firebase-admin/lib/utils/error.js:44:28)
    at FirebaseAppCheckError.PrefixedFirebaseError [as constructor] (/workspace/node_modules/firebase-admin/lib/utils/error.js:90:28)
    at new FirebaseAppCheckError (/workspace/node_modules/firebase-admin/lib/app-check/app-check-api-client-internal.js:187:28)
    at /workspace/node_modules/firebase-admin/lib/app-check/token-verifier.js:82:19
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  errorInfo: {
    code: 'app-check/invalid-argument',
    message: 'Decoding App Check token failed. Make sure you passed the entire string JWT which represents the Firebase App Check token.'
  },
  codePrefix: 'app-check'
}
```
```
Callable request verification failed: AppCheck token was rejected. {"verifications":{"auth":"MISSING","app":"INVALID"}}
```
### Sample project

**GitHub Repository**
You can find the source code under this link: https://github.com/nilsreichardt/playground/tree/firebase-app-check-cloud-function-unauthenticated-issue/firebase-app-check-cloud-functions-unauthentificated

**main.dart**
```dart
import 'package:cloud_functions/cloud_functions.dart';
import 'package:firebase_app_check/firebase_app_check.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Firebase.initializeApp();
  await FirebaseAppCheck.instance.activate();

  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: FutureBuilder<HttpsCallableResult<String>>(
              future: FirebaseFunctions.instance
                  .httpsCallable('helloWorld')
                  .call<String>(),
              builder: (context, future) {
                if (future.hasError)
                  return Text(future.error?.toString() ?? "Error");

                if (!future.hasData) return CircularProgressIndicator();

                final result = future.data;
                return Text(result!.data);
              }),
        ),
      ),
    );
  }
}
```

**index.ts**
```ts
import * as functions from "firebase-functions";

export const helloWorld = functions.https.onCall(async (data, context) => {
    return "Working";
});
```
---

## Additional context

![image](https://user-images.githubusercontent.com/24459435/129021319-b8eb1e7f-b191-4437-b426-e7000f0d72bb.png)

Unregistered or registered (App Attest or Device Check) makes no difference.

I find also another StackOverflow question from a different user: https://stackoverflow.com/questions/68679583/firebase-app-check-cloud-functions-failed-to-validate-appcheck-token?noredirect=1#comment121481062_68679583

### Tested Device
MacBook Pro M1, tested on iOS Simulator and iPad 2019

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.3 20E232 darwin-arm, locale en-DE)
[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc5)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[!] Android Studio
    ✗ Unable to find bundled Java version.
[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.2)
[✓] VS Code (version 1.60.0-insider)
[✓] Connected device (3 available)
    ! Error: iPhone von Roland is not connected. Xcode will continue when iPhone von Roland is connected. (code -13)

! Doctor found issues in 2 categories.
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```yaml
dependencies:
  flutter:
    sdk: flutter

  cloud_functions: ^3.0.0
  firebase_core: ^1.4.0
  firebase_app_check: ^0.0.1+3
```

```
Dart SDK 2.13.4
Flutter SDK 2.2.3
firebaes_app_check_cf_unauthenticated 1.0.0+1

dependencies:
- cloud_functions 3.0.0 [cloud_functions_platform_interface cloud_functions_web firebase_core firebase_core_platform_interface flutter]
- firebase_app_check 0.0.1+3 [firebase_app_check_platform_interface firebase_app_check_web firebase_core firebase_core_platform_interface flutter]
- firebase_core 1.4.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- async 2.6.1 [meta collection]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.1.0
- charcode 1.2.0
- clock 1.1.0
- cloud_functions_platform_interface 5.0.8 [firebase_core flutter meta plugin_platform_interface]
- cloud_functions_web 4.0.10 [cloud_functions_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- collection 1.15.0
- fake_async 1.2.0 [clock collection]
- firebase_app_check_platform_interface 0.0.1+3 [firebase_core flutter meta plugin_platform_interface]
- firebase_app_check_web 0.0.1+3 [firebase_app_check_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_core_platform_interface 4.0.1 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.1.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- js 0.6.3
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- path 1.8.0
- plugin_platform_interface 2.0.1 [meta]
- sky_engine 0.0.99
- source_span 1.8.1 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.3.0 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0 [collection]
- vector_math 2.1.0
```
</details>

---

**Comment by Tom3652** [comment]
Having the same issue as i asked about it on [StackOverFlow](https://stackoverflow.com/questions/68679583/firebase-app-check-cloud-functions-failed-to-validate-appcheck-token)

**Comment by maksymmalyhin** [comment]
@nilsreichardt @Tom3652 Thank you for the repot. Looks like the following App Check details lead to the behaviour you observer:
1. On the Firebase SDKs side when a valid App Check token cannot be obtained, a dummy App Check token is sent with HTTP requests to Functions
2. Firebase Functions cannot use the project enforcement settings due to technical limitation, instead the enforcement should be implemented in the function itself
3. Functions code tries to pars and validate the App Check token before calling `onCall` function:
    - if there is no App Check token, then the function is called with `context.app == undefined`
    - if there is an invalid App Check token the function will fail with the error you observe
    - if there is a valid App Check token then `context.app` will be populated based on it

The Functions behaviour was implemented so to match handling of Auth tokens, but we are considering improvements to it to avoid such confusions in the future. In the meanwhile you can try the following workarounds:

1. Don't install App Check SDK (remove `firebase_app_check: ^0.0.1+3` from your dependencies)
2. Configure DeviceCheck or/and App Attest attestation providers for your app to run on devices and Debug provider for your simulators/emulators

Please let us know if workarounds work for you.

**Comment by Tom3652** [comment]
@maksymmalyhin thanks for your answer !

Removing the App Check SDK was enough in my case indeed, but it can be a problem later if we "need" to use the SDK.
Anyway i will probably finish the setup but later with enforcement, for now it's working again and RealTime DB + Cloud Storage are still checked by App Check, so thank you.

**Comment by gOzaru** [comment]
Try updating Firebase SDK on build.gradle
It works for me.
See Project Settings > General > Your Apps > See SDK Instructions.

**Comment by nilsreichardt** [comment]
@markusaksli-nc In #6675 the author said, that it's working on physical devices (see https://github.com/FirebaseExtended/flutterfire/issues/6675#issuecomment-885668486). But I could also reproduce it on my iPad 2019 (real device).

**Comment by MaciejCaputa** [comment]
@maksymmalyhin I've managed to configure AppCheck for iOS using swift and it works with callable functions but the same approach for Android fails for callable functions.

**Comment by mikehardy** [comment]
Cross linking with react-native-firebase as we are similarly afflicted https://github.com/invertase/react-native-firebase/issues/5622

Here are the thoughts I mentioned there:

> This needs a reproduction on one (or the other) of the native APIs I think, probably easiest with firebase-ios-sdk since AppCheck there needs no extra configuration, you just include it and by default you get the DeviceCheck provider (which should trigger the error) - so starting from https://github.com/firebase/quickstart-ios/tree/master/functions and logging an issue upstream is probably the fastest way

**Comment by nilsreichardt** [comment]
@maksymmalyhin Is this correct, that we just need to wait until https://github.com/firebase/firebase-ios-sdk/pull/8558 is merged and published? So we need then only need to increase the Firebase iOS SDK Version in the `firebase_app_check` Flutter package and everything should be working?

**Comment by MaciejCaputa** [comment]
@nilsreichardt What bout android? Is similar fix planned?

**Comment by mikehardy** [comment]
@MaciejCaputa does firebase-android-sdk suffer the same problem? If it does not have an upstream issue logged in that repo then there will be no fix - if you've tested android and see this same behavior there, you'll need to search their issues list to see if it's noted already, and if not, log an issue

**Comment by maksymmalyhin** [comment]
Sorry for long silence, let me provide the updates.

- after some discussion we agreed to apply the following fixes:
  - Android, Apple and Web Functions SDKs will not send the dummy Firebase App Check token as it is mostly useless for Functions. Apple SDK fix was implemented in firebase/firebase-ios-sdk#8558 and should be available in the next SDK release. Android and Web SDK changes will follow soon. FireFlutter plugin will need to use the updated Functions SDK version.
  - Callable Functions implementation will be updated to handle an empty and invalid Firebase App Check token in the same way. `onCall` will be called with `context.app == undefined` for both cases, so control of enforcement of App Check will be in the function body only (basically as it is described in the [docs](https://firebase.google.com/docs/app-check/cloud-functions?authuser=0#add_support_to_a_function))
- After the fixes, it will be possible to call the functions with no App Check enforcement configured in the specified cases. It can be useful when debugging a dev build of your app, etc. But the App Check SDK **should not be installed in you app if the attestation providers are not configured** for it, otherwise the SDK will do wasteful attempts to obtain Firebase App Check token which **will introduce extra latency to the function calls and consume the device resources**.
  -  if FireFlutter plugin doesn't allow to install Functions without App Check, it should be addressed on the plugin side.

**Comment by markusaksli-nc** [comment]
This will still need to wait for a release but feel free to close if you think it doesn't need to be tracked here anymore.

**Comment by gigandre** [comment]
Thank you very much for this fix guys, I've also been facing this problem. 
When are you planning to release this fix?

**Comment by maksymmalyhin** [comment]
@gigandre Apple SDK part is scheduled for the next release which is expected to be public next week. 

But I would like to stress one more time that Firebase App Check SDK should not be installed in your application if you are not planing to configure and use it. And if you actually use it, then proper way to test in the development environment is to configure Debug provider (see [docs](https://firebase.google.com/docs/app-check/ios/debug-providerhttps://firebase.google.com/docs/app-check/ios/debug-provider) for more details.

**Comment by maksymmalyhin** [comment]
@markusaksli-nc Before closing the issue, could you please confirm that FireFlutter allows installing Functions without App Check? The described issue should not be a blocker for developers for most of the cases because the proper way to use Function without App Check is not installing App Check in the app. We need to make sure that it is possible. Thank you.

**Comment by mikehardy** [comment]
@maksymmalyhin 

FlutterFire functions module may be used without App Check module, they are separate.

However, it's important to recognize App Check debug modes are difficult to set up, the developer ergonomics are not comfortable. Specifically:

1) on iOS **you may not change the provider after firebase configure**. In a Flutter (or react-native-firebase) context this is quite painful as it requires AppDelegate.m changes that toggle on a debug provider or not, and cross-platform developers (Flutter, react-native) are typically not Objective-C folks.

2) on iOS again, in order to inject a token into the debug provider if you can get it configured in AppDelegate.m you need to add it to your app launch arguments from Xcode, except cross-platform folks (Flutter, react-ntaive) don't use Xcode typically - it is not a normal workflow at all. And to do inject the shared token from `xcrun simctl` requires an obscure setting (`SIMCTL_CHILD_FIRAAppCheckDebugToken`) to get it through to the app. It works, but almost no one knows how to do this, it's a barrier.

3) on Android to get App Check debug tokens working is maybe not even possible in Flutter at the moment? On react-native-firebase [I made the maybe questionable decision to force DebugProvider if the app was debuggable](https://github.com/invertase/react-native-firebase/pull/5581/files#diff-4de079cdc329034a2fa741cf2643135f7e62579f0429c86fb77f618221460164R47-R57) but FlutterFire doesn't offer that. So developers would need to modify their main Application object in debug mode to set a new provider and then to know in debug to not activate the normal Flutter App Check module since that would override the debug provider. That's a big barrier

4) on Android again, to plumb through a debug token so things validate then requires adding a new dependency to the app `build.gradle` (the firebase-android-sdk app check test helper) which cross-platform developers are not familiar with, and you have to get the token through somehow, which is not easy. I resorted to a [runtime patch](https://github.com/invertase/react-native-firebase/blob/f03589d6eed793b1f61b76d401401bf226799d26/tests/android/app/src/androidTest/java/com/invertase/testing/DetoxTest.java#L32-L59) on react-native-firebase in order to make it work.

I have direct experience from this because [I implemented it for react-native-firebase](https://github.com/invertase/react-native-firebase/pull/5581) and I help on FlutterFire things sometimes. 

I think App Check is amazing, I really like it and was happy to wrap it up and expose it to more developers for use in react-native, but it is currently not that easy to work with in test+debug modes in cross-patform frameworks for the above reasons, and there's no practical option but to include it (with failures in test/debug) if you want to use it all.

So, with all that said, this:

> The described issue should not be a blocker for developers for most of the cases because the proper way to use Function without App Check is not installing App Check in the app. We need to make sure that it is possible.

.. is not practical currently. All firebase modules both live and in emulator should work even if App Check is installed and not generating valid tokens. Otherwise it is *effectively* the equivalent of saying "you can't use App Check right now", even if technically it is possible with a lot of work. It is also not the expectation I have as a developer if I include AppCheck but don't set it to "enforcing" - I'm not expecting a side effect.

Please make it so all firebase modules work if App Check is included but not enforcing :pray:

**Comment by maksymmalyhin** [comment]
@mikehardy Thank you for the detailed feedback. Now I understand the root of the problem better. Yeah, we definitely need to work on debug story for Flutter and React native. Would you mind opening separate issues for the Debug provider support so we can keep a focused discussion and track progress there.

**Comment by mikehardy** [comment]
Sure - let me really think about it a bit - I am really well-versed at how it is at the moment, but it's a big step to go from "this is how it is" to "this is how it should be" and be practical while being prescriptive and staying within what's technically possible. I'll start with an issue on firebase-ios-sdk and tag you there though to see what we can come up with.

**Comment by weixifan** [comment]
@mikehardy Thank you for the valuable feedback! I do want to clarify that including the App Check module while not enforcing is explicitly a supported use case, because that's how we intend for developers to collect metrics and only enforce when they feel comfortable. Cases where the unenforced mode do not work properly are indeed bugs that should be fixed.

**Comment by nilsreichardt** [comment]
I agree with @weixifan. Additionally, existing apps needs to roll out an app version with an unenforced version, to get many active users as possible to the newest version, which supports Firebase App Check. Because enforcing Firebase App Check is a breaking change and will break the app for all users, with didn't installed the latest update. Therefore, every existing app needs a time, where Firebase App Check is in the app, but not enforced.

**Comment by weixifan** [comment]
@nilsreichardt Indeed, the App Check metrics (viewable in the Firebase Console and also in Cloud Monitoring) are designed for precisely this transition phase.

I do want to re-emphasize the point @maksymmalyhin made above, which is that if the provider you chose is not properly configured in the Firebase Console, then the App Check module will cause additional latency and will waste device resources. It is recommended that you depend on the App Check module only when you are ready to begin the transition phase for your app, (starting with an unenforced state, of course).

**Comment by Tom3652** [comment]
In addition, i would say that depending on the application, the quotas and limits are not that clear either : For instance, i have seen the 10k requests per day for the SafetyNet Attestation API.
I could not find anything about Device Check in Apple documentation either.

My point is that any limitation of the App Check would simply block users after it is reached with enforcement, so we need to be really careful before making the transition

**Comment by weixifan** [comment]
With the fix to all three platforms released, calls from devices that fail attestation should no longer result in an error when sending requests to Functions. On the Functions server-side SDK, the `context.app` object should now be `null` in that case, so your code is free to either enforce (reject those requests) or not.

**Comment by nwparker** [comment]
> With the fix to all three platforms released, calls from devices that fail attestation should no longer result in an error when sending requests to Functions. On the Functions server-side SDK, the `context.app` object should now be `null` in that case, so your code is free to either enforce (reject those requests) or not.

Thanks! Which version of [firebase_app_check](https://pub.dev/packages/firebase_app_check/changelog) needs to be used?
Will `0.0.2+1` suffice?

**Comment by mikehardy** [comment]
I think you will probably need to override the underlying SDKs actually - when @weixifan mentions "all three platforms" I think that is referring to firebase-js-sdk / firebase-android-sdk / firebase-ios-sdk, not FlutterFire specifically. 

This appears to be a description of the mechanism: https://firebase.flutter.dev/docs/overview/#overriding-native-sdk-versions then you may refer to the SDK release notes for the correct versions, as a general practice so you know what to specify - https://firebase.google.com/support/release-notes/android (should be 28.4.1?) and https://firebase.google.com/support/release-notes/ios (should be 8.7.0?)

**Comment by nilsreichardt** [comment]
@russellwheatley Are there any plans to update the native sdk for `firebase_app_check` package?
