### ISSUE TITLE
🐛 [FIREBASE_MESSAGING] firebase_messaging/unknown

### ISSUE THREAD

**Issue by flutteresbolivia** [FirebaseExtended/flutterfire#6863]
## Bug report

**Describe the bug**
I have these two errors in some phones, mostly it works fine, but in some phones I get this error.

Can someone tell me what it is or how to solve it?

[firebase_messaging/unknown] java.io.IOException: java.util.concurrent.ExecutionException: java.io.IOException: SERVICE_NOT_AVAILABLE

[firebase_messaging/unknown] java.io.IOException: java.util.concurrent.ExecutionException: java.io.IOException: FIS_AUTH_ERROR

> Android
> Version:9
> SM-G9650
> Model:PPR1.180610.011

> Android
> Version:10
> 
> STK-LX3
> Model:HUAWEISTK-LX3
> 

### Sample project

---

## Additional context

---

### Flutter doctor

[√] Flutter (Channel unknown, 2.0.3, on Microsoft Windows [VersiÃ³n 10.0.19043.1165], locale es-ES)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.59.1)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

**Comment by flutteresbolivia** [comment]
help plis

**Comment by markusaksli-nc** [comment]
Hi @flutteresbolivia 
The errors you mentioned could be caused by just a flaky connection, however, you also seem to be on an outdated flutter version.
You should upgrade to the latest flutter stable version, make sure you are using the latest versions of the plugins, and make sure you are not manually overriding the native Firebase SDK versions in your `android/app/build.gradle`.
Make sure the devices have a stable internet connection or test on a different network.
Thank you
