### ISSUE TITLE
[firebase_auth] Invalid SMS verification code exception not handled on iOS

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#687]
The invalid SMS verification code exception is not handled on the native side on iOS, and as such, when the wrong verification code is entered, onVerificationCode does not get called, and the plugin prints out the following log in the console:
```
Unhandled exception:
PlatformException(Error 17044, FIRAuthErrorDomain, The SMS verification code used to create the phone auth credential is invalid. Please resend the verification code SMS and be sure to use the verification code provided by the user.)
```

**Comment by kroikie** [comment]
@derTuca

The issue at https://github.com/flutter/flutter/issues/21117 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by kalegd** [comment]
This error occurs if you haven't set up your SHA certificate fingerprints. It might not be the only reason it occurs, but hopefully helps some of you

**Comment by espadafajar** [comment]
> 
> 
> This error occurs if you haven't set up your SHA certificate fingerprints. It might not be the only reason it occurs, but hopefully helps some of you

still not work till january 2020

**Comment by neenabastin123** [comment]
same issue for me also

**Comment by hungtran2492** [comment]
do you guys have any solution?

**Comment by GJJ2019** [comment]
I have also the same problem. I have build another screen for manual code completion & left [PhoneVerificationCompleted](https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_auth/firebase_auth/example/lib/signin_page.dart) method empty.

So the soln to this problem is to call this method & do other after verification stuff in this method like this :
`final PhoneVerificationCompleted verificationCompleted =(AuthCredential phoneAuthCredential) {`
`      print('Verified successfully');`
`// Do your after verification stuff here`
`    };`
Then your phone number will automatically get verified 😄 no need to manually enter code

**Comment by Ehesp** [comment]
Please try using the latest version of the plugins. 

Closing as I think this is now fixed. Please let me know otherwise.
