### ISSUE TITLE
🐛 [google_sign_in] Everytime need to signin!

### ISSUE THREAD

**Issue by Puspharaj** [FirebaseExtended/flutterfire#7028]
I believe it's a common thing, When one started to work on the flutter  web to signing to see how the entire signing echo system works. 

The problem seems to evident that when I try to run the app. The VSCODE starts the web app on a new chrome window, I have never signed in(Always happen when VSCODE try to make new window), Mean I have other instance of chrome which I already signed in. 

Here the problem raises, Every time I need to sign in to check app functionality by signing again, If I close the browser accidentally or Boot the system to work on the project. This seems giving me trouble meaning I have to go through 2 step sign in method to get it work(Cumbersome). 

I found a way to solve it, By running flutter run -d web-server --web-port 5000, It works nice and I'm able to jumb into the HomePage without singing in from the LogInPage.  Unfortunately debug functionality has gone. Mean I have no way to debug the app.

I'm stuck in the loop of sign in multiple times that's cumbersome.

Is there anyway to resolve this issue? I believe this occurs more than 2 years nobody has took in charge of it.

**Comment by markusaksli-nc** [comment]
Hi @Puspharaj 
As I have explained to you before this isn't something any of the plugin holders or flutter can just "fix" since it's a result of how cache works for modern browsers. The **only** solution here is to use a consistent port when running your app on web.

This can be easily done from the terminal with
```
flutter run -d chrome --web-port 8080
```

Or you can add the `"--web-port 8080"` argument to your VSC `launch.json` in the `"args" : [ ]` key.
If you can't easily debug the app when running the webserver then just don't run it on webserver and run it on chrome instead with the same argument.

Closing the issue since as I explained this is an easily solvable issue and isn't something we can take charge of and fix
