### ISSUE TITLE
[firebase_database] DataSnapshot.forEach() feature request

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#711]
Firebase Realtime Database client on Javascript has a great convenience method you can call on a `.once()` or `.onValue()` snapshot called forEach. It iterates through all snapshots and presents each one individually.

This feature is greatly missed in Flutter's `firebase_database` package. I find that breaking apart multiple DataSnapshots is verbose and you lose the static typing that would be so useful.

**Comment by kroikie** [comment]
@lukepighetti

The issue at https://github.com/flutter/flutter/issues/20524 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by dotdoom** [comment]
The problem here is that by the time `forEach` is called, the initial data structure in Java is already gone.

Flutter either has to keep a reference to that structure (which creates a problem of determining when it should be released), or recursively call [`DataSnapshot.getChildren`](https://firebase.google.com/docs/reference/android/com/google/firebase/database/DataSnapshot#public-iterabledatasnapshot-getchildren-) to precache the value before the structure is converted to Dart native types (which may come with performance penalty).

**Comment by Salakar** [comment]
Closing as this should be addressed as part of #753 - thanks!
