### ISSUE TITLE
In foreground FirebaseMessaging.onMessageOpenedApp.listen not working

### ISSUE THREAD

**Issue by thuva28** [FirebaseExtended/flutterfire#7380]

**Comment by darshankawar** [comment]
@thuva28 
When opening an issue, please use the issue [template](https://github.com/FirebaseExtended/flutterfire/issues/new?assignees=&labels=Needs+Attention%2C+type%3A+bug&template=---bug-report.md&title=%F0%9F%90%9B+%5BPLUGIN_NAME_HERE%5D+Your+issue+title+here) and provide the requested details, so that we can properly address this issue. Just adding a title of the issue you are facing won't help much to analyze or make this issue actionable.
Closing, as no information is provided.
