### ISSUE TITLE
🐛 [firebase_messaging] Firebase firestore database is locked (Sqlite code 5 SQLITE_BUSY)

### ISSUE THREAD

**Issue by ViniciusSossela** [FirebaseExtended/flutterfire#7384]
Is this example a good one for handling background messaging with Firebase/Firestore integration? 
It seems to have a problem;

https://github.com/FirebaseExtended/flutterfire/blob/e00c36ea1ecfa64b66d4f1e62def63123a382225/packages/firebase_messaging/firebase_messaging/example/lib/main.dart#L28

Issue reference: https://github.com/FirebaseExtended/flutterfire/issues/6087

**Comment by darshankawar** [comment]
@ViniciusSossela 
The method `_firebaseMessagingBackgroundHandler` is defined as a top-level function and `await Firebase.initializeApp()` need to be called inside it because when app is in background, handling messaging is a bit different as compared to when app is in foreground or terminated.  See the relevant [document](https://firebase.flutter.dev/docs/messaging/usage#background-messages) for further details on it.






> It seems to have a problem;

Only if there are multiple initializations of the apps. In that case, we need to call that method for every Firestore instance as mentioned in the comments. 

```
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  // If you're going to use other Firebase services in the background, such as Firestore,
  // make sure you call `initializeApp` before using other Firebase services.
```
