### ISSUE TITLE
🐛 [Firebase Hosting] Listview made from Json received from Heroku backend not showing

### ISSUE THREAD

**Issue by nyck33** [FirebaseExtended/flutterfire#7424]
My app runs fine on mobile and web locally but after `firebase deploy` when I get to the coupon screen that requests json from Heroku backend, nothing displays.  
Is this something I can debug with Crashlytics?  My Heroku logs show 200 OK each time.
Please go here: https://coupon-firebase.web.app/#/login
Sign in with Linkedin will get you in with no credentials.  
Then click Guest Services in bottom navigation bar.  
Once there, click the R2D2 card in the card grid.
Clicking that makes a call to the backend and navigates to the Coupon Screen.
But it does not show.
Master branch here:  https://github.com/nyck33/coupon_app for reference.
Git cloning the repo and on master branch, `flutter run -d chrome` or `flutter run`, the app works as expected.

**Comment by maheshmnj** [comment]
Hi @nyck33 I believe this issue doesn't belong here, Because this issue seems related to firebase hosting. For the list of flutterfire supported plugins please see  https://firebase.flutter.dev/.

Closing as this isn't an issue with flutterfire, if you disagree feel free to write in the comments and I will reopen it.

On a side note, I would suggest you to try deploying the same app on other hosting services like netify or github pages and see if it works.

Thanks

**Comment by nyck33** [comment]
@maheshmnj 
I'm so sorry to have wasted your valuable time.  I just did that CORS on the FastAPI backend to include localhost with any port using a regex and forgot to add my new url.

**Comment by nyck33** [comment]
It still does not display although I see 200 OK and the JSON in my web developers tool for Chrome.

**Comment by nyck33** [comment]
@maheshmnj firebase hosting is not listed on that link.
Where do I file any issues?

**Comment by nyck33** [comment]
What solved it was doing `flutter build web --release --web-renderer html` rather than just `flutter build web`
