### ISSUE TITLE
🐛 [FIREBASE_MESSAGING] APNS TOKEN not work

### ISSUE THREAD

**Issue by JeanPOAlves** [FirebaseExtended/flutterfire#7445]
I cannot receive push on iOS.
I follow everything on the doc and it won't.

when doing in the code:
await FirebaseMessaging.instance.getAPNSToken();
Returns null.
and :
await FirebaseMessaging.instance.getToken();
returns a message:
APNS device token not set before retrieving FCM Token for Sender ID

**Comment by JeanPOAlves** [comment]
On another device it worked, not sending via token, but a message to all devices,
What can it be?
the iOS version that worked is: 15.1
the iOS version that doesn't work: 13.1.3

> @JeanPOAlvesAo abrir um problema, use o [modelo ](https://github.com/FirebaseExtended/flutterfire/issues/new?assignees=&labels=Needs+Attention%2C+type%3A+bug&template=---bug-report.md&title=%F0%9F%90%9B+%5BPLUGIN_NAME_HERE%5D+Your+issue+title+here)e preencha os detalhes solicitados para que possamos analisá-lo usando-lo.
> 
> Você pode tentar o mesmo cenário em outro dispositivo ios e ver se ele persiste ou não?

On another device it worked, not sending via token, but a message to all devices,
What can it be?
the iOS version that worked is: 15.1
the iOS version that doesn't work: 13.1.3

**Comment by darshankawar** [comment]
> What can it be?

It's hard to tell without looking at any details. Please check if you've correct set up the notifications per instructed in the [document](https://firebase.flutter.dev/docs/messaging/apple-integration#linking-apns-with-fcm). 

There was similar issue reported which turned out to be device specific issue, https://github.com/FirebaseExtended/flutterfire/issues/7278
