### ISSUE TITLE
🐛 [firebase_auth] Phone Auth Issue In Flutter web

### ISSUE THREAD

**Issue by CoderJerry** [FirebaseExtended/flutterfire#7452]
## Bug report

even with the whitelisted phone number in firebase console , firebase auth in flutter web is throwing this error
[firebase_auth/too-many-requests] We have blocked all requests from this device due to unusual activity. Try again later.

**Comment by darshankawar** [comment]
@CoderJerry 
The exception you are getting `[firebase_auth/too-many-requests] We have blocked all requests from this device due to unusual activity. Try again later.` is coming from firebase and blocked by them and not by `firebase_auth` plugin.
The `firebase_auth` plugin has correctly captured and triggered the exception coming from firebase, ie, `too-many-requests` so this isn't an issue with the plugin. You'll need to reach out to firebase sdk github for further resolution.

Closing from here.
