### ISSUE TITLE
[firebase_messaging] Deliver notification to system tray even when the app is in the foreground.

### ISSUE THREAD

**Issue by seriiix** [FirebaseExtended/flutterfire#75]
From [doc](https://pub.dev/packages/firebase_messaging#receiving-messages), `onMessage` is called when a user receives notification in the foreground but I need to receive notification in the system tray. Is this possible?

**Comment by Salakar** [comment]
Looks like this now possible, the doc you linked states the various states `onMessage` works in;

![image](https://user-images.githubusercontent.com/5347038/79756899-3ed53980-8313-11ea-8c6b-448d5ec775fe.png)

**Comment by MindaugasVarkalys** [comment]
@Salakar 
Looking into the title of the issue, I think the question was not about the `onMessage` being called in different app states. The problem here is when the notification is received and the app is in foreground, it only calls `onMessage` but the notification is not delivered to system tray.

Is it possible to make notification to be deliver independent on the app state?
