### ISSUE TITLE
🐛 firebase_dynamic_links - Getting Null for Dynamic Link

### ISSUE THREAD

**Issue by balajiks-dev** [FirebaseExtended/flutterfire#7555]
This is my dynamic link code. I have added link in my Firebase Console also. But still am not getting data. It's null. Any guide or solutions will be good. 

```
` void initDynamicLinks() async {
    final PendingDynamicLinkData data = await FirebaseDynamicLinks.instance.getInitialLink();
    final Uri deepLink = data?.link;
    
if (deepLink != null) {
      Navigator.pushNamed(context, deepLink.path);
    }

    FirebaseDynamicLinks.instance.onLink(
      onSuccess: (PendingDynamicLinkData dynamicLink) async {
        final Uri deepLink = dynamicLink?.link;

        if (deepLink != null) {
          Navigator.pushNamed(context, deepLink.path);
        }
      },
      onError: (OnLinkErrorException e) async {
        print('onLinkError');
        print(e.message);
      }
    );
  }`
```

**Comment by darshankawar** [comment]
@balajiks-dev 
Since this repo is to track bugs and feature requests, I believe your issue should be filed on support channels like StackOverflow as you are seeking a solution or guidance. I am going ahead and closing it.
In order to confirm your code implementation is correct, please check the official plugin [documentation](https://firebase.flutter.dev/docs/dynamic-links/usage/) for implementation and see if it helps to resolve. If you think your implementation is correct, and `null` is occuring due to bug in plugin, write in comments by providing all requested details in the issue template and we'll address this issue.
Thanks.

**Comment by thermanos** [comment]
@balajiks-dev What is your flutter version? I'm experiencing similar issue since upgrading to 2.8.0

**Comment by balajiks-dev** [comment]
@thermanos  Am using Flutter version - 2.5.3
