### ISSUE TITLE
firebase database integer key is reading null  issue

### ISSUE THREAD

**Issue by Navaf-N** [FirebaseExtended/flutterfire#7595]
integer key reading null issue

**Comment by darshankawar** [comment]
@Navaf-N 
When opening an issue, please use the new issue [template](https://github.com/FirebaseExtended/flutterfire/issues/new?assignees=&labels=Needs+Attention%2C+type%3A+bug&template=---bug-report.md&title=%F0%9F%90%9B+%5BPLUGIN_NAME_HERE%5D+Your+issue+title+here) and fill out requested details so that it'll help to properly address the issue. 
Closing for now, as no details are provided. Please use the template.
