### ISSUE TITLE
SocketException: OS Error: Operation timed out, errno = 60, address = firebasestorage.googleapis.com, port = 55369. Error thrown null.

### ISSUE THREAD

**Issue by sspogra** [FirebaseExtended/flutterfire#7675]
## Bug report

**Describe the bug**
App Crash on iOS

### Steps to reproduce

2. '...'
4. See error or incorrect behavior

### Sample project

Providing a minimal example project which demonstrates the bug in isolation from your main App _greatly_ enhances the chance of a timely fix.
Please link to the public repository URL.

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

**Comment by darshankawar** [comment]
@sspogra 
I don't think this is related to flutterfire plugins. Maybe you filed it here based on the fact that the address points to firebasestorage.googleapis.com.
But this could be happening due to network connection or slow speed. 
Closing from here. Please look for similar issues on Stackoverflow and see if they help.
