### ISSUE TITLE
📚 [firebase_crashlytics] What is the correct installation in iOS?

### ISSUE THREAD

**Issue by kmartins** [FirebaseExtended/flutterfire#7717]
In the **FlutterFire** documentation is this

![flutterfire](https://user-images.githubusercontent.com/10598983/147498030-b59a9ae0-f1ad-472b-97de-7ab0bccb65be.png)

https://firebase.flutter.dev/docs/crashlytics/overview/#b-ios

But in official **Firebase** documentation is this:

![firebase_doc](https://user-images.githubusercontent.com/10598983/147497968-aa27c9ae-4c7e-44c4-b0e0-d567752ee93c.png)

https://firebase.google.com/docs/crashlytics/get-started?platform=ios

**Comment by maheshmnj** [comment]
Hi @kmartins, you should be referring to flutterfire documentation. I am not much familiar with native IOS but I believe the second documentation is more specific to native IOS.

**Comment by russellwheatley** [comment]
@kmartins, yes, it is different because you have to run the symbol upload script manually **when you initialise your Firebase app from dart** . This is why the link you posted says:

> Dart-only Firebase initialization currently only supports reporting Dart exceptions. To report native Android & iOS exception please follow the Android platform Setup section from the manual installation guide and the steps below.

You do not have to follow these instructions if you're using the [manual installation](https://firebase.flutter.dev/docs/manual-installation) process for providing Firebase app configuration required at app initialization (i.e `Firebase.initializeApp()`).

**Comment by kmartins** [comment]
Thanks for the answer @russellwheatley. So but the part of the native configuration shouldn't follow the official documentation of the **Firebase**? On **Android**, the `flutterfire documentation` is similar to the `firebase documentation` in **step 3**.
