### ISSUE TITLE
[FlutterFire_ui] Google Sign-in with a different account is not working.

### ISSUE THREAD

**Issue by mdkamrulislam-web** [FirebaseExtended/flutterfire#7801]
When I Sign-in with one of my Google accounts the sign-in works perfectly. but after signing out, when I try to sign in with a different account, instead of popping up the google accounts list the app directly sign-ins to the previous account I signed in to.

This is my Code Repository Link:
https://github.com/mdkamrulislam-web/flutter_fire_ui

**Comment by darshankawar** [comment]
@mdkamrulislam-web 
I think you wanted to open this issue as a bug but accidentally opened it as a documentation one.
Anyways, I cloned your repo but were getting some compile errors, so I tried the official flutterfire_ui plugin [example](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/flutterfire_ui/example) using latest stable version (2.8.1) and ran it on iOS simulator, wherein, I observed expected behavior as below:

1. Logged in as gmail user:

<img width="373" alt="Screenshot 2022-01-07 at 4 39 14 PM" src="https://user-images.githubusercontent.com/67046386/148535756-ea24698d-f6f1-4199-b716-3f30a8169ac8.png">


2. Logged out and then logged in again using Google sign in which showed me list of accounts to choose from:

<img width="379" alt="Screenshot 2022-01-07 at 4 39 36 PM" src="https://user-images.githubusercontent.com/67046386/148535861-3e1b7ea7-76ba-4e95-95ce-b5f9cef6c6ee.png">

Can you try the same example and see if it works ?

**Comment by brunodmn** [comment]
Same here, not popping up after first login.
Another problem is, when I try to sign in from RegisterScreen (Sign in with Google button), it will not even sign in with old account. Not throwing errors either....
![ezgif com-gif-maker](https://user-images.githubusercontent.com/53493535/148595532-e778899e-fb26-4588-9fd9-139cd215e56c.gif)
.

**Comment by wwnOddbit** [comment]
I am having exactly the same issue as mentioned by @mdkamrulislam-web on Android. However as @darshankawar mentioned, the issue does not happen when running the app in iOS Simulator. I hope we can reopen this issue.

**Comment by lesnitsky** [comment]
this is a valid issue

**Comment by brunodmn** [comment]
Well, a workaround is to use not only `FirebaseAuth.instance.signOut()` but also  `GoogleSignIn().signOut()`. 
This way first user is not cached as 'device default Google account'.

 So, you can create a button instead of using default flutterfire_ui sign out.
 ```
Future<void> signOut() async {
    await FirebaseAuth.instance.signOut();
    await GoogleSignIn().signOut().onError((error, stackTrace) => debugPrint('User is signed with a differente provider'));
  }
```
