### ISSUE TITLE
🐛 [firebase_auth] Unable to get OTP SMS in china.

### ISSUE THREAD

**Issue by developmentkws** [FirebaseExtended/flutterfire#7802]
our app was working fine, after updating firebase_auth , We are not able to get OTP in chinese phone number.
We've connected with VPN to disable Chinese firewall , Infact We were getting OTP before (its been more than 10 Months of publishing app), But suddenly its stopped. 
We have already tried 4 chinese mobile numbers but still unable to get OTP.

**Comment by darshankawar** [comment]
@developmentkws 


> after updating firebase_auth

What version you were on earlier to current ? If you see the plugin changelog, there doesn't seem to be any breaking change that'll lead to OTP feature would not work.

Since you mentioned you are connected with VPN, have you confirmed there aren't any changes related to it or the config / network at your end ?
Also, do you get any error when OTP is not being received ? Can you provide your `flutter doctor -v` too ?

**Comment by ajain-bst** [comment]
+1

Some of my users with Chinese numbers have also started complaining that they have stopped receiving OTPs suddenly, after a recent app upgrade.

Note: all other users are receiving OTP so it is not a problem with my code.
