### ISSUE TITLE
🐛 [firebase_messaging] java.io.IOException: java.util.concurrent.ExecutionException: java.io.IOException: MISSING_INSTANCEID_SERVICE

### ISSUE THREAD

**Issue by Purvik** [FirebaseExtended/flutterfire#7808]
Exception
java.io.IOException: java.util.concurrent.ExecutionException: java.io.IOException: MISSING_INSTANCEID_SERVICE
![Screenshot 2022-01-06 at 7 42 30 PM](https://user-images.githubusercontent.com/9566570/148395901-21c14608-11a9-4a15-9873-8a9ca1d68d28.png)

Check attached SS for details as there is no stack-trace we found.

Environment
Flutter 2.5.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 18116933e7 (3 months ago) • 2021-10-15 10:46:35 -0700
Engine • revision d3ea636dc5
Tools • Dart 2.14.4

Android AVD
Galaxy Tab A Lite

Code which is causing exception
```
this._firebaseToken = await FirebaseMessaging.instance.getToken();
```

File inside pub causing issue:
```
/Users/user/.pub-cache/hosted/pub.dartlang.org/firebase_messaging_platform_interface-3.0.9/lib/src/method_channel/method_channel_messaging.dart
```
![Screenshot 2022-01-06 at 7 45 26 PM](https://user-images.githubusercontent.com/9566570/148396340-614d1ed8-d741-43ef-b430-4abd553eba55.png)

**Comment by darshankawar** [comment]
@Purvik 
The error you are getting `MISSING_INSTANCEID_SERVICE` is due to token not getting generated and that's because the devices you are using may no support Google Play Service. Only devices with Google Play are supported.
See this [link](https://developers.google.com/android/reference/com/google/android/gms/iid/InstanceID#ERROR_MISSING_INSTANCEID_SERVICE) for more details. 

You can try on Google Play Service enabled device / tablet or emulator and see if you still get exception or not.
For now, I am closing this as a non-issue.
