### ISSUE TITLE
🐛 [flutterfire-cli] Creating a project with less than 4 letters results in an error 400

### ISSUE THREAD

**Issue by fodil-a** [FirebaseExtended/flutterfire#7877]
## Bug report

**Describe the bug**
Create a firebase project through the flutterfire-cli with less than 4 letters (example: nld)
It results in a firebase error (HTTP error code 400)

### Steps to reproduce

1. Execute flutterfire config
2. Choose "create a new project"
4. Type a project with less than 4 letters (exemple: nld)

### Expected behavior

Typing the name should result in a validation error, because firebase needs at least 4 characters.

**Comment by darshankawar** [comment]
@fodil-a 
Since you are using the CLI tool and its command `flutterfire configure` to create a new project, according to CLI documentation, any issues related to CLI tool need to be reported in dedicated repo: https://github.com/invertase/flutterfire_cli/issues. https://firebase.flutter.dev/docs/cli/#reporting-an-issue
So please open this issue in above repo.
Closing from here.
