### ISSUE TITLE
UniversalTextFormField autocorrect

### ISSUE THREAD

**Issue by ArslanBouzid** [FirebaseExtended/flutterfire#7893]
Hey Guys,

Is there a reason why autocorrect is not used in UniversalTextFormField ?
(it can just be passed to CupertinoTextFormFieldRow and TextFormField)

Thanks

**Comment by darshankawar** [comment]
@ArslanBouzid 
Is this specific to any flutterfire plugin ?

**Comment by ArslanBouzid** [comment]
Tested on the latest version:
flutterfire_ui: 0.3.1

**Comment by darshankawar** [comment]
@ArslanBouzid 
Since this is more of an enhancement to the plugin, according to the document: https://firebase.flutter.dev/docs/ui/overview/#roadmap--features, feature requests and questions need to be opened in discussion thread as you have done already. So I advise you to follow-up in it.
Closing from here.
