### ISSUE TITLE
🐛 [PLUGIN_NAME_HERE] Your issue title here

### ISSUE THREAD

**Issue by shah000** [FirebaseExtended/flutterfire#8087]
![image](https://user-images.githubusercontent.com/48676720/153926820-d6c2ebb9-b9c1-476d-9fd9-9c25a4b04eaa.png)
_TypeError (type 'String' is not a subtype of type 'Iterable<dynamic>')
![image](https://user-images.githubusercontent.com/48676720/153926873-76782199-4ad0-4cf9-9e39-3af691a13201.png)
data read using model but cannot access  KEYS why?

**Comment by darshankawar** [comment]
@shah000 
When opening an issue, please use new issue template and fill out requested details so that we'll have enough details to analyse the issue. Please don't just post screenshots of the issue which doesn't help much to debug further.

Closing, as no information is provided. Please use new issue template.
