### ISSUE TITLE
🐛 [firebase_messaging] Not able to use VOIP because of background notification issue

### ISSUE THREAD

**Issue by abusaadp** [FirebaseExtended/flutterfire#8177]
## Bug report

Hi,
 I am using this plugin for voip in my Android app. Presently I am getting both foreground and background notifications. In foreground notifications my app is working fine and I am able to initiate a call and integrate it with WebRtc. But when I get a background notification I am not able to initiate a call as all my variables of the app are null in the background notification. This is because a new isolate is spawned in a background notification. Also in this link https://firebase.flutter.dev/docs/messaging/usage/#background-messages it is said that 

'''Since the handler runs in its own isolate outside your applications context, it is not possible to update application state or execute any UI impacting logic. You can, however, perform logic such as HTTP requests, perform IO operations (e.g. updating local storage), communicate with other plugins etc.'''

So we cannot do anything with that notification. In almost all of the example projects using this plugin I see only print statement in the backgroundHandler. I would like to initiate a call and when the call is accepted start a WebRtc interface. All this is working in the foreground notification. I would like to know how to communicate with the foreground isolate when I get a background notification. Also how to bring the app to foreground for Android 10 and above. In Android 9 we can bring the app to foreground but not in Android 10. 

I am not sure what to do after receiving the background notification. Please help me in creating a voip app for Android using Flutter.

Thank You.

**Comment by darshankawar** [comment]
@abusaadp 
Have you tried sending a `high_priority` push notification ? 

> Please help me in creating a voip app for Android using Flutter.

This is best suited to be asked on support channels like StackOverflow, or probably start a discussion thread here https://github.com/FirebaseExtended/flutterfire/discussions



> I would like to know how to communicate with the foreground isolate when I get a background notification. Also how to bring the app to foreground for Android 10 and above. In Android 9 we can bring the app to foreground but not in Android 10.

This too is probably better to be asked as part of discussion rather than an issue.

I'll close it from here since this is more of a support question. You can start a discussion thread as shared in link above to get solution on it.

I will also suggest you to ask this in firebase [support](https://firebase.google.com/support) or in native firebase sdk because if native firebase doesn't support it, then most probably firebase_messaging won't support it too, because it is a wrapper around native firebase sdk.

**Comment by abusaadp** [comment]
I did try sending a high_priority push notification. I am getting the notification. But after getting the notification in the background I cannot do anything in the app other than printing a debug statement. I have already asked a stack overflow question [here](https://stackoverflow.com/questions/71282571/not-able-to-use-voip-in-android-using-flutter-because-of-background-notification). 
I can't use VOIP in Android using this plugin because there is no way to make the app come to the foreground if it is a background notification. I am not sure if this issue can be closed without any solution to it by the plugin developers.
