### ISSUE TITLE
Have issue when calling FirebaseAuth.instance

### ISSUE THREAD

**Issue by mhdshuhaib1704** [FirebaseExtended/flutterfire#8188]
![Screenshot (55)](https://user-images.githubusercontent.com/81548346/155837252-bce7def1-53a1-48a3-996f-738d0a9808f9.png)

**Comment by xuala69** [comment]
Having this issue right now, any update?

**Comment by darshankawar** [comment]
@mhdshuhaib1704 
When opening an issue, please use the new issue [template](https://github.com/FirebaseExtended/flutterfire/issues/new?assignees=&labels=Needs+Attention%2C+type%3A+bug&template=---bug-report.md&title=%F0%9F%90%9B+%5BPLUGIN_NAME_HERE%5D+Your+issue+title+here) and fill out requested details so we'll have enough details to analyze this issue.

Closing for now due to lack of any details to make it actionable.

**Comment by JamesBrel** [comment]
me too

**Comment by JamesBrel** [comment]
> ![Screenshot (55)](https://user-images.githubusercontent.com/81548346/155837252-bce7def1-53a1-48a3-996f-738d0a9808f9.png)

I found the solution go check this link: https://flutterhq.com/questions-and-answers/1513/flutter-compile-error-on-firebase-auth-a-non-null-value-must-be-returned-since-the-return-type-never-doesnt-allow-null. 
I upgrade the Flutter and dart to latest version , in end , i get a good result.
