### ISSUE TITLE
🐛 [firebase_auth] can't read keyset; the pref value , GenericIdpKeyset does not exist

### ISSUE THREAD

**Issue by cedvdb** [FirebaseExtended/flutterfire#8240]
Same issue as https://github.com/FirebaseExtended/flutterfire/issues/4651 which is closed. I'm receiving the below error when running integration test on firebase auth sms code verification with an android emulator:

```
E/zzf     ( 1131): Problem retrieving SafetyNet Token: 7: 
I/zzdu    ( 1131): keyset not found, will generate a new one
I/zzdu    ( 1131): java.io.FileNotFoundException: can't read keyset; the pref value      
GenericIdpKeyset does not exist
```

I've added the following dependency but that does not fix the issue when running integration tests

`implementation "androidx.browser:browser:1.3.0"`

**Comment by darshankawar** [comment]
@cedvdb 
Looking at the error log you shared and linked issue, it seem to be coming from native android sdk and may not be an issue from client side.
As a side note, check [this](https://stackoverflow.com/questions/64602707/firebase-phone-authentication-in-flutter) similar issue and see if it helps.

The original issue was closed based on native fix: https://github.com/FirebaseExtended/flutterfire/issues/4651#issuecomment-847821763

But since you are running integration test on firebase auth sms code verification with an android emulator, this might be having different implications. I suggest you to open issue in https://github.com/firebase/firebase-android-sdk/issues to see what they say.

**Comment by cedvdb** [comment]
@darshankawar one thing I know for sure is that flutter fire cli picked up the wrong API key for Android, which had not enough rights, EnCE why I had problems. This is a bug in the cli.

I can't say for sure if that is what gave this error message but it did prevent me from authenticating.

Just to be clear. My issue is resolved but there is an underlying bug in the cli.

**Comment by darshankawar** [comment]
@cedvdb 
Thanks for the update. CLI related issues need to be opened in dedicated repo here: https://github.com/invertase/flutterfire_cli/issues

https://firebase.flutter.dev/docs/cli/#reporting-an-issue

Closing from here since your original issue is resolved.
